// Course content for the audio app.
//
// Each item is one thing the learner learns to SAY.
//   en    – what the English narrator asks for ("How do you say: <en>?")
//   th    – Thai text sent to the Thai voice (never shown unless "peek" is on)
//   rom   – romanization, shown only with "peek" on
//   parts – optional back-chaining steps, played end-first before the whole phrase
//   note  – optional narration after the introduction: segments of {en} or {th}
//
// Placeholders, filled in from the learner's settings:
//   {P}  polite ending for statements  (ครับ khráp / ค่ะ khâ)
//   {Pq} polite ending for questions   (ครับ khráp / คะ khá)
//   {I}  "I"                            (ผม phǒm / ฉัน chǎn)

window.COURSE = {
  units: [
    {
      title: 'Unit 1 · Greetings',
      items: [
        { id: 'hello', en: 'hello', th: 'สวัสดี', rom: 'sa-wàt-dii',
          parts: [{ th: 'ดี', rom: 'dii' }, { th: 'หวัดดี', rom: 'wàt-dii' }],
          note: [{ en: 'Thais use the same word for hello and goodbye.' }] },
        { id: 'particle', en: 'the polite ending word', th: '{P}', rom: '{P}',
          note: [{ en: 'Thais add a polite word to the end of most sentences. It depends on whether the speaker is a man or a woman. For you, it is:' }, { th: '{P}' }] },
        { id: 'hello-polite', en: 'hello, politely', th: 'สวัสดี{P}', rom: 'sa-wàt-dii {P}' },
        { id: 'thanks', en: 'thank you', th: 'ขอบคุณ', rom: 'khɔ̀ɔp-khun',
          parts: [{ th: 'คุณ', rom: 'khun' }] },
        { id: 'thanks-polite', en: 'thank you, politely', th: 'ขอบคุณ{P}', rom: 'khɔ̀ɔp-khun {P}' },
        { id: 'fine', en: "I'm fine", th: 'สบายดี', rom: 'sa-baai-dii',
          parts: [{ th: 'ดี', rom: 'dii' }, { th: 'บายดี', rom: 'baai-dii' }] },
        { id: 'how-are-you', en: 'how are you?', th: 'สบายดีไหม{Pq}', rom: 'sa-baai-dii mǎi {Pq}',
          parts: [{ th: 'ไหม', rom: 'mǎi' }, { th: 'ดีไหม', rom: 'dii mǎi' }],
          note: [{ en: 'The little word at the end turns a sentence into a yes or no question.' }, { th: 'ไหม' }] },
        { id: 'sorry', en: 'sorry, or excuse me', th: 'ขอโทษ{P}', rom: 'khɔ̌ɔ-thôot {P}',
          parts: [{ th: 'โทษ', rom: 'thôot' }] },
        { id: 'no-problem', en: 'no problem, or never mind', th: 'ไม่เป็นไร', rom: 'mâi pen rai',
          parts: [{ th: 'ไร', rom: 'rai' }, { th: 'เป็นไร', rom: 'pen rai' }] },
      ],
    },
    {
      title: 'Unit 2 · Getting by',
      items: [
        { id: 'yes', en: "yes, that's right", th: 'ใช่', rom: 'châi' },
        { id: 'not-right', en: "no, that's not right", th: 'ไม่ใช่', rom: 'mâi châi',
          note: [{ en: 'Putting this word in front makes anything negative.' }, { th: 'ไม่' }] },
        { id: 'understand', en: 'I understand', th: 'เข้าใจ{P}', rom: 'khâo-jai {P}',
          parts: [{ th: 'ใจ', rom: 'jai' }] },
        { id: 'not-understand', en: "I don't understand", th: 'ไม่เข้าใจ{P}', rom: 'mâi khâo-jai {P}' },
        { id: 'slowly', en: 'please speak slowly', th: 'พูดช้าๆ หน่อย{P}', rom: 'phûut cháa-cháa nɔ̀i {P}',
          parts: [{ th: 'หน่อย', rom: 'nɔ̀i' }, { th: 'ช้าๆ หน่อย', rom: 'cháa-cháa nɔ̀i' }] },
        { id: 'pronoun-i', en: 'I, or me', th: '{I}', rom: '{I}',
          note: [{ en: 'Like the polite ending, the word for I depends on the speaker. For you, it is:' }, { th: '{I}' }] },
        { id: 'name-q', en: "what's your name?", th: 'คุณชื่ออะไร{Pq}', rom: 'khun chûue a-rai {Pq}',
          parts: [{ th: 'อะไร', rom: 'a-rai' }, { th: 'ชื่ออะไร', rom: 'chûue a-rai' }] },
        { id: 'nice-to-meet', en: 'nice to meet you', th: 'ยินดีที่ได้รู้จัก{P}', rom: 'yin-dii thîi dâi rúu-jàk {P}',
          parts: [{ th: 'รู้จัก', rom: 'rúu-jàk' }, { th: 'ได้รู้จัก', rom: 'dâi rúu-jàk' }, { th: 'ที่ได้รู้จัก', rom: 'thîi dâi rúu-jàk' }] },
      ],
    },
    {
      title: 'Unit 3 · Food and shopping',
      items: [
        { id: 'water', en: 'water', th: 'น้ำ', rom: 'náam' },
        { id: 'plain-water', en: 'plain drinking water', th: 'น้ำเปล่า', rom: 'náam plàao' },
        { id: 'may-i-have', en: 'may I have', th: 'ขอ', rom: 'khɔ̌ɔ' },
        { id: 'water-please', en: 'may I have plain water, please?', th: 'ขอน้ำเปล่า{P}', rom: 'khɔ̌ɔ náam plàao {P}' },
        { id: 'delicious', en: 'delicious', th: 'อร่อย', rom: 'a-rɔ̀i' },
        { id: 'very-delicious', en: 'very delicious', th: 'อร่อยมาก', rom: 'a-rɔ̀i mâak' },
        { id: 'not-spicy', en: 'not spicy', th: 'ไม่เผ็ด', rom: 'mâi phèt' },
        { id: 'how-much', en: 'how much?', th: 'เท่าไร{Pq}', rom: 'thâo-rài {Pq}' },
        { id: 'this-one', en: 'this one', th: 'อันนี้', rom: 'an níi' },
        { id: 'this-how-much', en: 'how much is this one?', th: 'อันนี้เท่าไร{Pq}', rom: 'an níi thâo-rài {Pq}' },
        { id: 'too-expensive', en: 'too expensive', th: 'แพงไป', rom: 'phɛɛng pai' },
        { id: 'bill', en: 'the bill, please', th: 'เช็คบิลด้วย{P}', rom: 'chék bin dûai {P}' },
        { id: 'toilet', en: 'the toilet', th: 'ห้องน้ำ', rom: 'hɔ̂ng-náam' },
        { id: 'where-toilet', en: 'where is the toilet?', th: 'ห้องน้ำอยู่ที่ไหน{Pq}', rom: 'hɔ̂ng-náam yùu thîi-nǎi {Pq}',
          parts: [{ th: 'ที่ไหน', rom: 'thîi-nǎi' }, { th: 'อยู่ที่ไหน', rom: 'yùu thîi-nǎi' }] },
      ],
    },
    {
      title: 'Unit 4 · Numbers',
      items: [
        { id: 'n1', en: 'one', th: 'หนึ่ง', rom: 'nùeng' },
        { id: 'n2', en: 'two', th: 'สอง', rom: 'sɔ̌ɔng' },
        { id: 'n3', en: 'three', th: 'สาม', rom: 'sǎam' },
        { id: 'n4', en: 'four', th: 'สี่', rom: 'sìi' },
        { id: 'n5', en: 'five', th: 'ห้า', rom: 'hâa' },
        { id: 'n6', en: 'six', th: 'หก', rom: 'hòk' },
        { id: 'n7', en: 'seven', th: 'เจ็ด', rom: 'jèt' },
        { id: 'n8', en: 'eight', th: 'แปด', rom: 'pɛ̀ɛt' },
        { id: 'n9', en: 'nine', th: 'เก้า', rom: 'kâao' },
        { id: 'n10', en: 'ten', th: 'สิบ', rom: 'sìp' },
        { id: 'n20', en: 'twenty', th: 'ยี่สิบ', rom: 'yîi-sìp',
          note: [{ en: 'Twenty is irregular. It is not two-ten.' }] },
        { id: 'n100', en: 'one hundred', th: 'หนึ่งร้อย', rom: 'nùeng rɔ́ɔi' },
        { id: 'baht-100', en: 'one hundred baht', th: 'หนึ่งร้อยบาท', rom: 'nùeng rɔ́ɔi bàat' },
      ],
    },
    {
      title: 'Unit 5 · Money and bargaining',
      items: [
        { id: 'n50', en: 'fifty', th: 'ห้าสิบ', rom: 'hâa-sìp' },
        { id: 'n200', en: 'two hundred', th: 'สองร้อย', rom: 'sɔ̌ɔng rɔ́ɔi' },
        { id: 'n500', en: 'five hundred', th: 'ห้าร้อย', rom: 'hâa rɔ́ɔi' },
        { id: 'n1000', en: 'one thousand', th: 'หนึ่งพัน', rom: 'nùeng phan' },
        { id: 'n1500', en: 'one thousand five hundred', th: 'หนึ่งพันห้าร้อย', rom: 'nùeng phan hâa rɔ́ɔi',
          parts: [{ th: 'ห้าร้อย', rom: 'hâa rɔ́ɔi' }] },
        { id: 'how-many-baht', en: 'how many baht?', th: 'กี่บาท{Pq}', rom: 'kìi bàat {Pq}' },
        { id: 'very-expensive', en: 'very expensive', th: 'แพงมาก', rom: 'phɛɛng mâak' },
        { id: 'cheap', en: 'cheap', th: 'ถูก', rom: 'thùuk' },
        { id: 'cheaper-q', en: 'do you have a cheaper one?', th: 'มีถูกกว่านี้ไหม{Pq}', rom: 'mii thùuk kwàa níi mǎi {Pq}',
          parts: [{ th: 'กว่านี้ไหม', rom: 'kwàa níi mǎi' }, { th: 'ถูกกว่านี้ไหม', rom: 'thùuk kwàa níi mǎi' }] },
        { id: 'discount-q', en: 'can you lower the price a bit?', th: 'ลดหน่อยได้ไหม{Pq}', rom: 'lót nɔ̀i dâi mǎi {Pq}',
          parts: [{ th: 'ได้ไหม', rom: 'dâi mǎi' }, { th: 'หน่อยได้ไหม', rom: 'nɔ̀i dâi mǎi' }],
          note: [{ en: 'Bargaining is normal at markets. Smile and keep it friendly.' }] },
        { id: 'take-it', en: "I'll take it", th: 'เอา{P}', rom: 'ao {P}' },
        { id: 'agreed', en: 'OK, deal', th: 'ตกลง{P}', rom: 'tòk-long {P}' },
        { id: 'dont-want', en: "I don't want it, thanks", th: 'ไม่เอา{P}', rom: 'mâi ao {P}' },
        { id: 'just-looking', en: "I'm just looking", th: 'ดูเฉยๆ{P}', rom: 'duu chǒei-chǒei {P}' },
        { id: 'pay-card', en: 'can I pay by card?', th: 'จ่ายด้วยบัตรได้ไหม{Pq}', rom: 'jàai dûai bàt dâi mǎi {Pq}',
          parts: [{ th: 'บัตรได้ไหม', rom: 'bàt dâi mǎi' }, { th: 'ด้วยบัตรได้ไหม', rom: 'dûai bàt dâi mǎi' }] },
        { id: 'cash', en: 'cash', th: 'เงินสด', rom: 'ngoen-sòt' },
        { id: 'change-money', en: 'the change, money back', th: 'เงินทอน', rom: 'ngoen-thɔɔn' },
        { id: 'atm-where', en: 'where is the ATM?', th: 'ตู้เอทีเอ็มอยู่ที่ไหน{Pq}', rom: 'tûu ee-thii-em yùu thîi-nǎi {Pq}',
          parts: [{ th: 'อยู่ที่ไหน', rom: 'yùu thîi-nǎi' }] },
      ],
    },
    {
      title: 'Unit 6 · Want, have, can',
      items: [
        { id: 'want-to', en: 'I want to', th: 'อยาก', rom: 'yàak' },
        { id: 'go', en: 'to go', th: 'ไป', rom: 'pai' },
        { id: 'want-go', en: 'I want to go', th: 'อยากไป', rom: 'yàak pai',
          note: [{ en: 'Thai often leaves out the word for I when it is obvious.' }] },
        { id: 'eat', en: 'to eat', th: 'กิน', rom: 'kin' },
        { id: 'eat-meal', en: 'to eat a meal', th: 'กินข้าว', rom: 'kin khâao',
          note: [{ en: 'Literally, eat rice. Rice is the meal in Thailand.' }] },
        { id: 'eaten-yet', en: 'have you eaten yet?', th: 'กินข้าวหรือยัง{Pq}', rom: 'kin khâao rǔue yang {Pq}',
          parts: [{ th: 'ยัง', rom: 'yang' }, { th: 'หรือยัง', rom: 'rǔue yang' }],
          note: [{ en: 'Thais often ask this as a friendly greeting, like how are you.' }] },
        { id: 'eaten-already', en: "I've eaten already", th: 'กินแล้ว{P}', rom: 'kin lɛ́ɛo {P}',
          parts: [{ th: 'แล้ว', rom: 'lɛ́ɛo' }] },
        { id: 'have', en: 'to have, or there is', th: 'มี', rom: 'mii' },
        { id: 'have-water', en: 'do you have water?', th: 'มีน้ำไหม{Pq}', rom: 'mii náam mǎi {Pq}' },
        { id: 'dont-have', en: "I don't have any, or there isn't any", th: 'ไม่มี', rom: 'mâi mii' },
        { id: 'can', en: 'can, or able to', th: 'ได้', rom: 'dâi' },
        { id: 'can-q', en: 'is that OK? Can I?', th: 'ได้ไหม{Pq}', rom: 'dâi mǎi {Pq}' },
        { id: 'cannot', en: "can't, or not possible", th: 'ไม่ได้', rom: 'mâi dâi' },
        { id: 'like', en: 'to like', th: 'ชอบ', rom: 'chɔ̂ɔp' },
        { id: 'like-thai-food', en: 'I like Thai food', th: '{I}ชอบอาหารไทย{P}', rom: '{I} chɔ̂ɔp aa-hǎan thai {P}',
          parts: [{ th: 'ไทย', rom: 'thai' }, { th: 'อาหารไทย', rom: 'aa-hǎan thai' }] },
      ],
    },
    {
      title: 'Unit 7 · Getting around',
      items: [
        { id: 'going-where', en: 'where are you going?', th: 'ไปไหน{Pq}', rom: 'pai nǎi {Pq}',
          note: [{ en: 'Another everyday greeting. A vague answer is fine.' }] },
        { id: 'hotel', en: 'hotel', th: 'โรงแรม', rom: 'roong-rɛɛm' },
        { id: 'want-hotel', en: 'I want to go to the hotel', th: 'อยากไปโรงแรม{P}', rom: 'yàak pai roong-rɛɛm {P}' },
        { id: 'airport', en: 'the airport', th: 'สนามบิน', rom: 'sa-nǎam-bin',
          parts: [{ th: 'บิน', rom: 'bin' }] },
        { id: 'go-airport', en: 'go to the airport', th: 'ไปสนามบิน', rom: 'pai sa-nǎam-bin' },
        { id: 'turn-left', en: 'turn left', th: 'เลี้ยวซ้าย', rom: 'líao sáai' },
        { id: 'turn-right', en: 'turn right', th: 'เลี้ยวขวา', rom: 'líao khwǎa' },
        { id: 'straight', en: 'go straight ahead', th: 'ตรงไป', rom: 'trong pai' },
        { id: 'stop-here', en: 'stop here, please', th: 'จอดตรงนี้{P}', rom: 'jɔ̀ɔt trong níi {P}',
          parts: [{ th: 'ตรงนี้', rom: 'trong níi' }] },
        { id: 'near', en: 'near', th: 'ใกล้', rom: 'klâi' },
        { id: 'far', en: 'far', th: 'ไกล', rom: 'klai',
          note: [{ en: 'Near and far differ only in tone. Listen to both.' }, { th: 'ใกล้' }, { th: 'ไกล' }] },
        { id: 'far-q', en: 'is it far?', th: 'ไกลไหม{Pq}', rom: 'klai mǎi {Pq}' },
      ],
    },
    {
      title: 'Unit 8 · Taxis and transport',
      items: [
        { id: 'taxi', en: 'taxi', th: 'แท็กซี่', rom: 'thɛ́k-sîi' },
        { id: 'car', en: 'car', th: 'รถ', rom: 'rót' },
        { id: 'here', en: 'here, this place', th: 'ที่นี่', rom: 'thîi-nîi' },
        { id: 'go-here', en: 'please take me here', th: 'ไปที่นี่{P}', rom: 'pai thîi-nîi {P}',
          note: [{ en: 'Show the driver the address on your phone while you say it.' }] },
        { id: 'meter', en: 'please use the meter', th: 'เปิดมิเตอร์ด้วย{P}', rom: 'pòet mí-tôe dûai {P}',
          parts: [{ th: 'ด้วย', rom: 'dûai' }, { th: 'มิเตอร์ด้วย', rom: 'mí-tôe dûai' }] },
        { id: 'how-much-airport', en: 'how much to the airport?', th: 'ไปสนามบินเท่าไร{Pq}', rom: 'pai sa-nǎam-bin thâo-rài {Pq}' },
        { id: 'how-long', en: 'how long does it take?', th: 'นานเท่าไร{Pq}', rom: 'naan thâo-rài {Pq}' },
        { id: 'traffic', en: 'the traffic is bad', th: 'รถติด', rom: 'rót tìt' },
        { id: 'stop-there', en: 'stop over there, please', th: 'จอดตรงนั้น{P}', rom: 'jɔ̀ɔt trong nán {P}' },
        { id: 'u-turn', en: 'make a U-turn', th: 'กลับรถ', rom: 'klàp rót' },
        { id: 'drive-slowly', en: 'please drive slowly', th: 'ขับช้าๆ หน่อย{P}', rom: 'khàp cháa-cháa nɔ̀i {P}' },
        { id: 'arrived-q', en: 'are we there yet?', th: 'ถึงหรือยัง{Pq}', rom: 'thǔeng rǔue yang {Pq}' },
        { id: 'arrived', en: "we've arrived", th: 'ถึงแล้ว', rom: 'thǔeng lɛ́ɛo' },
        { id: 'keep-change', en: 'keep the change', th: 'ไม่ต้องทอน{P}', rom: 'mâi tɔ̂ng thɔɔn {P}' },
        { id: 'skytrain', en: 'the skytrain', th: 'รถไฟฟ้า', rom: 'rót-fai-fáa' },
        { id: 'station-where', en: 'where is the station?', th: 'สถานีอยู่ที่ไหน{Pq}', rom: 'sa-thǎa-nii yùu thîi-nǎi {Pq}' },
        { id: 'ticket', en: 'ticket', th: 'ตั๋ว', rom: 'tǔa' },
        { id: 'one-ticket', en: 'one ticket, please', th: 'ขอตั๋วหนึ่งใบ{P}', rom: 'khɔ̌ɔ tǔa nùeng bai {P}' },
      ],
    },
    {
      title: 'Unit 9 · At the hotel',
      items: [
        { id: 'room', en: 'room', th: 'ห้อง', rom: 'hɔ̂ng' },
        { id: 'room-free-q', en: 'do you have a room available?', th: 'มีห้องว่างไหม{Pq}', rom: 'mii hɔ̂ng wâang mǎi {Pq}',
          parts: [{ th: 'ว่างไหม', rom: 'wâang mǎi' }, { th: 'ห้องว่างไหม', rom: 'hɔ̂ng wâang mǎi' }] },
        { id: 'booked', en: 'I have a reservation', th: '{I}จองไว้แล้ว{P}', rom: '{I} jɔɔng wái lɛ́ɛo {P}',
          parts: [{ th: 'ไว้แล้ว', rom: 'wái lɛ́ɛo' }, { th: 'จองไว้แล้ว', rom: 'jɔɔng wái lɛ́ɛo' }] },
        { id: 'night', en: 'night', th: 'คืน', rom: 'khuen' },
        { id: 'two-nights', en: 'two nights', th: 'สองคืน', rom: 'sɔ̌ɔng khuen' },
        { id: 'checkout-time', en: 'what time is check-out?', th: 'เช็คเอาท์กี่โมง{Pq}', rom: 'chék-áo kìi moong {Pq}' },
        { id: 'breakfast', en: 'breakfast', th: 'อาหารเช้า', rom: 'aa-hǎan cháao' },
        { id: 'breakfast-time', en: 'what time is breakfast?', th: 'อาหารเช้ากี่โมง{Pq}', rom: 'aa-hǎan cháao kìi moong {Pq}' },
        { id: 'wifi-password', en: "what's the Wi-Fi password?", th: 'รหัสไวไฟคืออะไร{Pq}', rom: 'ra-hàt wai-fai khue a-rai {Pq}',
          parts: [{ th: 'คืออะไร', rom: 'khue a-rai' }] },
        { id: 'key', en: 'key', th: 'กุญแจ', rom: 'kun-jɛɛ' },
        { id: 'towel', en: 'towel', th: 'ผ้าเช็ดตัว', rom: 'phâa chét tua' },
        { id: 'aircon-broken', en: 'the air conditioner is broken', th: 'แอร์เสีย{P}', rom: 'ɛɛ sǐa {P}' },
        { id: 'no-hot-water', en: "there's no hot water", th: 'ไม่มีน้ำร้อน{P}', rom: 'mâi mii náam rɔ́ɔn {P}' },
        { id: 'leave-bags', en: 'can I leave my bags here?', th: 'ฝากกระเป๋าไว้ได้ไหม{Pq}', rom: 'fàak kra-pǎo wái dâi mǎi {Pq}',
          parts: [{ th: 'ไว้ได้ไหม', rom: 'wái dâi mǎi' }, { th: 'กระเป๋าไว้ได้ไหม', rom: 'kra-pǎo wái dâi mǎi' }] },
        { id: 'help-me-q', en: 'could you help me?', th: 'ช่วยหน่อยได้ไหม{Pq}', rom: 'chûai nɔ̀i dâi mǎi {Pq}' },
      ],
    },
    {
      title: 'Unit 10 · Ordering food',
      items: [
        { id: 'menu', en: 'the menu, please', th: 'ขอเมนูหน่อย{P}', rom: 'khɔ̌ɔ mee-nuu nɔ̀i {P}' },
        { id: 'order-this', en: "I'd like this one", th: 'เอาอันนี้{P}', rom: 'ao an-níi {P}' },
        { id: 'pad-thai', en: 'pad thai', th: 'ผัดไทย', rom: 'phàt thai' },
        { id: 'fried-rice', en: 'fried rice', th: 'ข้าวผัด', rom: 'khâao phàt' },
        { id: 'chicken', en: 'chicken', th: 'ไก่', rom: 'kài' },
        { id: 'pork', en: 'pork', th: 'หมู', rom: 'mǔu' },
        { id: 'shrimp', en: 'shrimp', th: 'กุ้ง', rom: 'kûng' },
        { id: 'chicken-fried-rice', en: 'chicken fried rice', th: 'ข้าวผัดไก่', rom: 'khâao phàt kài',
          note: [{ en: 'The main dish comes first, then what is in it.' }] },
        { id: 'a-little-spicy', en: 'a little spicy', th: 'เผ็ดนิดหน่อย', rom: 'phèt nít-nɔ̀i' },
        { id: 'no-chili', en: 'no chili, please', th: 'ไม่ใส่พริก{P}', rom: 'mâi sài phrík {P}',
          parts: [{ th: 'พริก', rom: 'phrík' }, { th: 'ใส่พริก', rom: 'sài phrík' }] },
        { id: 'no-meat', en: 'no meat, please', th: 'ไม่ใส่เนื้อสัตว์{P}', rom: 'mâi sài núea sàt {P}' },
        { id: 'ice', en: 'ice', th: 'น้ำแข็ง', rom: 'náam-khɛ̌ng' },
        { id: 'no-ice', en: 'no ice, please', th: 'ไม่ใส่น้ำแข็ง{P}', rom: 'mâi sài náam-khɛ̌ng {P}' },
        { id: 'iced-coffee', en: 'iced coffee', th: 'กาแฟเย็น', rom: 'kaa-fɛɛ yen' },
        { id: 'less-sweet', en: 'not too sweet', th: 'หวานน้อย', rom: 'wǎan nɔ́ɔi' },
        { id: 'beer', en: 'beer', th: 'เบียร์', rom: 'bia' },
        { id: 'another-water', en: 'another bottle of water, please', th: 'ขอน้ำอีกขวด{P}', rom: 'khɔ̌ɔ náam ìik khùat {P}',
          parts: [{ th: 'อีกขวด', rom: 'ìik khùat' }, { th: 'น้ำอีกขวด', rom: 'náam ìik khùat' }] },
        { id: 'take-away', en: 'to take away, please', th: 'เอากลับบ้าน{P}', rom: 'ao klàp bâan {P}',
          note: [{ en: 'Literally, take it back home.' }] },
        { id: 'full', en: "I'm full", th: 'อิ่มแล้ว', rom: 'ìm lɛ́ɛo' },
      ],
    },
    {
      title: 'Unit 11 · About you',
      items: [
        { id: 'from-where', en: 'where are you from?', th: 'คุณมาจากไหน{Pq}', rom: 'khun maa jàak nǎi {Pq}',
          parts: [{ th: 'ไหน', rom: 'nǎi' }, { th: 'จากไหน', rom: 'jàak nǎi' }, { th: 'มาจากไหน', rom: 'maa jàak nǎi' }] },
        { id: 'from-america', en: "I'm from America", th: '{I}มาจากอเมริกา{P}', rom: '{I} maa jàak a-mee-ri-kaa {P}' },
        { id: 'thai-lang', en: 'the Thai language', th: 'ภาษาไทย', rom: 'phaa-sǎa thai' },
        { id: 'speak-little', en: 'I can speak a little Thai', th: '{I}พูดภาษาไทยได้นิดหน่อย{P}', rom: '{I} phûut phaa-sǎa thai dâi nít-nɔ̀i {P}',
          parts: [{ th: 'นิดหน่อย', rom: 'nít-nɔ̀i' }, { th: 'ได้นิดหน่อย', rom: 'dâi nít-nɔ̀i' }, { th: 'ภาษาไทยได้นิดหน่อย', rom: 'phaa-sǎa thai dâi nít-nɔ̀i' }] },
        { id: 'speak-english', en: 'can you speak English?', th: 'พูดภาษาอังกฤษได้ไหม{Pq}', rom: 'phûut phaa-sǎa ang-krìt dâi mǎi {Pq}',
          parts: [{ th: 'ได้ไหม', rom: 'dâi mǎi' }, { th: 'ภาษาอังกฤษได้ไหม', rom: 'phaa-sǎa ang-krìt dâi mǎi' }] },
        { id: 'friend', en: 'friend', th: 'เพื่อน', rom: 'phûean' },
        { id: 'work', en: 'to work', th: 'ทำงาน', rom: 'tham-ngaan' },
        { id: 'thailand', en: 'Thailand', th: 'ประเทศไทย', rom: 'pra-thêet thai' },
        { id: 'like-thailand', en: 'I like Thailand', th: '{I}ชอบประเทศไทย{P}', rom: '{I} chɔ̂ɔp pra-thêet thai {P}' },
      ],
    },
    {
      title: 'Unit 12 · Time and feelings',
      items: [
        { id: 'today', en: 'today', th: 'วันนี้', rom: 'wan-níi' },
        { id: 'tomorrow', en: 'tomorrow', th: 'พรุ่งนี้', rom: 'phrûng-níi' },
        { id: 'yesterday', en: 'yesterday', th: 'เมื่อวาน', rom: 'mûea-waan' },
        { id: 'now', en: 'now', th: 'ตอนนี้', rom: 'tɔɔn-níi' },
        { id: 'what-time', en: 'what time is it?', th: 'กี่โมงแล้ว{Pq}', rom: 'kìi moong lɛ́ɛo {Pq}',
          parts: [{ th: 'โมงแล้ว', rom: 'moong lɛ́ɛo' }] },
        { id: 'wait-moment', en: 'wait a moment, please', th: 'รอสักครู่{P}', rom: 'rɔɔ sàk-khrûu {P}',
          parts: [{ th: 'สักครู่', rom: 'sàk-khrûu' }] },
        { id: 'see-tomorrow', en: 'see you tomorrow', th: 'เจอกันพรุ่งนี้{P}', rom: 'joe kan phrûng-níi {P}',
          parts: [{ th: 'พรุ่งนี้', rom: 'phrûng-níi' }, { th: 'กันพรุ่งนี้', rom: 'kan phrûng-níi' }] },
        { id: 'hungry', en: "I'm hungry", th: 'หิวข้าว', rom: 'hǐu khâao' },
        { id: 'tired', en: "I'm tired", th: 'เหนื่อย', rom: 'nùeai' },
        { id: 'hot', en: "it's hot", th: 'ร้อน', rom: 'rɔ́ɔn' },
        { id: 'very-hot', en: "it's very hot today", th: 'วันนี้ร้อนมาก', rom: 'wan-níi rɔ́ɔn mâak' },
        { id: 'happy', en: "I'm happy", th: 'ดีใจ', rom: 'dii-jai',
          note: [{ en: 'Many feelings use the word for heart. Good heart means happy.' }] },
      ],
    },
    {
      title: 'Unit 13 · Health and help',
      items: [
        { id: 'help', en: 'help!', th: 'ช่วยด้วย', rom: 'chûai dûai' },
        { id: 'sick', en: "I'm sick", th: 'ไม่สบาย{P}', rom: 'mâi sa-baai {P}' },
        { id: 'headache', en: 'I have a headache', th: 'ปวดหัว{P}', rom: 'pùat hǔa {P}' },
        { id: 'stomachache', en: 'I have a stomachache', th: 'ปวดท้อง{P}', rom: 'pùat thɔ́ɔng {P}' },
        { id: 'fever', en: 'I have a fever', th: 'เป็นไข้{P}', rom: 'pen khâi {P}' },
        { id: 'medicine', en: 'medicine', th: 'ยา', rom: 'yaa' },
        { id: 'pharmacy', en: 'pharmacy', th: 'ร้านขายยา', rom: 'ráan khǎai yaa',
          note: [{ en: 'Literally, shop that sells medicine.' }] },
        { id: 'pharmacy-where', en: 'where is a pharmacy?', th: 'ร้านขายยาอยู่ที่ไหน{Pq}', rom: 'ráan khǎai yaa yùu thîi-nǎi {Pq}' },
        { id: 'doctor', en: 'doctor', th: 'หมอ', rom: 'mɔ̌ɔ' },
        { id: 'hospital', en: 'hospital', th: 'โรงพยาบาล', rom: 'roong-pha-yaa-baan',
          parts: [{ th: 'พยาบาล', rom: 'pha-yaa-baan' }] },
        { id: 'go-hospital', en: 'please take me to the hospital', th: 'ไปโรงพยาบาล{P}', rom: 'pai roong-pha-yaa-baan {P}' },
        { id: 'allergic-peanuts', en: "I'm allergic to peanuts", th: '{I}แพ้ถั่ว{P}', rom: '{I} phɛ́ɛ thùa {P}',
          note: [{ en: 'Swap the last word for what you are allergic to. Allergic is:' }, { th: 'แพ้' }] },
        { id: 'police', en: 'police', th: 'ตำรวจ', rom: 'tam-rùat' },
        { id: 'call-police', en: 'please call the police', th: 'ช่วยเรียกตำรวจ{P}', rom: 'chûai rîak tam-rùat {P}' },
        { id: 'lost-phone', en: 'I lost my phone', th: 'โทรศัพท์หาย{P}', rom: 'thoo-ra-sàp hǎai {P}' },
        { id: 'lost-way', en: "I'm lost", th: '{I}หลงทาง{P}', rom: '{I} lǒng thaang {P}' },
        { id: 'dangerous-q', en: 'is it dangerous?', th: 'อันตรายไหม{Pq}', rom: 'an-ta-raai mǎi {Pq}' },
      ],
    },
    {
      title: 'Unit 14 · Small talk',
      items: [
        { id: 'holiday', en: "I'm here on holiday", th: 'มาเที่ยว{P}', rom: 'maa thîao {P}' },
        { id: 'first-time', en: 'this is my first time in Thailand', th: 'มาเมืองไทยครั้งแรก{P}', rom: 'maa mueang thai khráng rɛ̂ɛk {P}',
          parts: [{ th: 'ครั้งแรก', rom: 'khráng rɛ̂ɛk' }, { th: 'เมืองไทยครั้งแรก', rom: 'mueang thai khráng rɛ̂ɛk' }] },
        { id: 'two-weeks', en: "I'm staying two weeks", th: 'อยู่สองอาทิตย์{P}', rom: 'yùu sɔ̌ɔng aa-thít {P}' },
        { id: 'beautiful', en: 'beautiful', th: 'สวย', rom: 'sǔai' },
        { id: 'very-beautiful', en: 'very beautiful', th: 'สวยมาก', rom: 'sǔai mâak' },
        { id: 'fun', en: "it's a lot of fun", th: 'สนุกมาก', rom: 'sa-nùk mâak' },
        { id: 'like-a-lot', en: 'I like it a lot', th: 'ชอบมาก', rom: 'chɔ̂ɔp mâak' },
        { id: 'raining', en: "it's raining", th: 'ฝนตก', rom: 'fǒn tòk' },
        { id: 'where-visit', en: 'where should I go sightseeing?', th: 'ควรไปเที่ยวที่ไหน{Pq}', rom: 'khuan pai thîao thîi-nǎi {Pq}',
          parts: [{ th: 'เที่ยวที่ไหน', rom: 'thîao thîi-nǎi' }, { th: 'ไปเที่ยวที่ไหน', rom: 'pai thîao thîi-nǎi' }] },
        { id: 'what-is-this', en: 'what is this?', th: 'นี่อะไร{Pq}', rom: 'nîi a-rai {Pq}' },
        { id: 'called-in-thai', en: 'what is this called in Thai?', th: 'ภาษาไทยเรียกว่าอะไร{Pq}', rom: 'phaa-sǎa thai rîak wâa a-rai {Pq}',
          parts: [{ th: 'ว่าอะไร', rom: 'wâa a-rai' }, { th: 'เรียกว่าอะไร', rom: 'rîak wâa a-rai' }] },
        { id: 'say-again', en: 'can you say that again?', th: 'พูดอีกทีได้ไหม{Pq}', rom: 'phûut ìik thii dâi mǎi {Pq}' },
        { id: 'speak-well', en: 'you speak Thai well', th: 'พูดไทยเก่ง', rom: 'phûut thai kèng',
          note: [{ en: 'Thais often say this kindly to learners. A modest answer is next.' }] },
        { id: 'not-good-yet', en: "not really, I'm not good yet", th: 'ยังไม่เก่ง{P}', rom: 'yang mâi kèng {P}' },
        { id: 'photo-q', en: 'can I take a photo?', th: 'ถ่ายรูปได้ไหม{Pq}', rom: 'thàai rûup dâi mǎi {Pq}' },
        { id: 'good-luck', en: 'good luck', th: 'โชคดี{P}', rom: 'chôok dii {P}' },
        { id: 'see-again', en: 'see you again', th: 'แล้วเจอกันใหม่{P}', rom: 'lɛ́ɛo joe kan mài {P}',
          parts: [{ th: 'กันใหม่', rom: 'kan mài' }, { th: 'เจอกันใหม่', rom: 'joe kan mài' }] },
      ],
    },
  ],
};
