// Course content for the audio app.
//
// Each item is one thing the learner learns to SAY.
//   en    – what the English narrator asks for ("How do you say: <en>?")
//   th    – Thai text sent to the Thai voice (never shown unless "peek" is on)
//   rom   – romanization, shown only with "peek" on
//   parts – optional back-chaining steps, played end-first before the whole phrase
//   note  – optional narration after the introduction: segments of {en} or {th}
//
// Placeholders, filled in from the learner's settings:
//   {P}  polite ending for statements  (ครับ khráp / ค่ะ khâ)
//   {Pq} polite ending for questions   (ครับ khráp / คะ khá)
//   {I}  "I"                            (ผม phǒm / ฉัน chǎn)

window.COURSE = {
  units: [
    {
      title: 'Unit 1 · Greetings',
      items: [
        { id: 'hello', en: 'hello', th: 'สวัสดี', rom: 'sa-wàt-dii',
          parts: [{ th: 'ดี', rom: 'dii' }, { th: 'หวัดดี', rom: 'wàt-dii' }],
          note: [{ en: 'Thais use the same word for hello and goodbye.' }] },
        { id: 'particle', en: 'the polite ending word', th: '{P}', rom: '{P}',
          note: [{ en: 'Thais add a polite word to the end of most sentences. It depends on whether the speaker is a man or a woman. For you, it is:' }, { th: '{P}' }] },
        { id: 'hello-polite', en: 'hello, politely', th: 'สวัสดี{P}', rom: 'sa-wàt-dii {P}' },
        { id: 'thanks', en: 'thank you', th: 'ขอบคุณ', rom: 'khɔ̀ɔp-khun',
          parts: [{ th: 'คุณ', rom: 'khun' }] },
        { id: 'thanks-polite', en: 'thank you, politely', th: 'ขอบคุณ{P}', rom: 'khɔ̀ɔp-khun {P}' },
        { id: 'fine', en: "I'm fine", th: 'สบายดี', rom: 'sa-baai-dii',
          parts: [{ th: 'ดี', rom: 'dii' }, { th: 'บายดี', rom: 'baai-dii' }] },
        { id: 'how-are-you', en: 'how are you?', th: 'สบายดีไหม{Pq}', rom: 'sa-baai-dii mǎi {Pq}',
          parts: [{ th: 'ไหม', rom: 'mǎi' }, { th: 'ดีไหม', rom: 'dii mǎi' }],
          note: [{ en: 'The little word at the end turns a sentence into a yes or no question.' }, { th: 'ไหม' }] },
        { id: 'sorry', en: 'sorry, or excuse me', th: 'ขอโทษ{P}', rom: 'khɔ̌ɔ-thôot {P}',
          parts: [{ th: 'โทษ', rom: 'thôot' }] },
        { id: 'no-problem', en: 'no problem, or never mind', th: 'ไม่เป็นไร', rom: 'mâi pen rai',
          parts: [{ th: 'ไร', rom: 'rai' }, { th: 'เป็นไร', rom: 'pen rai' }] },
      ],
    },
    {
      title: 'Unit 2 · Getting by',
      items: [
        { id: 'yes', en: "yes, that's right", th: 'ใช่', rom: 'châi' },
        { id: 'not-right', en: "no, that's not right", th: 'ไม่ใช่', rom: 'mâi châi',
          note: [{ en: 'Putting this word in front makes anything negative.' }, { th: 'ไม่' }] },
        { id: 'understand', en: 'I understand', th: 'เข้าใจ{P}', rom: 'khâo-jai {P}',
          parts: [{ th: 'ใจ', rom: 'jai' }] },
        { id: 'not-understand', en: "I don't understand", th: 'ไม่เข้าใจ{P}', rom: 'mâi khâo-jai {P}' },
        { id: 'slowly', en: 'please speak slowly', th: 'พูดช้าๆ หน่อย{P}', rom: 'phûut cháa-cháa nɔ̀i {P}',
          parts: [{ th: 'หน่อย', rom: 'nɔ̀i' }, { th: 'ช้าๆ หน่อย', rom: 'cháa-cháa nɔ̀i' }] },
        { id: 'how-say-thai', en: 'how do you say it in Thai?', th: 'ภาษาไทยพูดว่ายังไง{Pq}', rom: 'phaa-sǎa thai phûut wâa yang-ngai {Pq}',
          parts: [{ th: 'ยังไง', rom: 'yang-ngai' }, { th: 'ว่ายังไง', rom: 'wâa yang-ngai' }, { th: 'พูดว่ายังไง', rom: 'phûut wâa yang-ngai' }],
          note: [{ en: 'Point at the thing, or say the English word first, then ask. You will use this every day.' }] },
        { id: 'pronoun-i', en: 'I, or me', th: '{I}', rom: '{I}',
          note: [{ en: 'Like the polite ending, the word for I depends on the speaker. For you, it is:' }, { th: '{I}' }] },
        { id: 'name-q', en: "what's your name?", th: 'คุณชื่ออะไร{Pq}', rom: 'khun chûue a-rai {Pq}',
          parts: [{ th: 'อะไร', rom: 'a-rai' }, { th: 'ชื่ออะไร', rom: 'chûue a-rai' }] },
        { id: 'nice-to-meet', en: 'nice to meet you', th: 'ยินดีที่ได้รู้จัก{P}', rom: 'yin-dii thîi dâi rúu-jàk {P}',
          parts: [{ th: 'รู้จัก', rom: 'rúu-jàk' }, { th: 'ได้รู้จัก', rom: 'dâi rúu-jàk' }, { th: 'ที่ได้รู้จัก', rom: 'thîi dâi rúu-jàk' }] },
      ],
    },
    {
      title: 'Unit 3 · Food and shopping',
      items: [
        { id: 'water', en: 'water', th: 'น้ำ', rom: 'náam' },
        { id: 'plain-water', en: 'plain drinking water', th: 'น้ำเปล่า', rom: 'náam plàao' },
        { id: 'may-i-have', en: 'may I have', th: 'ขอ', rom: 'khɔ̌ɔ' },
        { id: 'water-please', en: 'may I have plain water, please?', th: 'ขอน้ำเปล่า{P}', rom: 'khɔ̌ɔ náam plàao {P}' },
        { id: 'delicious', en: 'delicious', th: 'อร่อย', rom: 'a-rɔ̀i' },
        { id: 'very-delicious', en: 'very delicious', th: 'อร่อยมาก', rom: 'a-rɔ̀i mâak' },
        { id: 'not-spicy', en: 'not spicy', th: 'ไม่เผ็ด', rom: 'mâi phèt' },
        { id: 'how-much', en: 'how much?', th: 'เท่าไร{Pq}', rom: 'thâo-rài {Pq}' },
        { id: 'this-one', en: 'this one', th: 'อันนี้', rom: 'an níi' },
        { id: 'this-how-much', en: 'how much is this one?', th: 'อันนี้เท่าไร{Pq}', rom: 'an níi thâo-rài {Pq}' },
        { id: 'too-expensive', en: 'too expensive', th: 'แพงไป', rom: 'phɛɛng pai' },
        { id: 'bill', en: 'the bill, please', th: 'เช็คบิลด้วย{P}', rom: 'chék bin dûai {P}' },
        { id: 'toilet', en: 'the toilet', th: 'ห้องน้ำ', rom: 'hɔ̂ng-náam' },
        { id: 'where-toilet', en: 'where is the toilet?', th: 'ห้องน้ำอยู่ที่ไหน{Pq}', rom: 'hɔ̂ng-náam yùu thîi-nǎi {Pq}',
          parts: [{ th: 'ที่ไหน', rom: 'thîi-nǎi' }, { th: 'อยู่ที่ไหน', rom: 'yùu thîi-nǎi' }] },
      ],
    },
    {
      title: 'Unit 4 · Numbers',
      items: [
        { id: 'n1', en: 'one', th: 'หนึ่ง', rom: 'nùeng' },
        { id: 'n2', en: 'two', th: 'สอง', rom: 'sɔ̌ɔng' },
        { id: 'n3', en: 'three', th: 'สาม', rom: 'sǎam' },
        { id: 'n4', en: 'four', th: 'สี่', rom: 'sìi' },
        { id: 'n5', en: 'five', th: 'ห้า', rom: 'hâa' },
        { id: 'n6', en: 'six', th: 'หก', rom: 'hòk' },
        { id: 'n7', en: 'seven', th: 'เจ็ด', rom: 'jèt' },
        { id: 'n8', en: 'eight', th: 'แปด', rom: 'pɛ̀ɛt' },
        { id: 'n9', en: 'nine', th: 'เก้า', rom: 'kâao' },
        { id: 'n10', en: 'ten', th: 'สิบ', rom: 'sìp' },
        { id: 'n20', en: 'twenty', th: 'ยี่สิบ', rom: 'yîi-sìp',
          note: [{ en: 'Twenty is irregular. It is not two-ten.' }] },
        { id: 'n100', en: 'one hundred', th: 'หนึ่งร้อย', rom: 'nùeng rɔ́ɔi' },
        { id: 'baht-100', en: 'one hundred baht', th: 'หนึ่งร้อยบาท', rom: 'nùeng rɔ́ɔi bàat' },
      ],
    },
    {
      title: 'Unit 5 · Money and bargaining',
      items: [
        { id: 'n50', en: 'fifty', th: 'ห้าสิบ', rom: 'hâa-sìp' },
        { id: 'n200', en: 'two hundred', th: 'สองร้อย', rom: 'sɔ̌ɔng rɔ́ɔi' },
        { id: 'n500', en: 'five hundred', th: 'ห้าร้อย', rom: 'hâa rɔ́ɔi' },
        { id: 'n1000', en: 'one thousand', th: 'หนึ่งพัน', rom: 'nùeng phan' },
        { id: 'n1500', en: 'one thousand five hundred', th: 'หนึ่งพันห้าร้อย', rom: 'nùeng phan hâa rɔ́ɔi',
          parts: [{ th: 'ห้าร้อย', rom: 'hâa rɔ́ɔi' }] },
        { id: 'how-many-baht', en: 'how many baht?', th: 'กี่บาท{Pq}', rom: 'kìi bàat {Pq}' },
        { id: 'very-expensive', en: 'very expensive', th: 'แพงมาก', rom: 'phɛɛng mâak' },
        { id: 'cheap', en: 'cheap', th: 'ถูก', rom: 'thùuk' },
        { id: 'cheaper-q', en: 'do you have a cheaper one?', th: 'มีถูกกว่านี้ไหม{Pq}', rom: 'mii thùuk kwàa níi mǎi {Pq}',
          parts: [{ th: 'กว่านี้ไหม', rom: 'kwàa níi mǎi' }, { th: 'ถูกกว่านี้ไหม', rom: 'thùuk kwàa níi mǎi' }] },
        { id: 'discount-q', en: 'can you lower the price a bit?', th: 'ลดหน่อยได้ไหม{Pq}', rom: 'lót nɔ̀i dâi mǎi {Pq}',
          parts: [{ th: 'ได้ไหม', rom: 'dâi mǎi' }, { th: 'หน่อยได้ไหม', rom: 'nɔ̀i dâi mǎi' }],
          note: [{ en: 'Bargaining is normal at markets. Smile and keep it friendly.' }] },
        { id: 'take-it', en: "I'll take it", th: 'เอา{P}', rom: 'ao {P}' },
        { id: 'agreed', en: 'OK, deal', th: 'ตกลง{P}', rom: 'tòk-long {P}' },
        { id: 'dont-want', en: "I don't want it, thanks", th: 'ไม่เอา{P}', rom: 'mâi ao {P}' },
        { id: 'just-looking', en: "I'm just looking", th: 'ดูเฉยๆ{P}', rom: 'duu chǒei-chǒei {P}' },
        { id: 'pay-card', en: 'can I pay by card?', th: 'จ่ายด้วยบัตรได้ไหม{Pq}', rom: 'jàai dûai bàt dâi mǎi {Pq}',
          parts: [{ th: 'บัตรได้ไหม', rom: 'bàt dâi mǎi' }, { th: 'ด้วยบัตรได้ไหม', rom: 'dûai bàt dâi mǎi' }] },
        { id: 'cash', en: 'cash', th: 'เงินสด', rom: 'ngoen-sòt' },
        { id: 'change-money', en: 'the change, money back', th: 'เงินทอน', rom: 'ngoen-thɔɔn' },
        { id: 'atm-where', en: 'where is the ATM?', th: 'ตู้เอทีเอ็มอยู่ที่ไหน{Pq}', rom: 'tûu ee-thii-em yùu thîi-nǎi {Pq}',
          parts: [{ th: 'อยู่ที่ไหน', rom: 'yùu thîi-nǎi' }] },
      ],
    },
    {
      title: 'Unit 6 · Want, have, can',
      items: [
        { id: 'want-to', en: 'I want to', th: 'อยาก', rom: 'yàak' },
        { id: 'go', en: 'to go', th: 'ไป', rom: 'pai' },
        { id: 'want-go', en: 'I want to go', th: 'อยากไป', rom: 'yàak pai',
          note: [{ en: 'Thai often leaves out the word for I when it is obvious.' }] },
        { id: 'eat', en: 'to eat', th: 'กิน', rom: 'kin' },
        { id: 'eat-meal', en: 'to eat a meal', th: 'กินข้าว', rom: 'kin khâao',
          note: [{ en: 'Literally, eat rice. Rice is the meal in Thailand.' }] },
        { id: 'eaten-yet', en: 'have you eaten yet?', th: 'กินข้าวหรือยัง{Pq}', rom: 'kin khâao rǔue yang {Pq}',
          parts: [{ th: 'ยัง', rom: 'yang' }, { th: 'หรือยัง', rom: 'rǔue yang' }],
          note: [{ en: 'Thais often ask this as a friendly greeting, like how are you.' }] },
        { id: 'eaten-already', en: "I've eaten already", th: 'กินแล้ว{P}', rom: 'kin lɛ́ɛo {P}',
          parts: [{ th: 'แล้ว', rom: 'lɛ́ɛo' }] },
        { id: 'have', en: 'to have, or there is', th: 'มี', rom: 'mii' },
        { id: 'have-water', en: 'do you have water?', th: 'มีน้ำไหม{Pq}', rom: 'mii náam mǎi {Pq}' },
        { id: 'dont-have', en: "I don't have any, or there isn't any", th: 'ไม่มี', rom: 'mâi mii' },
        { id: 'can', en: 'can, or able to', th: 'ได้', rom: 'dâi' },
        { id: 'can-q', en: 'is that OK? Can I?', th: 'ได้ไหม{Pq}', rom: 'dâi mǎi {Pq}' },
        { id: 'cannot', en: "can't, or not possible", th: 'ไม่ได้', rom: 'mâi dâi' },
        { id: 'like', en: 'to like', th: 'ชอบ', rom: 'chɔ̂ɔp' },
        { id: 'like-thai-food', en: 'I like Thai food', th: '{I}ชอบอาหารไทย{P}', rom: '{I} chɔ̂ɔp aa-hǎan thai {P}',
          parts: [{ th: 'ไทย', rom: 'thai' }, { th: 'อาหารไทย', rom: 'aa-hǎan thai' }] },
      ],
    },
    {
      title: 'Unit 7 · Getting around',
      items: [
        { id: 'going-where', en: 'where are you going?', th: 'ไปไหน{Pq}', rom: 'pai nǎi {Pq}',
          note: [{ en: 'Another everyday greeting. A vague answer is fine.' }] },
        { id: 'hotel', en: 'hotel', th: 'โรงแรม', rom: 'roong-rɛɛm' },
        { id: 'want-hotel', en: 'I want to go to the hotel', th: 'อยากไปโรงแรม{P}', rom: 'yàak pai roong-rɛɛm {P}' },
        { id: 'airport', en: 'the airport', th: 'สนามบิน', rom: 'sa-nǎam-bin',
          parts: [{ th: 'บิน', rom: 'bin' }] },
        { id: 'go-airport', en: 'go to the airport', th: 'ไปสนามบิน', rom: 'pai sa-nǎam-bin' },
        { id: 'turn-left', en: 'turn left', th: 'เลี้ยวซ้าย', rom: 'líao sáai' },
        { id: 'turn-right', en: 'turn right', th: 'เลี้ยวขวา', rom: 'líao khwǎa' },
        { id: 'straight', en: 'go straight ahead', th: 'ตรงไป', rom: 'trong pai' },
        { id: 'stop-here', en: 'stop here, please', th: 'จอดตรงนี้{P}', rom: 'jɔ̀ɔt trong níi {P}',
          parts: [{ th: 'ตรงนี้', rom: 'trong níi' }] },
        { id: 'near', en: 'near', th: 'ใกล้', rom: 'klâi' },
        { id: 'far', en: 'far', th: 'ไกล', rom: 'klai',
          note: [{ en: 'Near and far differ only in tone. Listen to both.' }, { th: 'ใกล้' }, { th: 'ไกล' }] },
        { id: 'far-q', en: 'is it far?', th: 'ไกลไหม{Pq}', rom: 'klai mǎi {Pq}' },
      ],
    },
    {
      title: 'Unit 8 · Taxis and transport',
      items: [
        { id: 'taxi', en: 'taxi', th: 'แท็กซี่', rom: 'thɛ́k-sîi' },
        { id: 'car', en: 'car', th: 'รถ', rom: 'rót' },
        { id: 'here', en: 'here, this place', th: 'ที่นี่', rom: 'thîi-nîi' },
        { id: 'go-here', en: 'please take me here', th: 'ไปที่นี่{P}', rom: 'pai thîi-nîi {P}',
          note: [{ en: 'Show the driver the address on your phone while you say it.' }] },
        { id: 'meter', en: 'please use the meter', th: 'เปิดมิเตอร์ด้วย{P}', rom: 'pòet mí-tôe dûai {P}',
          parts: [{ th: 'ด้วย', rom: 'dûai' }, { th: 'มิเตอร์ด้วย', rom: 'mí-tôe dûai' }] },
        { id: 'how-much-airport', en: 'how much to the airport?', th: 'ไปสนามบินเท่าไร{Pq}', rom: 'pai sa-nǎam-bin thâo-rài {Pq}' },
        { id: 'how-long', en: 'how long does it take?', th: 'นานเท่าไร{Pq}', rom: 'naan thâo-rài {Pq}' },
        { id: 'traffic', en: 'the traffic is bad', th: 'รถติด', rom: 'rót tìt' },
        { id: 'stop-there', en: 'stop over there, please', th: 'จอดตรงนั้น{P}', rom: 'jɔ̀ɔt trong nán {P}' },
        { id: 'u-turn', en: 'make a U-turn', th: 'กลับรถ', rom: 'klàp rót' },
        { id: 'drive-slowly', en: 'please drive slowly', th: 'ขับช้าๆ หน่อย{P}', rom: 'khàp cháa-cháa nɔ̀i {P}' },
        { id: 'arrived-q', en: 'are we there yet?', th: 'ถึงหรือยัง{Pq}', rom: 'thǔeng rǔue yang {Pq}' },
        { id: 'arrived', en: "we've arrived", th: 'ถึงแล้ว', rom: 'thǔeng lɛ́ɛo' },
        { id: 'keep-change', en: 'keep the change', th: 'ไม่ต้องทอน{P}', rom: 'mâi tɔ̂ng thɔɔn {P}' },
        { id: 'skytrain', en: 'the skytrain', th: 'รถไฟฟ้า', rom: 'rót-fai-fáa' },
        { id: 'station-where', en: 'where is the station?', th: 'สถานีอยู่ที่ไหน{Pq}', rom: 'sa-thǎa-nii yùu thîi-nǎi {Pq}' },
        { id: 'ticket', en: 'ticket', th: 'ตั๋ว', rom: 'tǔa' },
        { id: 'one-ticket', en: 'one ticket, please', th: 'ขอตั๋วหนึ่งใบ{P}', rom: 'khɔ̌ɔ tǔa nùeng bai {P}' },
      ],
    },
    {
      title: 'Unit 9 · At the hotel',
      items: [
        { id: 'room', en: 'room', th: 'ห้อง', rom: 'hɔ̂ng' },
        { id: 'room-free-q', en: 'do you have a room available?', th: 'มีห้องว่างไหม{Pq}', rom: 'mii hɔ̂ng wâang mǎi {Pq}',
          parts: [{ th: 'ว่างไหม', rom: 'wâang mǎi' }, { th: 'ห้องว่างไหม', rom: 'hɔ̂ng wâang mǎi' }] },
        { id: 'booked', en: 'I have a reservation', th: '{I}จองไว้แล้ว{P}', rom: '{I} jɔɔng wái lɛ́ɛo {P}',
          parts: [{ th: 'ไว้แล้ว', rom: 'wái lɛ́ɛo' }, { th: 'จองไว้แล้ว', rom: 'jɔɔng wái lɛ́ɛo' }] },
        { id: 'night', en: 'night', th: 'คืน', rom: 'khuen' },
        { id: 'two-nights', en: 'two nights', th: 'สองคืน', rom: 'sɔ̌ɔng khuen' },
        { id: 'checkout-time', en: 'what time is check-out?', th: 'เช็คเอาท์กี่โมง{Pq}', rom: 'chék-áo kìi moong {Pq}' },
        { id: 'breakfast', en: 'breakfast', th: 'อาหารเช้า', rom: 'aa-hǎan cháao' },
        { id: 'breakfast-time', en: 'what time is breakfast?', th: 'อาหารเช้ากี่โมง{Pq}', rom: 'aa-hǎan cháao kìi moong {Pq}' },
        { id: 'wifi-password', en: "what's the Wi-Fi password?", th: 'รหัสไวไฟคืออะไร{Pq}', rom: 'ra-hàt wai-fai khue a-rai {Pq}',
          parts: [{ th: 'คืออะไร', rom: 'khue a-rai' }] },
        { id: 'key', en: 'key', th: 'กุญแจ', rom: 'kun-jɛɛ' },
        { id: 'towel', en: 'towel', th: 'ผ้าเช็ดตัว', rom: 'phâa chét tua' },
        { id: 'aircon-broken', en: 'the air conditioner is broken', th: 'แอร์เสีย{P}', rom: 'ɛɛ sǐa {P}' },
        { id: 'no-hot-water', en: "there's no hot water", th: 'ไม่มีน้ำร้อน{P}', rom: 'mâi mii náam rɔ́ɔn {P}' },
        { id: 'leave-bags', en: 'can I leave my bags here?', th: 'ฝากกระเป๋าไว้ได้ไหม{Pq}', rom: 'fàak kra-pǎo wái dâi mǎi {Pq}',
          parts: [{ th: 'ไว้ได้ไหม', rom: 'wái dâi mǎi' }, { th: 'กระเป๋าไว้ได้ไหม', rom: 'kra-pǎo wái dâi mǎi' }] },
        { id: 'help-me-q', en: 'could you help me?', th: 'ช่วยหน่อยได้ไหม{Pq}', rom: 'chûai nɔ̀i dâi mǎi {Pq}' },
      ],
    },
    {
      title: 'Unit 10 · Ordering food',
      items: [
        { id: 'menu', en: 'the menu, please', th: 'ขอเมนูหน่อย{P}', rom: 'khɔ̌ɔ mee-nuu nɔ̀i {P}' },
        { id: 'order-this', en: "I'd like this one", th: 'เอาอันนี้{P}', rom: 'ao an-níi {P}' },
        { id: 'pad-thai', en: 'pad thai', th: 'ผัดไทย', rom: 'phàt thai' },
        { id: 'fried-rice', en: 'fried rice', th: 'ข้าวผัด', rom: 'khâao phàt' },
        { id: 'chicken', en: 'chicken', th: 'ไก่', rom: 'kài' },
        { id: 'pork', en: 'pork', th: 'หมู', rom: 'mǔu' },
        { id: 'shrimp', en: 'shrimp', th: 'กุ้ง', rom: 'kûng' },
        { id: 'chicken-fried-rice', en: 'chicken fried rice', th: 'ข้าวผัดไก่', rom: 'khâao phàt kài',
          note: [{ en: 'The main dish comes first, then what is in it.' }] },
        { id: 'a-little-spicy', en: 'a little spicy', th: 'เผ็ดนิดหน่อย', rom: 'phèt nít-nɔ̀i' },
        { id: 'no-chili', en: 'no chili, please', th: 'ไม่ใส่พริก{P}', rom: 'mâi sài phrík {P}',
          parts: [{ th: 'พริก', rom: 'phrík' }, { th: 'ใส่พริก', rom: 'sài phrík' }] },
        { id: 'no-meat', en: 'no meat, please', th: 'ไม่ใส่เนื้อสัตว์{P}', rom: 'mâi sài núea sàt {P}' },
        { id: 'ice', en: 'ice', th: 'น้ำแข็ง', rom: 'náam-khɛ̌ng' },
        { id: 'no-ice', en: 'no ice, please', th: 'ไม่ใส่น้ำแข็ง{P}', rom: 'mâi sài náam-khɛ̌ng {P}' },
        { id: 'iced-coffee', en: 'iced coffee', th: 'กาแฟเย็น', rom: 'kaa-fɛɛ yen' },
        { id: 'less-sweet', en: 'not too sweet', th: 'หวานน้อย', rom: 'wǎan nɔ́ɔi' },
        { id: 'beer', en: 'beer', th: 'เบียร์', rom: 'bia' },
        { id: 'another-water', en: 'another bottle of water, please', th: 'ขอน้ำอีกขวด{P}', rom: 'khɔ̌ɔ náam ìik khùat {P}',
          parts: [{ th: 'อีกขวด', rom: 'ìik khùat' }, { th: 'น้ำอีกขวด', rom: 'náam ìik khùat' }] },
        { id: 'take-away', en: 'to take away, please', th: 'เอากลับบ้าน{P}', rom: 'ao klàp bâan {P}',
          note: [{ en: 'Literally, take it back home.' }] },
        { id: 'full', en: "I'm full", th: 'อิ่มแล้ว', rom: 'ìm lɛ́ɛo' },
      ],
    },
    {
      title: 'Unit 11 · About you',
      items: [
        { id: 'from-where', en: 'where are you from?', th: 'คุณมาจากไหน{Pq}', rom: 'khun maa jàak nǎi {Pq}',
          parts: [{ th: 'ไหน', rom: 'nǎi' }, { th: 'จากไหน', rom: 'jàak nǎi' }, { th: 'มาจากไหน', rom: 'maa jàak nǎi' }] },
        { id: 'from-america', en: "I'm from America", th: '{I}มาจากอเมริกา{P}', rom: '{I} maa jàak a-mee-ri-kaa {P}' },
        { id: 'thai-lang', en: 'the Thai language', th: 'ภาษาไทย', rom: 'phaa-sǎa thai' },
        { id: 'speak-little', en: 'I can speak a little Thai', th: '{I}พูดภาษาไทยได้นิดหน่อย{P}', rom: '{I} phûut phaa-sǎa thai dâi nít-nɔ̀i {P}',
          parts: [{ th: 'นิดหน่อย', rom: 'nít-nɔ̀i' }, { th: 'ได้นิดหน่อย', rom: 'dâi nít-nɔ̀i' }, { th: 'ภาษาไทยได้นิดหน่อย', rom: 'phaa-sǎa thai dâi nít-nɔ̀i' }] },
        { id: 'speak-english', en: 'can you speak English?', th: 'พูดภาษาอังกฤษได้ไหม{Pq}', rom: 'phûut phaa-sǎa ang-krìt dâi mǎi {Pq}',
          parts: [{ th: 'ได้ไหม', rom: 'dâi mǎi' }, { th: 'ภาษาอังกฤษได้ไหม', rom: 'phaa-sǎa ang-krìt dâi mǎi' }] },
        { id: 'friend', en: 'friend', th: 'เพื่อน', rom: 'phûean' },
        { id: 'work', en: 'to work', th: 'ทำงาน', rom: 'tham-ngaan' },
        { id: 'thailand', en: 'Thailand', th: 'ประเทศไทย', rom: 'pra-thêet thai' },
        { id: 'like-thailand', en: 'I like Thailand', th: '{I}ชอบประเทศไทย{P}', rom: '{I} chɔ̂ɔp pra-thêet thai {P}' },
      ],
    },
    {
      title: 'Unit 12 · Time and feelings',
      items: [
        { id: 'today', en: 'today', th: 'วันนี้', rom: 'wan-níi' },
        { id: 'tomorrow', en: 'tomorrow', th: 'พรุ่งนี้', rom: 'phrûng-níi' },
        { id: 'yesterday', en: 'yesterday', th: 'เมื่อวาน', rom: 'mûea-waan' },
        { id: 'now', en: 'now', th: 'ตอนนี้', rom: 'tɔɔn-níi' },
        { id: 'what-time', en: 'what time is it?', th: 'กี่โมงแล้ว{Pq}', rom: 'kìi moong lɛ́ɛo {Pq}',
          parts: [{ th: 'โมงแล้ว', rom: 'moong lɛ́ɛo' }] },
        { id: 'wait-moment', en: 'wait a moment, please', th: 'รอสักครู่{P}', rom: 'rɔɔ sàk-khrûu {P}',
          parts: [{ th: 'สักครู่', rom: 'sàk-khrûu' }] },
        { id: 'see-tomorrow', en: 'see you tomorrow', th: 'เจอกันพรุ่งนี้{P}', rom: 'joe kan phrûng-níi {P}',
          parts: [{ th: 'พรุ่งนี้', rom: 'phrûng-níi' }, { th: 'กันพรุ่งนี้', rom: 'kan phrûng-níi' }] },
        { id: 'hungry', en: "I'm hungry", th: 'หิวข้าว', rom: 'hǐu khâao' },
        { id: 'tired', en: "I'm tired", th: 'เหนื่อย', rom: 'nùeai' },
        { id: 'hot', en: "it's hot", th: 'ร้อน', rom: 'rɔ́ɔn' },
        { id: 'very-hot', en: "it's very hot today", th: 'วันนี้ร้อนมาก', rom: 'wan-níi rɔ́ɔn mâak' },
        { id: 'happy', en: "I'm happy", th: 'ดีใจ', rom: 'dii-jai',
          note: [{ en: 'Many feelings use the word for heart. Good heart means happy.' }] },
      ],
    },
    {
      title: 'Unit 13 · Health and help',
      items: [
        { id: 'help', en: 'help!', th: 'ช่วยด้วย', rom: 'chûai dûai' },
        { id: 'sick', en: "I'm sick", th: 'ไม่สบาย{P}', rom: 'mâi sa-baai {P}' },
        { id: 'headache', en: 'I have a headache', th: 'ปวดหัว{P}', rom: 'pùat hǔa {P}' },
        { id: 'stomachache', en: 'I have a stomachache', th: 'ปวดท้อง{P}', rom: 'pùat thɔ́ɔng {P}' },
        { id: 'fever', en: 'I have a fever', th: 'เป็นไข้{P}', rom: 'pen khâi {P}' },
        { id: 'medicine', en: 'medicine', th: 'ยา', rom: 'yaa' },
        { id: 'pharmacy', en: 'pharmacy', th: 'ร้านขายยา', rom: 'ráan khǎai yaa',
          note: [{ en: 'Literally, shop that sells medicine.' }] },
        { id: 'pharmacy-where', en: 'where is a pharmacy?', th: 'ร้านขายยาอยู่ที่ไหน{Pq}', rom: 'ráan khǎai yaa yùu thîi-nǎi {Pq}' },
        { id: 'doctor', en: 'doctor', th: 'หมอ', rom: 'mɔ̌ɔ' },
        { id: 'hospital', en: 'hospital', th: 'โรงพยาบาล', rom: 'roong-pha-yaa-baan',
          parts: [{ th: 'พยาบาล', rom: 'pha-yaa-baan' }] },
        { id: 'go-hospital', en: 'please take me to the hospital', th: 'ไปโรงพยาบาล{P}', rom: 'pai roong-pha-yaa-baan {P}' },
        { id: 'allergic-peanuts', en: "I'm allergic to peanuts", th: '{I}แพ้ถั่ว{P}', rom: '{I} phɛ́ɛ thùa {P}',
          note: [{ en: 'Swap the last word for what you are allergic to. Allergic is:' }, { th: 'แพ้' }] },
        { id: 'police', en: 'police', th: 'ตำรวจ', rom: 'tam-rùat' },
        { id: 'call-police', en: 'please call the police', th: 'ช่วยเรียกตำรวจ{P}', rom: 'chûai rîak tam-rùat {P}' },
        { id: 'lost-phone', en: 'I lost my phone', th: 'โทรศัพท์หาย{P}', rom: 'thoo-ra-sàp hǎai {P}' },
        { id: 'lost-way', en: "I'm lost", th: '{I}หลงทาง{P}', rom: '{I} lǒng thaang {P}' },
        { id: 'dangerous-q', en: 'is it dangerous?', th: 'อันตรายไหม{Pq}', rom: 'an-ta-raai mǎi {Pq}' },
      ],
    },
    {
      title: 'Unit 14 · Small talk',
      items: [
        { id: 'holiday', en: "I'm here on holiday", th: 'มาเที่ยว{P}', rom: 'maa thîao {P}' },
        { id: 'first-time', en: 'this is my first time in Thailand', th: 'มาเมืองไทยครั้งแรก{P}', rom: 'maa mueang thai khráng rɛ̂ɛk {P}',
          parts: [{ th: 'ครั้งแรก', rom: 'khráng rɛ̂ɛk' }, { th: 'เมืองไทยครั้งแรก', rom: 'mueang thai khráng rɛ̂ɛk' }] },
        { id: 'two-weeks', en: "I'm staying two weeks", th: 'อยู่สองอาทิตย์{P}', rom: 'yùu sɔ̌ɔng aa-thít {P}' },
        { id: 'beautiful', en: 'beautiful', th: 'สวย', rom: 'sǔai' },
        { id: 'very-beautiful', en: 'very beautiful', th: 'สวยมาก', rom: 'sǔai mâak' },
        { id: 'fun', en: "it's a lot of fun", th: 'สนุกมาก', rom: 'sa-nùk mâak' },
        { id: 'like-a-lot', en: 'I like it a lot', th: 'ชอบมาก', rom: 'chɔ̂ɔp mâak' },
        { id: 'raining', en: "it's raining", th: 'ฝนตก', rom: 'fǒn tòk' },
        { id: 'where-visit', en: 'where should I go sightseeing?', th: 'ควรไปเที่ยวที่ไหน{Pq}', rom: 'khuan pai thîao thîi-nǎi {Pq}',
          parts: [{ th: 'เที่ยวที่ไหน', rom: 'thîao thîi-nǎi' }, { th: 'ไปเที่ยวที่ไหน', rom: 'pai thîao thîi-nǎi' }] },
        { id: 'what-is-this', en: 'what is this?', th: 'นี่อะไร{Pq}', rom: 'nîi a-rai {Pq}' },
        { id: 'called-in-thai', en: 'what is this called in Thai?', th: 'ภาษาไทยเรียกว่าอะไร{Pq}', rom: 'phaa-sǎa thai rîak wâa a-rai {Pq}',
          parts: [{ th: 'ว่าอะไร', rom: 'wâa a-rai' }, { th: 'เรียกว่าอะไร', rom: 'rîak wâa a-rai' }] },
        { id: 'say-again', en: 'can you say that again?', th: 'พูดอีกทีได้ไหม{Pq}', rom: 'phûut ìik thii dâi mǎi {Pq}' },
        { id: 'speak-well', en: 'you speak Thai well', th: 'พูดไทยเก่ง', rom: 'phûut thai kèng',
          note: [{ en: 'Thais often say this kindly to learners. A modest answer is next.' }] },
        { id: 'not-good-yet', en: "not really, I'm not good yet", th: 'ยังไม่เก่ง{P}', rom: 'yang mâi kèng {P}' },
        { id: 'photo-q', en: 'can I take a photo?', th: 'ถ่ายรูปได้ไหม{Pq}', rom: 'thàai rûup dâi mǎi {Pq}' },
        { id: 'good-luck', en: 'good luck', th: 'โชคดี{P}', rom: 'chôok dii {P}' },
        { id: 'see-again', en: 'see you again', th: 'แล้วเจอกันใหม่{P}', rom: 'lɛ́ɛo joe kan mài {P}',
          parts: [{ th: 'กันใหม่', rom: 'kan mài' }, { th: 'เจอกันใหม่', rom: 'joe kan mài' }] },
      ],
    },
    {
      title: 'Unit 15 · Question words',
      items: [
        { id: 'q-who', en: 'who?', th: 'ใคร', rom: 'khrai' },
        { id: 'q-what', en: 'what?', th: 'อะไร', rom: 'a-rai' },
        { id: 'q-where', en: 'where?', th: 'ที่ไหน', rom: 'thîi-nǎi' },
        { id: 'q-when', en: 'when?', th: 'เมื่อไร', rom: 'mûea-rài' },
        { id: 'q-why', en: 'why?', th: 'ทำไม', rom: 'tham-mai' },
        { id: 'q-how', en: 'how?', th: 'ยังไง', rom: 'yang-ngai',
          note: [{ en: 'This is the everyday spoken form. You will hear it constantly.' }] },
        { id: 'q-which', en: 'which one?', th: 'อันไหน', rom: 'an nǎi' },
        { id: 'q-how-many-people', en: 'how many people?', th: 'กี่คน', rom: 'kìi khon' },
        { id: 'q-who-is-that', en: 'who is that?', th: 'นั่นใคร', rom: 'nân khrai' },
        { id: 'q-doing', en: 'what are you doing?', th: 'ทำอะไรอยู่', rom: 'tham a-rai yùu' },
        { id: 'q-when-go', en: 'when are you going?', th: 'จะไปเมื่อไร', rom: 'jà pai mûea-rài' },
        { id: 'q-how-get-there', en: 'how do I get there?', th: 'ไปยังไง{Pq}', rom: 'pai yang-ngai {Pq}' },
        { id: 'q-meaning', en: 'what does it mean?', th: 'แปลว่าอะไร{Pq}', rom: 'plɛɛ wâa a-rai {Pq}',
          parts: [{ th: 'ว่าอะไร', rom: 'wâa a-rai' }] },
      ],
    },
    {
      title: 'Unit 16 · Everyday verbs',
      items: [
        { id: 'v-come', en: 'to come', th: 'มา', rom: 'maa' },
        { id: 'v-buy', en: 'to buy', th: 'ซื้อ', rom: 'súue' },
        { id: 'v-sell', en: 'to sell', th: 'ขาย', rom: 'khǎai' },
        { id: 'v-sleep', en: 'to sleep', th: 'นอน', rom: 'nɔɔn' },
        { id: 'v-drink', en: 'to drink', th: 'ดื่ม', rom: 'dùuem' },
        { id: 'v-walk', en: 'to walk', th: 'เดิน', rom: 'doen' },
        { id: 'v-look', en: 'to look, to watch', th: 'ดู', rom: 'duu' },
        { id: 'v-wait', en: 'to wait', th: 'รอ', rom: 'rɔɔ' },
        { id: 'v-know', en: 'I know', th: 'รู้', rom: 'rúu' },
        { id: 'v-dont-know', en: "I don't know", th: 'ไม่รู้', rom: 'mâi rúu' },
        { id: 'v-think', en: 'to think', th: 'คิด', rom: 'khít' },
        { id: 'v-want-buy', en: 'I want to buy this one', th: 'อยากซื้ออันนี้{P}', rom: 'yàak súue an-níi {P}' },
        { id: 'v-wait-for-me', en: 'wait for me, please', th: 'รอ{I}ด้วย{P}', rom: 'rɔɔ {I} dûai {P}' },
        { id: 'v-understand-q', en: 'do you understand?', th: 'เข้าใจไหม{Pq}', rom: 'khâo-jai mǎi {Pq}' },
      ],
    },
    {
      title: 'Unit 17 · Days and times',
      items: [
        { id: 'd-mon', en: 'Monday', th: 'วันจันทร์', rom: 'wan jan' },
        { id: 'd-tue', en: 'Tuesday', th: 'วันอังคาร', rom: 'wan ang-khaan' },
        { id: 'd-wed', en: 'Wednesday', th: 'วันพุธ', rom: 'wan phút' },
        { id: 'd-thu', en: 'Thursday', th: 'วันพฤหัส', rom: 'wan pha-rúe-hàt' },
        { id: 'd-fri', en: 'Friday', th: 'วันศุกร์', rom: 'wan sùk' },
        { id: 'd-sat', en: 'Saturday', th: 'วันเสาร์', rom: 'wan sǎo' },
        { id: 'd-sun', en: 'Sunday', th: 'วันอาทิตย์', rom: 'wan aa-thít' },
        { id: 'd-what-day', en: 'what day is it today?', th: 'วันนี้วันอะไร{Pq}', rom: 'wan-níi wan a-rai {Pq}' },
        { id: 'd-morning', en: 'in the morning', th: 'ตอนเช้า', rom: 'tɔɔn cháao' },
        { id: 'd-evening', en: 'in the evening', th: 'ตอนเย็น', rom: 'tɔɔn yen' },
        { id: 'd-night', en: 'at night', th: 'ตอนกลางคืน', rom: 'tɔɔn klaang-khuen' },
        { id: 'd-week', en: 'week', th: 'อาทิตย์', rom: 'aa-thít',
          note: [{ en: 'Same word as in Sunday. Context tells you which.' }] },
        { id: 'd-next-week', en: 'next week', th: 'อาทิตย์หน้า', rom: 'aa-thít nâa' },
        { id: 'd-later', en: 'later', th: 'ทีหลัง', rom: 'thii-lǎng' },
      ],
    },
    {
      title: 'Unit 18 · Places and directions',
      items: [
        { id: 'p-market', en: 'market', th: 'ตลาด', rom: 'ta-làat' },
        { id: 'p-night-market', en: 'night market', th: 'ตลาดกลางคืน', rom: 'ta-làat klaang-khuen' },
        { id: 'p-restaurant', en: 'restaurant', th: 'ร้านอาหาร', rom: 'ráan aa-hǎan' },
        { id: 'p-bank', en: 'bank', th: 'ธนาคาร', rom: 'tha-naa-khaan' },
        { id: 'p-temple', en: 'temple', th: 'วัด', rom: 'wát' },
        { id: 'p-beach', en: 'beach', th: 'ชายหาด', rom: 'chaai-hàat' },
        { id: 'p-mall', en: 'shopping mall', th: 'ห้าง', rom: 'hâang' },
        { id: 'p-map', en: 'map', th: 'แผนที่', rom: 'phɛ̌ɛn-thîi' },
        { id: 'p-seven-q', en: 'is there a 7-Eleven around here?', th: 'แถวนี้มีเซเว่นไหม{Pq}', rom: 'thɛ̌o níi mii see-wên mǎi {Pq}',
          parts: [{ th: 'เซเว่นไหม', rom: 'see-wên mǎi' }, { th: 'มีเซเว่นไหม', rom: 'mii see-wên mǎi' }] },
        { id: 'p-walk-q', en: 'can I walk there?', th: 'เดินไปได้ไหม{Pq}', rom: 'doen pai dâi mǎi {Pq}' },
        { id: 'p-on-left', en: "it's on the left", th: 'อยู่ทางซ้าย', rom: 'yùu thaang sáai' },
        { id: 'p-on-right', en: "it's on the right", th: 'อยู่ทางขวา', rom: 'yùu thaang khwǎa' },
        { id: 'p-straight-left', en: 'go straight, then turn left', th: 'ตรงไปแล้วเลี้ยวซ้าย', rom: 'trong pai lɛ́ɛo líao sáai',
          parts: [{ th: 'เลี้ยวซ้าย', rom: 'líao sáai' }, { th: 'แล้วเลี้ยวซ้าย', rom: 'lɛ́ɛo líao sáai' }] },
      ],
    },
    {
      title: 'Unit 19 · Street food',
      items: [
        { id: 'f-som-tam', en: 'papaya salad', th: 'ส้มตำ', rom: 'sôm-tam' },
        { id: 'f-sticky-rice', en: 'sticky rice', th: 'ข้าวเหนียว', rom: 'khâao-nǐao' },
        { id: 'f-grilled-chicken', en: 'grilled chicken', th: 'ไก่ย่าง', rom: 'kài-yâang' },
        { id: 'f-mango-sticky', en: 'mango sticky rice', th: 'ข้าวเหนียวมะม่วง', rom: 'khâao-nǐao ma-mûang' },
        { id: 'f-noodle-soup', en: 'noodle soup', th: 'ก๋วยเตี๋ยว', rom: 'kǔai-tǐao' },
        { id: 'f-pork-skewers', en: 'grilled pork skewers', th: 'หมูปิ้ง', rom: 'mǔu-pîng' },
        { id: 'f-basil-pork', en: 'stir-fried basil pork', th: 'ผัดกะเพราหมู', rom: 'phàt ka-phrao mǔu' },
        { id: 'f-fried-egg', en: 'fried egg', th: 'ไข่ดาว', rom: 'khài-daao' },
        { id: 'f-add-egg', en: 'with a fried egg, please', th: 'ใส่ไข่ดาว{P}', rom: 'sài khài-daao {P}' },
        { id: 'f-coconut', en: 'coconut', th: 'มะพร้าว', rom: 'ma-phráao' },
        { id: 'f-orange-juice', en: 'fresh orange juice', th: 'น้ำส้มคั้น', rom: 'náam-sôm khán' },
        { id: 'f-one-serving', en: 'one serving, please', th: 'เอาหนึ่งที่{P}', rom: 'ao nùeng thîi {P}' },
        { id: 'f-whats-good', en: "what's good here?", th: 'ที่นี่อะไรอร่อย{Pq}', rom: 'thîi-nîi a-rai a-rɔ̀i {Pq}' },
        { id: 'f-same-as-that', en: 'the same as that one', th: 'เหมือนอันนั้น', rom: 'mǔean an-nán' },
      ],
    },
    {
      title: 'Unit 20 · Clothes, colors and sizes',
      items: [
        { id: 'c-shirt', en: 'shirt', th: 'เสื้อ', rom: 'sûea' },
        { id: 'c-pants', en: 'pants', th: 'กางเกง', rom: 'kaang-keeng' },
        { id: 'c-shoes', en: 'shoes', th: 'รองเท้า', rom: 'rɔɔng-tháao' },
        { id: 'c-big', en: 'big', th: 'ใหญ่', rom: 'yài' },
        { id: 'c-small', en: 'small', th: 'เล็ก', rom: 'lék' },
        { id: 'c-too-small', en: 'too small', th: 'เล็กไป', rom: 'lék pai' },
        { id: 'c-too-big', en: 'too big', th: 'ใหญ่ไป', rom: 'yài pai' },
        { id: 'c-bigger-q', en: 'do you have a bigger one?', th: 'มีใหญ่กว่านี้ไหม{Pq}', rom: 'mii yài kwàa níi mǎi {Pq}' },
        { id: 'c-try-q', en: 'can I try it on?', th: 'ลองได้ไหม{Pq}', rom: 'lɔɔng dâi mǎi {Pq}' },
        { id: 'c-color', en: 'color', th: 'สี', rom: 'sǐi' },
        { id: 'c-red', en: 'red', th: 'สีแดง', rom: 'sǐi dɛɛng' },
        { id: 'c-white', en: 'white', th: 'สีขาว', rom: 'sǐi khǎao' },
        { id: 'c-black', en: 'black', th: 'สีดำ', rom: 'sǐi dam' },
        { id: 'c-blue', en: 'blue', th: 'สีฟ้า', rom: 'sǐi fáa' },
        { id: 'c-other-color-q', en: 'do you have other colors?', th: 'มีสีอื่นไหม{Pq}', rom: 'mii sǐi ùuen mǎi {Pq}' },
      ],
    },
    {
      title: 'Unit 21 · Massage and spa',
      items: [
        { id: 'm-massage', en: 'massage', th: 'นวด', rom: 'nûat' },
        { id: 'm-thai', en: 'Thai massage', th: 'นวดไทย', rom: 'nûat thai' },
        { id: 'm-foot', en: 'foot massage', th: 'นวดเท้า', rom: 'nûat tháao' },
        { id: 'm-oil', en: 'oil massage', th: 'นวดน้ำมัน', rom: 'nûat náam-man' },
        { id: 'm-one-hour', en: 'one hour', th: 'หนึ่งชั่วโมง', rom: 'nùeng chûa-moong' },
        { id: 'm-two-hours', en: 'two hours', th: 'สองชั่วโมง', rom: 'sɔ̌ɔng chûa-moong' },
        { id: 'm-per-hour-q', en: 'how much per hour?', th: 'ชั่วโมงละเท่าไร{Pq}', rom: 'chûa-moong lá thâo-rài {Pq}' },
        { id: 'm-harder', en: 'harder, please', th: 'แรงๆ หน่อย{P}', rom: 'rɛɛng-rɛɛng nɔ̀i {P}' },
        { id: 'm-softer', en: 'softer, please', th: 'เบาๆ หน่อย{P}', rom: 'bao-bao nɔ̀i {P}' },
        { id: 'm-hurts', en: 'it hurts', th: 'เจ็บ', rom: 'jèp' },
        { id: 'm-feels-good', en: 'that feels really good', th: 'สบายมาก', rom: 'sa-baai mâak' },
        { id: 'm-shoulders', en: 'shoulders', th: 'ไหล่', rom: 'lài' },
        { id: 'm-back', en: 'back (of the body)', th: 'หลัง', rom: 'lǎng' },
        { id: 'm-not-there', en: "please don't massage there", th: 'ไม่ต้องนวดตรงนั้น{P}', rom: 'mâi tɔ̂ng nûat trong nán {P}' },
      ],
    },
    {
      title: 'Unit 22 · Beaches and islands',
      items: [
        { id: 'b-island', en: 'island', th: 'เกาะ', rom: 'kɔ̀' },
        { id: 'b-sea', en: 'the sea', th: 'ทะเล', rom: 'tha-lee' },
        { id: 'b-boat', en: 'boat', th: 'เรือ', rom: 'ruea' },
        { id: 'b-boat-ticket', en: 'boat ticket', th: 'ตั๋วเรือ', rom: 'tǔa ruea' },
        { id: 'b-boat-time-q', en: 'what time does the boat leave?', th: 'เรือออกกี่โมง{Pq}', rom: 'ruea ɔ̀ɔk kìi moong {Pq}' },
        { id: 'b-swim', en: 'to swim', th: 'ว่ายน้ำ', rom: 'wâai-náam' },
        { id: 'b-swim-q', en: 'can I swim here?', th: 'ว่ายน้ำที่นี่ได้ไหม{Pq}', rom: 'wâai-náam thîi-nîi dâi mǎi {Pq}' },
        { id: 'b-snorkel', en: 'snorkeling, diving', th: 'ดำน้ำ', rom: 'dam-náam' },
        { id: 'b-life-jacket', en: 'life jacket', th: 'เสื้อชูชีพ', rom: 'sûea chuu-chîip' },
        { id: 'b-sunscreen', en: 'sunscreen', th: 'ครีมกันแดด', rom: 'khriim kan-dɛ̀ɛt' },
        { id: 'b-strong-sun', en: 'the sun is strong', th: 'แดดแรง', rom: 'dɛ̀ɛt rɛɛng' },
        { id: 'b-big-waves', en: 'the waves are big', th: 'คลื่นใหญ่', rom: 'khlûen yài' },
        { id: 'b-rent-bike', en: 'rent a motorbike', th: 'เช่ามอเตอร์ไซค์', rom: 'châo mɔɔ-toe-sai' },
        { id: 'b-per-day-q', en: 'how much per day?', th: 'วันละเท่าไร{Pq}', rom: 'wan lá thâo-rài {Pq}' },
      ],
    },
    {
      title: 'Unit 23 · Temples and culture',
      items: [
        { id: 't-monk', en: 'monk', th: 'พระ', rom: 'phrá' },
        { id: 't-buddha', en: 'Buddha image', th: 'พระพุทธรูป', rom: 'phrá-phút-tha-rûup' },
        { id: 't-beautiful-temple', en: 'this temple is very beautiful', th: 'วัดนี้สวยมาก', rom: 'wát níi sǔai mâak' },
        { id: 't-shoes-off-q', en: 'do I need to take off my shoes?', th: 'ต้องถอดรองเท้าไหม{Pq}', rom: 'tɔ̂ng thɔ̀ɔt rɔɔng-tháao mǎi {Pq}',
          parts: [{ th: 'รองเท้าไหม', rom: 'rɔɔng-tháao mǎi' }, { th: 'ถอดรองเท้าไหม', rom: 'thɔ̀ɔt rɔɔng-tháao mǎi' }] },
        { id: 't-come-in-q', en: 'may I go in?', th: 'เข้าไปได้ไหม{Pq}', rom: 'khâo pai dâi mǎi {Pq}' },
        { id: 't-outfit-q', en: 'is this outfit OK?', th: 'แต่งตัวแบบนี้ได้ไหม{Pq}', rom: 'tɛ̀ng-tua bɛ̀ɛp níi dâi mǎi {Pq}' },
        { id: 't-wai', en: 'the Thai greeting with hands together', th: 'ไหว้', rom: 'wâi' },
        { id: 't-pray', en: 'to pay respect to the Buddha', th: 'ไหว้พระ', rom: 'wâi phrá' },
        { id: 't-merit', en: 'to make merit', th: 'ทำบุญ', rom: 'tham-bun' },
        { id: 't-festival', en: 'festival', th: 'เทศกาล', rom: 'thêet-sa-kaan' },
        { id: 't-songkran', en: 'Songkran, Thai New Year', th: 'สงกรานต์', rom: 'sǒng-kraan' },
        { id: 't-loy-krathong', en: 'Loy Krathong, the floating lantern festival', th: 'ลอยกระทง', rom: 'loi kra-thong' },
        { id: 't-polite', en: 'polite', th: 'สุภาพ', rom: 'sù-phâap' },
      ],
    },
    {
      title: 'Unit 24 · Phone and internet',
      items: [
        { id: 'i-sim', en: 'SIM card', th: 'ซิมการ์ด', rom: 'sim-káat' },
        { id: 'i-buy-sim', en: 'I want to buy a SIM card', th: 'อยากซื้อซิมการ์ด{P}', rom: 'yàak súue sim-káat {P}' },
        { id: 'i-top-up', en: 'to top up credit', th: 'เติมเงิน', rom: 'toem ngoen' },
        { id: 'i-wifi-q', en: 'is there Wi-Fi?', th: 'มีไวไฟไหม{Pq}', rom: 'mii wai-fai mǎi {Pq}' },
        { id: 'i-slow', en: 'the internet is slow', th: 'เน็ตช้า', rom: 'nét cháa' },
        { id: 'i-battery-dead', en: 'my battery is dead', th: 'แบตหมด', rom: 'bɛ̀t mòt' },
        { id: 'i-charger', en: 'charger', th: 'ที่ชาร์จ', rom: 'thîi cháat' },
        { id: 'i-charge-q', en: 'can I charge my phone?', th: 'ชาร์จโทรศัพท์ได้ไหม{Pq}', rom: 'cháat thoo-ra-sàp dâi mǎi {Pq}' },
        { id: 'i-phone-number', en: 'phone number', th: 'เบอร์โทร', rom: 'boe thoo' },
        { id: 'i-number-q', en: "what's your phone number?", th: 'เบอร์โทรอะไร{Pq}', rom: 'boe thoo a-rai {Pq}' },
        { id: 'i-call-me', en: 'call me', th: 'โทรหา{I}{P}', rom: 'thoo hǎa {I} {P}' },
        { id: 'i-line-q', en: 'can I have your LINE?', th: 'ขอไลน์หน่อยได้ไหม{Pq}', rom: 'khɔ̌ɔ lai nɔ̀i dâi mǎi {Pq}',
          note: [{ en: 'LINE is the messaging app almost everyone in Thailand uses.' }] },
      ],
    },
    {
      title: 'Unit 25 · Making friends',
      items: [
        { id: 'r-where-live-q', en: 'where do you live?', th: 'อยู่ที่ไหน{Pq}', rom: 'yùu thîi-nǎi {Pq}' },
        { id: 'r-live-america', en: 'I live in America', th: '{I}อยู่อเมริกา{P}', rom: '{I} yùu a-mee-ri-kaa {P}' },
        { id: 'r-job-q', en: 'what do you do for work?', th: 'ทำงานอะไร{Pq}', rom: 'tham-ngaan a-rai {Pq}' },
        { id: 'r-age-q', en: 'how old are you?', th: 'อายุเท่าไร{Pq}', rom: 'aa-yú thâo-rài {Pq}' },
        { id: 'r-married-q', en: 'are you married?', th: 'แต่งงานหรือยัง{Pq}', rom: 'tɛ̀ng-ngaan rǔue yang {Pq}',
          note: [{ en: 'Thais often ask personal questions early. It is friendly, not rude.' }] },
        { id: 'r-married', en: "I'm married", th: 'แต่งงานแล้ว{P}', rom: 'tɛ̀ng-ngaan lɛ́ɛo {P}' },
        { id: 'r-single', en: "I'm single", th: 'ยังโสด{P}', rom: 'yang sòot {P}' },
        { id: 'r-children', en: 'I have children', th: 'มีลูก{P}', rom: 'mii lûuk {P}' },
        { id: 'r-my-friend', en: 'this is my friend', th: 'นี่เพื่อน{I}{P}', rom: 'nîi phûean {I} {P}' },
        { id: 'r-eat-together-q', en: 'shall we go eat together?', th: 'ไปกินข้าวด้วยกันไหม{Pq}', rom: 'pai kin khâao dûai kan mǎi {Pq}',
          parts: [{ th: 'ด้วยกันไหม', rom: 'dûai kan mǎi' }, { th: 'กินข้าวด้วยกันไหม', rom: 'kin khâao dûai kan mǎi' }] },
        { id: 'r-kind', en: "you're very kind", th: 'ใจดีมาก', rom: 'jai-dii mâak' },
        { id: 'r-miss-you', en: 'I miss you', th: 'คิดถึง', rom: 'khít-thǔeng' },
        { id: 'r-keep-touch', en: "let's keep in touch", th: 'ติดต่อกันนะ', rom: 'tìt-tɔ̀ɔ kan ná' },
      ],
    },
    {
      title: 'Unit 26 · Reactions',
      items: [
        { id: 'x-really-q', en: 'really?', th: 'จริงเหรอ', rom: 'jing rǒe' },
        { id: 'x-truly', en: 'truly, really', th: 'จริงๆ', rom: 'jing-jing' },
        { id: 'x-oh-i-see', en: 'oh, I see', th: 'อ๋อ', rom: 'ɔ̌ɔ' },
        { id: 'x-ok', en: 'OK', th: 'โอเค', rom: 'oo-khee' },
        { id: 'x-sure', en: 'sure, no problem', th: 'ได้เลย', rom: 'dâi loei' },
        { id: 'x-maybe', en: 'maybe', th: 'อาจจะ', rom: 'àat jà' },
        { id: 'x-not-sure', en: "I'm not sure", th: 'ไม่แน่ใจ', rom: 'mâi nɛ̂ɛ-jai' },
        { id: 'x-hang-on', en: 'hang on a second', th: 'แป๊บนึง', rom: 'pɛ́p nueng' },
        { id: 'x-no-thanks', en: 'no, thank you', th: 'ไม่เป็นไร ขอบคุณ{P}', rom: 'mâi pen rai, khɔ̀ɔp-khun {P}' },
        { id: 'x-pity', en: "what a pity, that's too bad", th: 'น่าเสียดาย', rom: 'nâa sǐa-daai' },
        { id: 'x-congrats', en: 'congratulations', th: 'ยินดีด้วย', rom: 'yin-dii dûai' },
        { id: 'x-excited', en: "I'm excited", th: 'ตื่นเต้น', rom: 'tùuen-tên' },
        { id: 'x-sleepy', en: "I'm sleepy", th: 'ง่วงนอน', rom: 'ngûang nɔɔn' },
        { id: 'x-cute', en: 'cute', th: 'น่ารัก', rom: 'nâa-rák' },
      ],
    },
    {
      title: 'Unit 27 · Family',
      items: [
        { id: 'fam-family', en: 'family', th: 'ครอบครัว', rom: 'khrɔ̂ɔp-khrua' },
        { id: 'fam-father', en: 'father', th: 'พ่อ', rom: 'phɔ̂ɔ' },
        { id: 'fam-mother', en: 'mother', th: 'แม่', rom: 'mɛ̂ɛ' },
        { id: 'fam-older', en: 'older brother or sister', th: 'พี่', rom: 'phîi',
          note: [{ en: 'Thais also call anyone a little older than them this. It is friendly and polite.' }] },
        { id: 'fam-younger', en: 'younger brother or sister', th: 'น้อง', rom: 'nɔ́ɔng',
          note: [{ en: 'And this is for anyone a little younger, like a waiter or a shop assistant.' }] },
        { id: 'fam-husband', en: 'husband', th: 'สามี', rom: 'sǎa-mii' },
        { id: 'fam-wife', en: 'wife', th: 'ภรรยา', rom: 'phan-ra-yaa' },
        { id: 'fam-child', en: 'child, or children', th: 'ลูก', rom: 'lûuk' },
        { id: 'fam-son', en: 'son', th: 'ลูกชาย', rom: 'lûuk-chaai' },
        { id: 'fam-daughter', en: 'daughter', th: 'ลูกสาว', rom: 'lûuk-sǎao' },
        { id: 'fam-grandma', en: 'grandmother', th: 'ยาย', rom: 'yaai' },
        { id: 'fam-siblings-q', en: 'how many brothers and sisters do you have?', th: 'มีพี่น้องกี่คน{Pq}', rom: 'mii phîi-nɔ́ɔng kìi khon {Pq}',
          parts: [{ th: 'กี่คน', rom: 'kìi khon' }, { th: 'พี่น้องกี่คน', rom: 'phîi-nɔ́ɔng kìi khon' }] },
        { id: 'fam-two-children', en: 'I have two children', th: 'มีลูกสองคน{P}', rom: 'mii lûuk sɔ̌ɔng khon {P}',
          parts: [{ th: 'สองคน', rom: 'sɔ̌ɔng khon' }, { th: 'ลูกสองคน', rom: 'lûuk sɔ̌ɔng khon' }] },
        { id: 'fam-this-is', en: 'this is my family', th: 'นี่ครอบครัว{I}{P}', rom: 'nîi khrɔ̂ɔp-khrua {I} {P}' },
        { id: 'fam-mother-thai', en: 'my mother is Thai', th: 'แม่{I}เป็นคนไทย{P}', rom: 'mɛ̂ɛ {I} pen khon thai {P}',
          parts: [{ th: 'คนไทย', rom: 'khon thai' }, { th: 'เป็นคนไทย', rom: 'pen khon thai' }] },
      ],
    },
    {
      title: 'Unit 28 · Telling the time',
      items: [
        { id: 'time-7am', en: 'seven in the morning', th: 'เจ็ดโมงเช้า', rom: 'jèt moong cháao',
          note: [{ en: 'Thai splits the day into blocks. Morning hours use this word for o\'clock, plus morning:' }, { th: 'โมงเช้า' }] },
        { id: 'time-9am', en: 'nine in the morning', th: 'เก้าโมงเช้า', rom: 'kâao moong cháao' },
        { id: 'time-noon', en: 'noon', th: 'เที่ยง', rom: 'thîang' },
        { id: 'time-1pm', en: 'one in the afternoon', th: 'บ่ายโมง', rom: 'bàai moong' },
        { id: 'time-3pm', en: 'three in the afternoon', th: 'บ่ายสามโมง', rom: 'bàai sǎam moong' },
        { id: 'time-5pm', en: 'five in the evening', th: 'ห้าโมงเย็น', rom: 'hâa moong yen' },
        { id: 'time-7pm', en: 'seven in the evening', th: 'หนึ่งทุ่ม', rom: 'nùeng thûm',
          note: [{ en: 'From seven at night, Thais count again from one, with this word:' }, { th: 'ทุ่ม' }] },
        { id: 'time-9pm', en: 'nine at night', th: 'สามทุ่ม', rom: 'sǎam thûm' },
        { id: 'time-midnight', en: 'midnight', th: 'เที่ยงคืน', rom: 'thîang-khuen' },
        { id: 'time-half', en: 'half past three in the afternoon', th: 'บ่ายสามโมงครึ่ง', rom: 'bàai sǎam moong khrûeng',
          parts: [{ th: 'ครึ่ง', rom: 'khrûeng' }, { th: 'โมงครึ่ง', rom: 'moong khrûeng' }] },
        { id: 'time-minute', en: 'minute', th: 'นาที', rom: 'naa-thii' },
        { id: 'time-open-q', en: 'what time do you open?', th: 'เปิดกี่โมง{Pq}', rom: 'pòet kìi moong {Pq}' },
        { id: 'time-close-q', en: 'what time do you close?', th: 'ปิดกี่โมง{Pq}', rom: 'pìt kìi moong {Pq}' },
        { id: 'time-meet-7pm', en: "let's meet at seven in the evening", th: 'เจอกันหนึ่งทุ่ม{P}', rom: 'joe kan nùeng thûm {P}' },
        { id: 'time-now-q', en: 'what time is it now?', th: 'ตอนนี้กี่โมงแล้ว{Pq}', rom: 'tɔɔn-níi kìi moong lɛ́ɛo {Pq}' },
      ],
    },
    {
      title: 'Unit 29 · Airport and immigration',
      items: [
        { id: 'air-passport', en: 'passport', th: 'พาสปอร์ต', rom: 'pháat-sa-pɔ̀ɔt' },
        { id: 'air-visa', en: 'visa', th: 'วีซ่า', rom: 'wii-sâa' },
        { id: 'air-flight', en: 'flight', th: 'เที่ยวบิน', rom: 'thîao-bin' },
        { id: 'air-gate-q', en: 'which gate?', th: 'ประตูไหน{Pq}', rom: 'pra-tuu nǎi {Pq}' },
        { id: 'air-boarding-pass', en: 'boarding pass', th: 'บัตรขึ้นเครื่อง', rom: 'bàt khûen khrûeang',
          parts: [{ th: 'เครื่อง', rom: 'khrûeang' }, { th: 'ขึ้นเครื่อง', rom: 'khûen khrûeang' }] },
        { id: 'air-luggage', en: 'suitcase, luggage', th: 'กระเป๋าเดินทาง', rom: 'kra-pǎo doen-thaang' },
        { id: 'air-lost-bag', en: 'my luggage is lost', th: 'กระเป๋าหาย{P}', rom: 'kra-pǎo hǎai {P}' },
        { id: 'air-window-seat', en: 'a window seat, please', th: 'ขอที่นั่งริมหน้าต่าง{P}', rom: 'khɔ̌ɔ thîi-nâng rim nâa-tàang {P}',
          parts: [{ th: 'หน้าต่าง', rom: 'nâa-tàang' }, { th: 'ริมหน้าต่าง', rom: 'rim nâa-tàang' }, { th: 'ที่นั่งริมหน้าต่าง', rom: 'thîi-nâng rim nâa-tàang' }] },
        { id: 'air-delayed', en: 'the flight is delayed', th: 'เที่ยวบินล่าช้า', rom: 'thîao-bin lâa-cháa' },
        { id: 'air-customs', en: 'customs', th: 'ศุลกากร', rom: 'sǔn-la-kaa-kɔɔn' },
        { id: 'air-declare', en: 'nothing to declare', th: 'ไม่มีอะไรต้องสำแดง{P}', rom: 'mâi mii a-rai tɔ̂ng sǎm-dɛɛng {P}',
          parts: [{ th: 'สำแดง', rom: 'sǎm-dɛɛng' }, { th: 'ต้องสำแดง', rom: 'tɔ̂ng sǎm-dɛɛng' }, { th: 'อะไรต้องสำแดง', rom: 'a-rai tɔ̂ng sǎm-dɛɛng' }] },
        { id: 'air-stay-q', en: 'how many days are you staying?', th: 'อยู่กี่วัน{Pq}', rom: 'yùu kìi wan {Pq}' },
        { id: 'air-stay-10', en: "I'm staying ten days", th: 'อยู่สิบวัน{P}', rom: 'yùu sìp wan {P}' },
        { id: 'air-taxi-stand', en: 'where is the taxi stand?', th: 'จุดจอดแท็กซี่อยู่ที่ไหน{Pq}', rom: 'jùt jɔ̀ɔt thɛ́k-sîi yùu thîi-nǎi {Pq}',
          parts: [{ th: 'อยู่ที่ไหน', rom: 'yùu thîi-nǎi' }, { th: 'แท็กซี่อยู่ที่ไหน', rom: 'thɛ́k-sîi yùu thîi-nǎi' }] },
        { id: 'air-departures', en: 'departures', th: 'ขาออก', rom: 'khǎa ɔ̀ɔk' },
        { id: 'air-arrivals', en: 'arrivals', th: 'ขาเข้า', rom: 'khǎa khâo' },
      ],
    },
    {
      title: 'Unit 30 · Describing and comparing',
      items: [
        { id: 'cmp-cold', en: 'cold', th: 'หนาว', rom: 'nǎao' },
        { id: 'cmp-fast', en: 'fast', th: 'เร็ว', rom: 'reo' },
        { id: 'cmp-slow', en: 'slow', th: 'ช้า', rom: 'cháa' },
        { id: 'cmp-old', en: 'old (a thing)', th: 'เก่า', rom: 'kào' },
        { id: 'cmp-new', en: 'new', th: 'ใหม่', rom: 'mài' },
        { id: 'cmp-very-good', en: 'very good', th: 'ดีมาก', rom: 'dii mâak' },
        { id: 'cmp-not-good', en: 'not good', th: 'ไม่ดี', rom: 'mâi dii' },
        { id: 'cmp-better', en: 'this one is better', th: 'อันนี้ดีกว่า', rom: 'an níi dii kwàa',
          note: [{ en: 'To compare, add this word after the adjective. It means more than:' }, { th: 'กว่า' }] },
        { id: 'cmp-cheaper-than', en: 'cheaper than that one', th: 'ถูกกว่าอันนั้น', rom: 'thùuk kwàa an nán' },
        { id: 'cmp-which-better', en: 'which one is better?', th: 'อันไหนดีกว่า{Pq}', rom: 'an nǎi dii kwàa {Pq}' },
        { id: 'cmp-best', en: 'the best', th: 'ดีที่สุด', rom: 'dii thîi-sùt',
          note: [{ en: 'For the most, add this after the adjective:' }, { th: 'ที่สุด' }] },
        { id: 'cmp-most-delicious', en: 'the most delicious', th: 'อร่อยที่สุด', rom: 'a-rɔ̀i thîi-sùt' },
        { id: 'cmp-too-fast', en: 'too fast', th: 'เร็วไป', rom: 'reo pai' },
        { id: 'cmp-many-people', en: 'a lot of people', th: 'คนเยอะ', rom: 'khon yóe' },
        { id: 'cmp-same', en: 'the same, or me too', th: 'เหมือนกัน', rom: 'mǔean kan' },
        { id: 'cmp-different', en: 'different', th: 'ต่างกัน', rom: 'tàang kan' },
      ],
    },
  ],
};
