// One short conversation per unit (keyed by the unit's key in course.js), used by the Pimsleur-style lessons.
//   who: 'A' = the learner (voiced to match the learner's gender), 'B' = the other person (the other voice)
//   Placeholders: {P} {Pq} {I} = A's polite ending / question ending / "I";
//                 {Pb} {Pbq} {Ib} = the same for B (the opposite gender to the learner).
//   en: meaning, shown on screen and used as the role-play prompt for A's lines.
window.DIALOGUES = {
  'greetings': {
    scene: 'You meet someone in your hotel lobby.', you: 'the guest',
    lines: [
      { who: 'B', th: 'สวัสดี{Pb}', rom: 'sa-wàt-dii {Pb}', en: 'Hello.' },
      { who: 'A', th: 'สวัสดี{P}', rom: 'sa-wàt-dii {P}', en: 'Hello.' },
      { who: 'B', th: 'สบายดีไหม{Pbq}', rom: 'sa-baai dii mǎi {Pbq}', en: 'How are you?' },
      { who: 'A', th: 'สบายดี ขอบคุณ{P}', rom: 'sa-baai dii, khɔ̀ɔp-khun {P}', en: "I'm fine, thank you." },
      { who: 'B', th: 'ไม่เป็นไร{Pb}', rom: 'mâi pen rai {Pb}', en: "You're welcome." },
      { who: 'A', th: 'สวัสดี{P}', rom: 'sa-wàt-dii {P}', en: 'Goodbye.' },
    ],
  },
  'getting-by': {
    scene: 'A shopkeeper asks you something, a little too fast.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'คุณชื่ออะไร{Pbq}', rom: 'khun chûue a-rai {Pbq}', en: "What's your name?" },
      { who: 'A', th: 'ไม่เข้าใจ{P}', rom: 'mâi khâo-jai {P}', en: "I don't understand." },
      { who: 'A', th: 'พูดช้าๆ หน่อย{P}', rom: 'phûut cháa-cháa nɔ̀i {P}', en: 'Please speak slowly.' },
      { who: 'B', th: 'คุณ... ชื่อ... อะไร{Pbq}', rom: 'khun... chûue... a-rai {Pbq}', en: 'What... is your... name?' },
      { who: 'A', th: 'เข้าใจ{P}', rom: 'khâo-jai {P}', en: 'I understand.' },
      { who: 'A', th: 'ยินดีที่ได้รู้จัก{P}', rom: 'yin-dii thîi dâi rúu-jàk {P}', en: 'Nice to meet you.' },
      { who: 'B', th: 'ยินดีที่ได้รู้จัก{Pb}', rom: 'yin-dii thîi dâi rúu-jàk {Pb}', en: 'Nice to meet you too.' },
    ],
  },
  'food-shopping': {
    scene: 'You are eating at a small restaurant.', you: 'the customer',
    lines: [
      { who: 'A', th: 'ขอน้ำเปล่า{P}', rom: 'khɔ̌ɔ náam plàao {P}', en: 'May I have plain water, please?' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'Sure.' },
      { who: 'A', th: 'อร่อยมาก{P}', rom: 'a-rɔ̀i mâak {P}', en: "It's very delicious." },
      { who: 'B', th: 'ขอบคุณ{Pb}', rom: 'khɔ̀ɔp-khun {Pb}', en: 'Thank you.' },
      { who: 'A', th: 'ห้องน้ำอยู่ที่ไหน{Pq}', rom: 'hɔ̂ng-náam yùu thîi-nǎi {Pq}', en: 'Where is the toilet?' },
      { who: 'B', th: 'ตรงนั้น{Pb}', rom: 'trong nán {Pb}', en: 'Over there.' },
      { who: 'A', th: 'เช็คบิลด้วย{P}', rom: 'chék bin dûai {P}', en: 'The bill, please.' },
      { who: 'B', th: 'หนึ่งร้อยบาท{Pb}', rom: 'nùeng rɔ́ɔi bàat {Pb}', en: 'One hundred baht.' },
    ],
  },
  'numbers': {
    scene: 'Buying fruit at a market stall.', you: 'the shopper',
    lines: [
      { who: 'B', th: 'สวัสดี{Pb}', rom: 'sa-wàt-dii {Pb}', en: 'Hello.' },
      { who: 'A', th: 'อันนี้เท่าไร{Pq}', rom: 'an níi thâo-rài {Pq}', en: 'How much is this one?' },
      { who: 'B', th: 'ยี่สิบบาท{Pb}', rom: 'yîi-sìp bàat {Pb}', en: 'Twenty baht.' },
      { who: 'A', th: 'ยี่สิบบาท', rom: 'yîi-sìp bàat', en: 'Twenty baht?' },
      { who: 'B', th: 'ใช่{Pb}', rom: 'châi {Pb}', en: 'Yes.' },
      { who: 'A', th: 'หนึ่งร้อยบาท', rom: 'nùeng rɔ́ɔi bàat', en: '(handing over a note) One hundred baht.' },
      { who: 'B', th: 'ขอบคุณ{Pb}', rom: 'khɔ̀ɔp-khun {Pb}', en: 'Thank you.' },
    ],
  },
  'money': {
    scene: 'Bargaining for a shirt at a night market.', you: 'the shopper',
    lines: [
      { who: 'A', th: 'อันนี้เท่าไร{Pq}', rom: 'an níi thâo-rài {Pq}', en: 'How much is this one?' },
      { who: 'B', th: 'ห้าร้อยบาท{Pb}', rom: 'hâa rɔ́ɔi bàat {Pb}', en: 'Five hundred baht.' },
      { who: 'A', th: 'แพงมาก ลดหน่อยได้ไหม{Pq}', rom: 'phɛɛng mâak, lót nɔ̀i dâi mǎi {Pq}', en: 'Very expensive. Can you lower the price a bit?' },
      { who: 'B', th: 'สี่ร้อยบาท{Pb}', rom: 'sìi rɔ́ɔi bàat {Pb}', en: 'Four hundred baht.' },
      { who: 'A', th: 'มีถูกกว่านี้ไหม{Pq}', rom: 'mii thùuk kwàa níi mǎi {Pq}', en: 'Do you have a cheaper one?' },
      { who: 'B', th: 'อันนี้สองร้อยบาท{Pb}', rom: 'an níi sɔ̌ɔng rɔ́ɔi bàat {Pb}', en: 'This one is two hundred baht.' },
      { who: 'A', th: 'ตกลง เอา{P}', rom: 'tòk-long, ao {P}', en: "OK, deal. I'll take it." },
      { who: 'B', th: 'ขอบคุณ{Pb}', rom: 'khɔ̀ɔp-khun {Pb}', en: 'Thank you.' },
    ],
  },
  'want-have-can': {
    scene: 'A Thai friend checks in on you at lunchtime.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'กินข้าวหรือยัง{Pbq}', rom: 'kin khâao rǔue yang {Pbq}', en: 'Have you eaten yet?' },
      { who: 'A', th: 'ยัง{P}', rom: 'yang {P}', en: 'Not yet.' },
      { who: 'B', th: 'อยากกินอะไร{Pbq}', rom: 'yàak kin a-rai {Pbq}', en: 'What do you want to eat?' },
      { who: 'A', th: '{I}ชอบอาหารไทย{P}', rom: '{I} chɔ̂ɔp aa-hǎan thai {P}', en: 'I like Thai food.' },
      { who: 'B', th: 'ไปกินข้าวกัน{Pb}', rom: 'pai kin khâao kan {Pb}', en: "Let's go eat." },
      { who: 'A', th: 'ได้{P}', rom: 'dâi {P}', en: 'OK, sure.' },
    ],
  },
  'getting-around': {
    scene: 'Asking a passer-by the way back to your hotel.', you: 'the visitor',
    lines: [
      { who: 'A', th: 'ขอโทษ{P}', rom: 'khɔ̌ɔ-thôot {P}', en: 'Excuse me.' },
      { who: 'A', th: 'อยากไปโรงแรม{P}', rom: 'yàak pai roong-rɛɛm {P}', en: 'I want to go to the hotel.' },
      { who: 'B', th: 'ไม่ไกล{Pb}', rom: 'mâi klai {Pb}', en: "It's not far." },
      { who: 'B', th: 'ตรงไป แล้วเลี้ยวขวา{Pb}', rom: 'trong pai, lɛ́ɛo líao khwǎa {Pb}', en: 'Go straight, then turn right.' },
      { who: 'A', th: 'ตรงไป เลี้ยวขวา', rom: 'trong pai, líao khwǎa', en: 'Straight, then right?' },
      { who: 'B', th: 'ใช่{Pb}', rom: 'châi {Pb}', en: 'Yes.' },
      { who: 'A', th: 'ขอบคุณ{P}', rom: 'khɔ̀ɔp-khun {P}', en: 'Thank you.' },
    ],
  },
  'transport': {
    scene: 'Taking a taxi to the airport.', you: 'the passenger',
    lines: [
      { who: 'A', th: 'ไปสนามบิน{P}', rom: 'pai sa-nǎam-bin {P}', en: 'To the airport, please.' },
      { who: 'A', th: 'เปิดมิเตอร์ด้วย{P}', rom: 'pòet mí-tôe dûai {P}', en: 'Please use the meter.' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'OK.' },
      { who: 'A', th: 'นานเท่าไร{Pq}', rom: 'naan thâo-rài {Pq}', en: 'How long does it take?' },
      { who: 'B', th: 'รถติด หนึ่งชั่วโมง{Pb}', rom: 'rót tìt, nùeng chûa-moong {Pb}', en: 'Traffic is bad. One hour.' },
      { who: 'B', th: 'ถึงแล้ว{Pb}', rom: 'thǔeng lɛ́ɛo {Pb}', en: "We've arrived." },
      { who: 'A', th: 'จอดตรงนี้{P}', rom: 'jɔ̀ɔt trong níi {P}', en: 'Stop here, please.' },
      { who: 'A', th: 'ไม่ต้องทอน{P}', rom: 'mâi tɔ̂ng thɔɔn {P}', en: 'Keep the change.' },
      { who: 'B', th: 'ขอบคุณ{Pb} ตุ๊กตุ๊กจอดตรงนั้น', rom: 'khɔ̀ɔp-khun {Pb}, túk-túk jɔ̀ɔt trong nán', en: 'Thank you. The tuk-tuks wait over there.' },
    ],
  },
  'hotel': {
    scene: 'Checking in at your hotel.', you: 'the guest',
    lines: [
      { who: 'B', th: 'สวัสดี{Pb}', rom: 'sa-wàt-dii {Pb}', en: 'Hello.' },
      { who: 'A', th: '{I}จองไว้แล้ว{P}', rom: '{I} jɔɔng wái lɛ́ɛo {P}', en: 'I have a reservation.' },
      { who: 'B', th: 'สองคืน ใช่ไหม{Pbq}', rom: 'sɔ̌ɔng khuen, châi mǎi {Pbq}', en: 'Two nights, right?' },
      { who: 'A', th: 'ใช่{P}', rom: 'châi {P}', en: 'Yes.' },
      { who: 'A', th: 'รหัสไวไฟคืออะไร{Pq}', rom: 'ra-hàt wai-fai khue a-rai {Pq}', en: "What's the Wi-Fi password?" },
      { who: 'B', th: 'หนึ่ง สอง สาม สี่{Pb}', rom: 'nùeng, sɔ̌ɔng, sǎam, sìi {Pb}', en: 'One, two, three, four.' },
      { who: 'A', th: 'อาหารเช้ากี่โมง{Pq}', rom: 'aa-hǎan cháao kìi moong {Pq}', en: 'What time is breakfast?' },
      { who: 'B', th: 'เจ็ดโมง{Pb}', rom: 'jèt moong {Pb}', en: "Seven o'clock." },
    ],
  },
  'ordering-food': {
    scene: 'Ordering lunch at a restaurant.', you: 'the customer',
    lines: [
      { who: 'A', th: 'ขอเมนูหน่อย{P}', rom: 'khɔ̌ɔ mee-nuu nɔ̀i {P}', en: 'The menu, please.' },
      { who: 'A', th: 'เอาข้าวผัดไก่{P}', rom: 'ao khâao phàt kài {P}', en: "I'd like chicken fried rice." },
      { who: 'B', th: 'เผ็ดไหม{Pbq}', rom: 'phèt mǎi {Pbq}', en: 'Spicy?' },
      { who: 'A', th: 'ไม่ใส่พริก{P}', rom: 'mâi sài phrík {P}', en: 'No chili, please.' },
      { who: 'B', th: 'ดื่มอะไร{Pbq}', rom: 'dùuem a-rai {Pbq}', en: 'Anything to drink?' },
      { who: 'A', th: 'กาแฟเย็น หวานน้อย{P}', rom: 'kaa-fɛɛ yen, wǎan nɔ́ɔi {P}', en: 'Iced coffee, not too sweet.' },
      { who: 'A', th: 'อิ่มแล้ว เช็คบิลด้วย{P}', rom: 'ìm lɛ́ɛo, chék bin dûai {P}', en: "I'm full. The bill, please." },
    ],
  },
  'about-you': {
    scene: 'Chatting with someone at a café.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'คุณมาจากไหน{Pbq}', rom: 'khun maa jàak nǎi {Pbq}', en: 'Where are you from?' },
      { who: 'A', th: '{I}มาจากอเมริกา{P}', rom: '{I} maa jàak a-mee-ri-kaa {P}', en: "I'm from America." },
      { who: 'B', th: 'พูดภาษาไทยได้ไหม{Pbq}', rom: 'phûut phaa-sǎa thai dâi mǎi {Pbq}', en: 'Can you speak Thai?' },
      { who: 'A', th: '{I}พูดภาษาไทยได้นิดหน่อย{P}', rom: '{I} phûut phaa-sǎa thai dâi nít-nɔ̀i {P}', en: 'I can speak a little Thai.' },
      { who: 'B', th: 'ชอบประเทศไทยไหม{Pbq}', rom: 'chɔ̂ɔp pra-thêet thai mǎi {Pbq}', en: 'Do you like Thailand?' },
      { who: 'A', th: '{I}ชอบประเทศไทย{P}', rom: '{I} chɔ̂ɔp pra-thêet thai {P}', en: 'I like Thailand.' },
    ],
  },
  'time-feelings': {
    scene: 'A hot afternoon with a new friend.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'วันนี้ร้อนมาก{Pb}', rom: 'wan-níi rɔ́ɔn mâak {Pb}', en: "It's very hot today." },
      { who: 'A', th: 'ใช่ ร้อนมาก{P}', rom: 'châi, rɔ́ɔn mâak {P}', en: 'Yes, very hot.' },
      { who: 'B', th: 'หิวข้าวไหม{Pbq}', rom: 'hǐu khâao mǎi {Pbq}', en: 'Are you hungry?' },
      { who: 'A', th: 'หิวข้าว แต่เหนื่อย{P}', rom: 'hǐu khâao, tɛ̀ɛ nùeai {P}', en: "I'm hungry, but tired." },
      { who: 'A', th: 'กี่โมงแล้ว{Pq}', rom: 'kìi moong lɛ́ɛo {Pq}', en: 'What time is it?' },
      { who: 'B', th: 'ห้าโมงเย็น{Pb}', rom: 'hâa moong yen {Pb}', en: "Five in the evening." },
      { who: 'A', th: 'เจอกันพรุ่งนี้{P}', rom: 'joe kan phrûng-níi {P}', en: 'See you tomorrow.' },
      { who: 'B', th: 'เจอกันพรุ่งนี้{Pb}', rom: 'joe kan phrûng-níi {Pb}', en: 'See you tomorrow.' },
    ],
  },
  'health': {
    scene: "You're not feeling well and ask the hotel staff for help.", you: 'the guest',
    lines: [
      { who: 'A', th: 'ไม่สบาย{P}', rom: 'mâi sa-baai {P}', en: "I'm sick." },
      { who: 'B', th: 'เป็นอะไร{Pbq}', rom: 'pen a-rai {Pbq}', en: "What's wrong?" },
      { who: 'A', th: 'ปวดหัว เป็นไข้{P}', rom: 'pùat hǔa, pen khâi {P}', en: 'I have a headache and a fever.' },
      { who: 'A', th: 'ท้องเสียด้วย{P}', rom: 'thɔ́ɔng sǐa dûai {P}', en: 'And I have diarrhea.' },
      { who: 'B', th: 'ไปโรงพยาบาลไหม{Pbq}', rom: 'pai roong-pha-yaa-baan mǎi {Pbq}', en: 'Do you want to go to the hospital?' },
      { who: 'A', th: 'ร้านขายยาอยู่ที่ไหน{Pq}', rom: 'ráan khǎai yaa yùu thîi-nǎi {Pq}', en: 'Where is a pharmacy?' },
      { who: 'B', th: 'อยู่ใกล้ๆ นี้{Pb}', rom: 'yùu klâi-klâi níi {Pb}', en: "It's near here." },
      { who: 'A', th: 'ขอบคุณ{P}', rom: 'khɔ̀ɔp-khun {P}', en: 'Thank you.' },
    ],
  },
  'small-talk': {
    scene: 'A friendly vendor starts chatting with you.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'มาเที่ยวเหรอ{Pbq}', rom: 'maa thîao rǒe {Pbq}', en: 'Here on holiday?' },
      { who: 'A', th: 'มาเที่ยว{P}', rom: 'maa thîao {P}', en: "I'm here on holiday." },
      { who: 'A', th: 'มาเมืองไทยครั้งแรก{P}', rom: 'maa mueang thai khráng rɛ̂ɛk {P}', en: 'This is my first time in Thailand.' },
      { who: 'B', th: 'พูดไทยเก่ง{Pb}', rom: 'phûut thai kèng {Pb}', en: 'You speak Thai well.' },
      { who: 'A', th: 'ยังไม่เก่ง{P}', rom: 'yang mâi kèng {P}', en: "Not really, I'm not good yet." },
      { who: 'B', th: 'ชอบไหม{Pbq}', rom: 'chɔ̂ɔp mǎi {Pbq}', en: 'Do you like it?' },
      { who: 'A', th: 'ชอบมาก สนุกมาก{P}', rom: 'chɔ̂ɔp mâak, sa-nùk mâak {P}', en: "I like it a lot. It's a lot of fun." },
    ],
  },
  'question-words': {
    scene: 'A friend tells you about their plans.', you: 'the friend',
    lines: [
      { who: 'B', th: 'พรุ่งนี้จะไปตลาด{Pb}', rom: 'phrûng-níi jà pai ta-làat {Pb}', en: "Tomorrow I'm going to the market." },
      { who: 'A', th: 'ไปกับใคร{Pq}', rom: 'pai kàp khrai {Pq}', en: 'Who are you going with?' },
      { who: 'B', th: 'ไปกับเพื่อน{Pb}', rom: 'pai kàp phûean {Pb}', en: 'With a friend.' },
      { who: 'A', th: 'ไปยังไง{Pq}', rom: 'pai yang-ngai {Pq}', en: 'How are you getting there?' },
      { who: 'B', th: 'นั่งรถไฟฟ้า{Pb}', rom: 'nâng rót-fai-fáa {Pb}', en: 'By skytrain.' },
      { who: 'A', th: 'จะไปเมื่อไร{Pq}', rom: 'jà pai mûea-rài {Pq}', en: 'When are you going?' },
      { who: 'B', th: 'ตอนเช้า{Pb}', rom: 'tɔɔn cháao {Pb}', en: 'In the morning.' },
    ],
  },
  'verbs': {
    scene: 'Shopping with a Thai friend.', you: 'the shopper',
    lines: [
      { who: 'A', th: 'รอ{I}ด้วย{P}', rom: 'rɔɔ {I} dûai {P}', en: 'Wait for me, please.' },
      { who: 'B', th: 'ได้ จะซื้ออะไร{Pbq}', rom: 'dâi, jà súue a-rai {Pbq}', en: 'Sure. What are you going to buy?' },
      { who: 'A', th: 'อยากซื้ออันนี้{P}', rom: 'yàak súue an-níi {P}', en: 'I want to buy this one.' },
      { who: 'B', th: 'ดูก่อน{Pb}', rom: 'duu kɔ̀ɔn {Pb}', en: 'Take a look first.' },
      { who: 'A', th: 'ไม่รู้ คิดก่อน{P}', rom: 'mâi rúu, khít kɔ̀ɔn {P}', en: "I don't know. Let me think first." },
      { who: 'B', th: 'ได้ ไม่เป็นไร{Pb}', rom: 'dâi, mâi pen rai {Pb}', en: 'Sure, no problem.' },
    ],
  },
  'days-times': {
    scene: 'Making weekend plans.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'วันนี้วันอะไร{Pbq}', rom: 'wan-níi wan a-rai {Pbq}', en: 'What day is it today?' },
      { who: 'A', th: 'วันศุกร์{P}', rom: 'wan sùk {P}', en: 'Friday.' },
      { who: 'B', th: 'พรุ่งนี้ว่างไหม{Pbq}', rom: 'phrûng-níi wâang mǎi {Pbq}', en: 'Are you free tomorrow?' },
      { who: 'A', th: 'ตอนเย็นว่าง{P}', rom: 'tɔɔn yen wâang {P}', en: "I'm free in the evening." },
      { who: 'B', th: 'ไปตลาดกลางคืนไหม{Pbq}', rom: 'pai ta-làat klaang-khuen mǎi {Pbq}', en: 'Shall we go to the night market?' },
      { who: 'A', th: 'ได้ เจอกันพรุ่งนี้{P}', rom: 'dâi, joe kan phrûng-níi {P}', en: 'Sure. See you tomorrow.' },
    ],
  },
  'places': {
    scene: 'Looking for a convenience store.', you: 'the visitor',
    lines: [
      { who: 'A', th: 'แถวนี้มีเซเว่นไหม{Pq}', rom: 'thɛ̌o níi mii see-wên mǎi {Pq}', en: 'Is there a 7-Eleven around here?' },
      { who: 'B', th: 'มี{Pb} ตรงไปแล้วเลี้ยวซ้าย', rom: 'mii {Pb}, trong pai lɛ́ɛo líao sáai', en: 'Yes. Go straight, then turn left.' },
      { who: 'A', th: 'เดินไปได้ไหม{Pq}', rom: 'doen pai dâi mǎi {Pq}', en: 'Can I walk there?' },
      { who: 'B', th: 'ได้{Pb} ไม่ไกล', rom: 'dâi {Pb}, mâi klai', en: "Yes, it's not far." },
      { who: 'A', th: 'อยู่ทางซ้าย{Pq}', rom: 'yùu thaang sáai {Pq}', en: "It's on the left?" },
      { who: 'B', th: 'ใช่{Pb}', rom: 'châi {Pb}', en: 'Yes.' },
      { who: 'A', th: 'ขอบคุณ{P}', rom: 'khɔ̀ɔp-khun {P}', en: 'Thank you.' },
    ],
  },
  'street-food': {
    scene: 'Ordering at a street food stall.', you: 'the customer',
    lines: [
      { who: 'A', th: 'ที่นี่อะไรอร่อย{Pq}', rom: 'thîi-nîi a-rai a-rɔ̀i {Pq}', en: "What's good here?" },
      { who: 'B', th: 'ผัดกะเพราหมู{Pb}', rom: 'phàt ka-phrao mǔu {Pb}', en: 'Stir-fried basil pork.' },
      { who: 'A', th: 'เอาหนึ่งที่ ใส่ไข่ดาว{P}', rom: 'ao nùeng thîi, sài khài-daao {P}', en: 'One serving, with a fried egg.' },
      { who: 'B', th: 'เผ็ดไหม{Pbq}', rom: 'phèt mǎi {Pbq}', en: 'Spicy?' },
      { who: 'A', th: 'เผ็ดนิดหน่อย{P}', rom: 'phèt nít-nɔ̀i {P}', en: 'A little spicy.' },
      { who: 'A', th: 'แล้วก็ข้าวเหนียวมะม่วง{P}', rom: 'lɛ́ɛo kɔ̂ɔ khâao-nǐao ma-mûang {P}', en: 'And mango sticky rice too.' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'Sure.' },
    ],
  },
  'clothes': {
    scene: 'Trying on a shirt at a shop.', you: 'the shopper',
    lines: [
      { who: 'A', th: 'ลองได้ไหม{Pq}', rom: 'lɔɔng dâi mǎi {Pq}', en: 'Can I try it on?' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'Sure.' },
      { who: 'A', th: 'เล็กไป มีใหญ่กว่านี้ไหม{Pq}', rom: 'lék pai, mii yài kwàa níi mǎi {Pq}', en: "It's too small. Do you have a bigger one?" },
      { who: 'B', th: 'มี{Pb} เอาสีอะไร{Pbq}', rom: 'mii {Pb}, ao sǐi a-rai {Pbq}', en: 'Yes. Which color would you like?' },
      { who: 'A', th: 'สีดำ{P}', rom: 'sǐi dam {P}', en: 'Black.' },
      { who: 'B', th: 'สีดำไม่มี มีสีขาว{Pb}', rom: 'sǐi dam mâi mii, mii sǐi khǎao {Pb}', en: "There's no black. There's white." },
      { who: 'A', th: 'โอเค เอาสีขาว{P}', rom: 'oo-khee, ao sǐi khǎao {P}', en: "OK, I'll take white." },
    ],
  },
  'massage': {
    scene: 'Booking a Thai massage.', you: 'the customer',
    lines: [
      { who: 'A', th: 'นวดไทย ชั่วโมงละเท่าไร{Pq}', rom: 'nûat thai, chûa-moong lá thâo-rài {Pq}', en: 'How much is a Thai massage per hour?' },
      { who: 'B', th: 'สามร้อยบาท{Pb}', rom: 'sǎam rɔ́ɔi bàat {Pb}', en: 'Three hundred baht.' },
      { who: 'A', th: 'เอาหนึ่งชั่วโมง{P}', rom: 'ao nùeng chûa-moong {P}', en: "I'll have one hour." },
      { who: 'B', th: 'แรงไหม{Pbq}', rom: 'rɛɛng mǎi {Pbq}', en: 'Is it too strong?' },
      { who: 'A', th: 'เบาๆ หน่อย{P}', rom: 'bao-bao nɔ̀i {P}', en: 'Softer, please.' },
      { who: 'A', th: 'ปวดหลัง{P}', rom: 'pùat lǎng {P}', en: 'My back hurts.' },
      { who: 'B', th: 'โอเค{Pb}', rom: 'oo-khee {Pb}', en: 'OK.' },
      { who: 'A', th: 'สบายมาก{P}', rom: 'sa-baai mâak {P}', en: 'That feels really good.' },
    ],
  },
  'beaches': {
    scene: 'Buying a boat ticket to an island.', you: 'the traveler',
    lines: [
      { who: 'A', th: 'ตั๋วเรือไปเกาะเท่าไร{Pq}', rom: 'tǔa ruea pai kɔ̀ thâo-rài {Pq}', en: 'How much is a boat ticket to the island?' },
      { who: 'B', th: 'สองร้อยบาท{Pb}', rom: 'sɔ̌ɔng rɔ́ɔi bàat {Pb}', en: 'Two hundred baht.' },
      { who: 'A', th: 'เรือออกกี่โมง{Pq}', rom: 'ruea ɔ̀ɔk kìi moong {Pq}', en: 'What time does the boat leave?' },
      { who: 'B', th: 'เก้าโมง{Pb}', rom: 'kâao moong {Pb}', en: "Nine o'clock." },
      { who: 'A', th: 'มีเสื้อชูชีพไหม{Pq}', rom: 'mii sûea chuu-chîip mǎi {Pq}', en: 'Are there life jackets?' },
      { who: 'B', th: 'มี{Pb} วันนี้คลื่นใหญ่', rom: 'mii {Pb}, wan-níi khlûen yài', en: 'Yes. The waves are big today.' },
      { who: 'A', th: 'ว่ายน้ำได้ไหม{Pq}', rom: 'wâai-náam dâi mǎi {Pq}', en: 'Can I swim?' },
      { who: 'B', th: 'ไม่ได้ อันตราย{Pb}', rom: 'mâi dâi, an-ta-raai {Pb}', en: "No, it's dangerous." },
    ],
  },
  'temples': {
    scene: 'Visiting a temple.', you: 'the visitor',
    lines: [
      { who: 'A', th: 'เข้าไปได้ไหม{Pq}', rom: 'khâo pai dâi mǎi {Pq}', en: 'May I go in?' },
      { who: 'B', th: 'ได้ ต้องถอดรองเท้า{Pb}', rom: 'dâi, tɔ̂ng thɔ̀ɔt rɔɔng-tháao {Pb}', en: 'Yes, but you need to take off your shoes.' },
      { who: 'A', th: 'แต่งตัวแบบนี้ได้ไหม{Pq}', rom: 'tɛ̀ng-tua bɛ̀ɛp níi dâi mǎi {Pq}', en: 'Is this outfit OK?' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: "It's fine." },
      { who: 'A', th: 'วัดนี้สวยมาก{P}', rom: 'wát níi sǔai mâak {P}', en: 'This temple is very beautiful.' },
      { who: 'B', th: 'มาไหว้พระเหรอ{Pbq}', rom: 'maa wâi phrá rǒe {Pbq}', en: 'Did you come to pay respects?' },
      { who: 'A', th: 'ใช่ มาทำบุญ{P}', rom: 'châi, maa tham-bun {P}', en: 'Yes, I came to make merit.' },
      { who: 'B', th: 'นับถือศาสนาอะไร{Pbq}', rom: 'náp-thǔue sàat-sa-nǎa a-rai {Pbq}', en: 'What religion are you?' },
      { who: 'A', th: '{I}เป็นคริสต์ แต่ชอบนั่งสมาธิ{P}', rom: '{I} pen khrít, tɛ̀ɛ chɔ̂ɔp nâng sa-maa-thí {P}', en: "I'm Christian, but I like to meditate." },
      { who: 'B', th: 'ดีมาก{Pb} ใจสงบ', rom: 'dii mâak {Pb}, jai sa-ngòp', en: 'Very good. A calm mind.' },
    ],
  },
  'phone': {
    scene: 'At a phone shop at the airport.', you: 'the traveler',
    lines: [
      { who: 'A', th: 'อยากซื้อซิมการ์ด{P}', rom: 'yàak súue sim-káat {P}', en: 'I want to buy a SIM card.' },
      { who: 'B', th: 'กี่วัน{Pbq}', rom: 'kìi wan {Pbq}', en: 'For how many days?' },
      { who: 'A', th: 'สองอาทิตย์{P}', rom: 'sɔ̌ɔng aa-thít {P}', en: 'Two weeks.' },
      { who: 'B', th: 'ห้าร้อยบาท{Pb}', rom: 'hâa rɔ́ɔi bàat {Pb}', en: 'Five hundred baht.' },
      { who: 'A', th: 'แบตหมด ชาร์จโทรศัพท์ได้ไหม{Pq}', rom: 'bɛ̀t mòt, cháat thoo-ra-sàp dâi mǎi {Pq}', en: 'My battery is dead. Can I charge my phone?' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'Sure.' },
      { who: 'A', th: 'มีไวไฟไหม{Pq}', rom: 'mii wai-fai mǎi {Pq}', en: 'Is there Wi-Fi?' },
      { who: 'B', th: 'มี{Pb}', rom: 'mii {Pb}', en: 'Yes, there is.' },
    ],
  },
  'friends': {
    scene: 'Getting to know someone at a party.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'อยู่ที่ไหน{Pbq}', rom: 'yùu thîi-nǎi {Pbq}', en: 'Where do you live?' },
      { who: 'A', th: '{I}อยู่อเมริกา{P}', rom: '{I} yùu a-mee-ri-kaa {P}', en: 'I live in America.' },
      { who: 'B', th: 'แต่งงานหรือยัง{Pbq}', rom: 'tɛ̀ng-ngaan rǔue yang {Pbq}', en: 'Are you married?' },
      { who: 'A', th: 'แต่งงานแล้ว{P}', rom: 'tɛ̀ng-ngaan lɛ́ɛo {P}', en: "I'm married." },
      { who: 'B', th: 'ขอไลน์หน่อยได้ไหม{Pbq}', rom: 'khɔ̌ɔ lai nɔ̀i dâi mǎi {Pbq}', en: 'Can I have your LINE?' },
      { who: 'A', th: 'ได้{P}', rom: 'dâi {P}', en: 'Sure.' },
      { who: 'B', th: 'ไปกินข้าวด้วยกันไหม{Pbq}', rom: 'pai kin khâao dûai kan mǎi {Pbq}', en: 'Shall we go eat together?' },
      { who: 'A', th: 'ได้ ใจดีมาก{P}', rom: 'dâi, jai-dii mâak {P}', en: "Sure. You're very kind." },
    ],
  },
  'reactions': {
    scene: 'A friend shares some news.', you: 'the friend',
    lines: [
      { who: 'B', th: '{Ib}ได้งานใหม่{Pb}', rom: '{Ib} dâi ngaan mài {Pb}', en: 'I got a new job.' },
      { who: 'A', th: 'จริงเหรอ ยินดีด้วย{P}', rom: 'jing rǒe, yin-dii dûai {P}', en: 'Really? Congratulations.' },
      { who: 'B', th: 'แต่ต้องย้ายไปเชียงใหม่{Pb}', rom: 'tɛ̀ɛ tɔ̂ng yáai pai chiang-mài {Pb}', en: 'But I have to move to Chiang Mai.' },
      { who: 'A', th: 'น่าเสียดาย คิดถึง{P}', rom: 'nâa sǐa-daai, khít-thǔeng {P}', en: "What a pity. I'll miss you." },
      { who: 'B', th: 'ใจเย็นๆ ติดต่อกันนะ{Pb}', rom: 'jai yen yen, tìt-tɔ̀ɔ kan ná {Pb}', en: "Take it easy. Let's keep in touch." },
      { who: 'A', th: 'ได้เลย{P}', rom: 'dâi loei {P}', en: 'Sure, of course.' },
    ],
  },
  'family': {
    scene: "A friend introduces you to their family.", you: 'the visitor',
    lines: [
      { who: 'B', th: 'นี่ครอบครัว{Ib}{Pb}', rom: 'nîi khrɔ̂ɔp-khrua {Ib} {Pb}', en: 'This is my family.' },
      { who: 'A', th: 'ยินดีที่ได้รู้จัก{P}', rom: 'yin-dii thîi dâi rúu-jàk {P}', en: 'Nice to meet you.' },
      { who: 'B', th: 'มีพี่น้องกี่คน{Pbq}', rom: 'mii phîi-nɔ́ɔng kìi khon {Pbq}', en: 'How many brothers and sisters do you have?' },
      { who: 'A', th: 'มีน้องหนึ่งคน{P}', rom: 'mii nɔ́ɔng nùeng khon {P}', en: 'I have one younger sibling.' },
      { who: 'B', th: 'มีลูกไหม{Pbq}', rom: 'mii lûuk mǎi {Pbq}', en: 'Do you have children?' },
      { who: 'A', th: 'มีลูกสองคน{P}', rom: 'mii lûuk sɔ̌ɔng khon {P}', en: 'I have two children.' },
      { who: 'B', th: 'ลูกชายหรือลูกสาว{Pbq}', rom: 'lûuk-chaai rǔue lûuk-sǎao {Pbq}', en: 'Sons or daughters?' },
      { who: 'A', th: 'ลูกชายหนึ่ง ลูกสาวหนึ่ง{P}', rom: 'lûuk-chaai nùeng, lûuk-sǎao nùeng {P}', en: 'One son and one daughter.' },
    ],
  },
  'telling-time': {
    scene: 'Arranging to meet a friend for dinner.', you: 'the friend',
    lines: [
      { who: 'A', th: 'เจอกันกี่โมง{Pq}', rom: 'joe kan kìi moong {Pq}', en: 'What time shall we meet?' },
      { who: 'B', th: 'หนึ่งทุ่ม ได้ไหม{Pbq}', rom: 'nùeng thûm, dâi mǎi {Pbq}', en: 'Seven in the evening, is that OK?' },
      { who: 'A', th: 'หนึ่งทุ่มครึ่งได้ไหม{Pq}', rom: 'nùeng thûm khrûeng dâi mǎi {Pq}', en: 'Could we make it half past seven?' },
      { who: 'B', th: 'ได้{Pb} ร้านปิดสามทุ่ม', rom: 'dâi {Pb}, ráan pìt sǎam thûm', en: 'Sure. The restaurant closes at nine.' },
      { who: 'A', th: 'ตอนนี้กี่โมงแล้ว{Pq}', rom: 'tɔɔn-níi kìi moong lɛ́ɛo {Pq}', en: 'What time is it now?' },
      { who: 'B', th: 'บ่ายสามโมงครึ่ง{Pb}', rom: 'bàai sǎam moong khrûeng {Pb}', en: 'Half past three.' },
      { who: 'A', th: 'โอเค เจอกันหนึ่งทุ่มครึ่ง{P}', rom: 'oo-khee, joe kan nùeng thûm khrûeng {P}', en: 'OK, see you at half past seven.' },
    ],
  },
  'airport': {
    scene: 'Arriving at the airport: immigration, then a missing bag.', you: 'the traveler',
    lines: [
      { who: 'B', th: 'ขอพาสปอร์ต{Pb}', rom: 'khɔ̌ɔ pháat-sa-pɔ̀ɔt {Pb}', en: 'Passport, please.' },
      { who: 'A', th: 'นี่{P}', rom: 'nîi {P}', en: 'Here you are.' },
      { who: 'B', th: 'อยู่กี่วัน{Pbq}', rom: 'yùu kìi wan {Pbq}', en: 'How many days are you staying?' },
      { who: 'A', th: 'อยู่สิบวัน มาเที่ยว{P}', rom: 'yùu sìp wan, maa thîao {P}', en: "Ten days. I'm here on holiday." },
      { who: 'B', th: 'ขอบคุณ{Pb} ทางออกอยู่ทางนั้น', rom: 'khɔ̀ɔp-khun {Pb}, thaang ɔ̀ɔk yùu thaang nán', en: 'Thank you. The exit is that way.' },
      { who: 'A', th: 'ขอโทษ{P} กระเป๋าหาย{P}', rom: 'khɔ̌ɔ-thôot {P}, kra-pǎo hǎai {P}', en: 'Excuse me. My luggage is lost.' },
      { who: 'B', th: 'เที่ยวบินอะไร{Pbq}', rom: 'thîao-bin a-rai {Pbq}', en: 'Which flight?' },
      { who: 'A', th: 'เที่ยวบินจากเชียงใหม่{P}', rom: 'thîao-bin jàak chiang-mài {P}', en: 'The flight from Chiang Mai.' },
    ],
  },
  'comparing': {
    scene: 'Choosing between two bags at a shop.', you: 'the shopper',
    lines: [
      { who: 'A', th: 'อันไหนดีกว่า{Pq}', rom: 'an nǎi dii kwàa {Pq}', en: 'Which one is better?' },
      { who: 'B', th: 'อันนี้ดีกว่า แต่แพงกว่า{Pb}', rom: 'an níi dii kwàa, tɛ̀ɛ phɛɛng kwàa {Pb}', en: 'This one is better, but more expensive.' },
      { who: 'A', th: 'อันนั้นถูกกว่าไหม{Pq}', rom: 'an nán thùuk kwàa mǎi {Pq}', en: 'Is that one cheaper?' },
      { who: 'B', th: 'ถูกกว่า แต่เก่า{Pb}', rom: 'thùuk kwàa, tɛ̀ɛ kào {Pb}', en: "It's cheaper, but old." },
      { who: 'A', th: 'เอาอันใหม่ อันนี้ดีที่สุด{P}', rom: 'ao an mài, an níi dii thîi-sùt {P}', en: "I'll take the new one. This is the best." },
      { who: 'B', th: 'ใช่{Pb} ดีที่สุด', rom: 'châi {Pb}, dii thîi-sùt', en: 'Yes, the best.' },
    ],
  },
  'weather': {
    scene: 'Planning a day out during the rainy season.', you: 'the visitor',
    lines: [
      { who: 'A', th: 'วันนี้อากาศเป็นยังไง{Pq}', rom: 'wan-níi aa-kàat pen yang-ngai {Pq}', en: "How's the weather today?" },
      { who: 'B', th: 'ตอนเช้าแดดออก แต่ตอนเย็นฝนจะตก{Pb}', rom: 'tɔɔn cháao dɛ̀ɛt ɔ̀ɔk, tɛ̀ɛ tɔɔn yen fǒn jà tòk {Pb}', en: "Sunny in the morning, but it's going to rain in the evening." },
      { who: 'A', th: 'หน้าฝนเหรอ{Pq}', rom: 'nâa fǒn rǒe {Pq}', en: "Is it the rainy season?" },
      { who: 'B', th: 'ใช่{Pb} ร้อนและชื้นมาก', rom: 'châi {Pb}, rɔ́ɔn lɛ́ chúuen mâak', en: "Yes. It's very hot and humid." },
      { who: 'A', th: 'มีร่มไหม{Pq}', rom: 'mii rôm mǎi {Pq}', en: 'Do you have an umbrella?' },
      { who: 'B', th: 'มี{Pb} เอาไปด้วย', rom: 'mii {Pb}, ao pai dûai', en: 'Yes. Take it with you.' },
      { who: 'A', th: 'ถ้าฝนตก จะอยู่โรงแรม{P}', rom: 'thâa fǒn tòk, jà yùu roong-rɛɛm {P}', en: "If it rains, I'll stay at the hotel." },
      { who: 'B', th: 'สบายๆ{Pb} หน้าหนาวอากาศดีกว่า', rom: 'sa-baai sa-baai {Pb}, nâa nǎao aa-kàat dii kwàa', en: 'No stress. The weather is better in the cool season.' },
    ],
  },
  'problems': {
    scene: 'Something is wrong with your hotel room.', you: 'the guest',
    lines: [
      { who: 'A', th: 'ขอโทษที่รบกวน{P} มีปัญหา{P}', rom: 'khɔ̌ɔ-thôot thîi róp-kuan {P}, mii pan-hǎa {P}', en: "Sorry to trouble you. There's a problem." },
      { who: 'B', th: 'เป็นอะไร{Pbq}', rom: 'pen a-rai {Pbq}', en: "What's wrong?" },
      { who: 'A', th: 'ฝักบัวเสีย และไม่มีกระดาษทิชชู่{P}', rom: 'fàk-bua sǐa, lɛ́ mâi mii kra-dàat thít-chûu {P}', en: "The shower is broken, and there's no toilet paper." },
      { who: 'B', th: 'ขอโทษ{Pb} จะส่งคนไปซ่อม', rom: 'khɔ̌ɔ-thôot {Pb}, jà sòng khon pai sɔ̂m', en: "Sorry. I'll send someone to fix it." },
      { who: 'A', th: 'ห้องเสียงดังไปด้วย ขอเปลี่ยนห้องได้ไหม{Pq}', rom: 'hɔ̂ng sǐang dang pai dûai, khɔ̌ɔ plìan hɔ̂ng dâi mǎi {Pq}', en: 'The room is too noisy as well. Can I change rooms?' },
      { who: 'B', th: 'ได้{Pb} ใจเย็นๆ นะ{Pb}', rom: 'dâi {Pb}, jai yen yen ná {Pb}', en: "Yes. Don't worry, take it easy." },
      { who: 'A', th: 'ขอบคุณมาก{P}', rom: 'khɔ̀ɔp-khun mâak {P}', en: 'Thank you very much.' },
    ],
  },
};
