// One short conversation per unit (keyed by the unit's key in course.js), used by the Pimsleur-style lessons.
//   who: 'A' = the learner (voiced to match the learner's gender), 'B' = the other person (the other voice)
//   Placeholders: {P} {Pq} {I} = A's polite ending / question ending / "I";
//                 {Pb} {Pbq} {Ib} = the same for B (the opposite gender to the learner).
//   en: meaning, shown on screen and used as the role-play prompt for A's lines.
window.DIALOGUES = {
  'greetings': {
    scene: 'You meet someone in your hotel lobby.', you: 'the guest',
    lines: [
      { who: 'B', th: 'สวัสดี{Pb}', rom: 'sa-wàt-dii {Pb}', en: 'Hello.' },
      { who: 'A', th: 'สวัสดี{P}', rom: 'sa-wàt-dii {P}', en: 'Hello.' },
      { who: 'B', th: 'สบายดีไหม{Pbq}', rom: 'sa-baai dii mǎi {Pbq}', en: 'How are you?' },
      { who: 'A', th: 'สบายดี ขอบคุณ{P}', rom: 'sa-baai dii, khɔ̀ɔp-khun {P}', en: "I'm fine, thank you." },
      { who: 'B', th: 'ไม่เป็นไร{Pb}', rom: 'mâi pen rai {Pb}', en: "You're welcome." },
      { who: 'A', th: 'สวัสดี{P}', rom: 'sa-wàt-dii {P}', en: 'Goodbye.' },
    ],
  },
  'getting-by': {
    scene: 'A shopkeeper asks you something, a little too fast.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'คุณชื่ออะไร{Pbq}', rom: 'khun chûue a-rai {Pbq}', en: "What's your name?" },
      { who: 'A', th: 'ไม่เข้าใจ{P}', rom: 'mâi khâo-jai {P}', en: "I don't understand." },
      { who: 'A', th: 'พูดช้าๆ หน่อย{P}', rom: 'phûut cháa-cháa nɔ̀i {P}', en: 'Please speak slowly.' },
      { who: 'B', th: 'คุณ... ชื่อ... อะไร{Pbq}', rom: 'khun... chûue... a-rai {Pbq}', en: 'What... is your... name?' },
      { who: 'A', th: 'เข้าใจ{P}', rom: 'khâo-jai {P}', en: 'I understand.' },
      { who: 'A', th: 'ยินดีที่ได้รู้จัก{P}', rom: 'yin-dii thîi dâi rúu-jàk {P}', en: 'Nice to meet you.' },
      { who: 'B', th: 'ยินดีที่ได้รู้จัก{Pb}', rom: 'yin-dii thîi dâi rúu-jàk {Pb}', en: 'Nice to meet you too.' },
    ],
  },
  'food-shopping': {
    scene: 'You are eating at a small restaurant.', you: 'the customer',
    lines: [
      { who: 'A', th: 'ขอน้ำเปล่า{P}', rom: 'khɔ̌ɔ náam plàao {P}', en: 'May I have plain water, please?' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'Sure.' },
      { who: 'A', th: 'อร่อยมาก{P}', rom: 'a-rɔ̀i mâak {P}', en: "It's very delicious." },
      { who: 'B', th: 'ขอบคุณ{Pb}', rom: 'khɔ̀ɔp-khun {Pb}', en: 'Thank you.' },
      { who: 'A', th: 'ห้องน้ำอยู่ที่ไหน{Pq}', rom: 'hɔ̂ng-náam yùu thîi-nǎi {Pq}', en: 'Where is the toilet?' },
      { who: 'B', th: 'ตรงนั้น{Pb}', rom: 'trong nán {Pb}', en: 'Over there.' },
      { who: 'A', th: 'เช็คบิลด้วย{P}', rom: 'chék bin dûai {P}', en: 'The bill, please.' },
      { who: 'B', th: 'หนึ่งร้อยบาท{Pb}', rom: 'nùeng rɔ́ɔi bàat {Pb}', en: 'One hundred baht.' },
    ],
  },
  'numbers': {
    scene: 'Buying fruit at a market stall.', you: 'the shopper',
    lines: [
      { who: 'B', th: 'สวัสดี{Pb}', rom: 'sa-wàt-dii {Pb}', en: 'Hello.' },
      { who: 'A', th: 'อันนี้เท่าไร{Pq}', rom: 'an níi thâo-rài {Pq}', en: 'How much is this one?' },
      { who: 'B', th: 'ยี่สิบบาท{Pb}', rom: 'yîi-sìp bàat {Pb}', en: 'Twenty baht.' },
      { who: 'A', th: 'ยี่สิบบาท', rom: 'yîi-sìp bàat', en: 'Twenty baht?' },
      { who: 'B', th: 'ใช่{Pb}', rom: 'châi {Pb}', en: 'Yes.' },
      { who: 'A', th: 'หนึ่งร้อยบาท', rom: 'nùeng rɔ́ɔi bàat', en: '(handing over a note) One hundred baht.' },
      { who: 'B', th: 'ขอบคุณ{Pb}', rom: 'khɔ̀ɔp-khun {Pb}', en: 'Thank you.' },
    ],
  },
  'money': {
    scene: 'Bargaining for a shirt at a night market.', you: 'the shopper',
    lines: [
      { who: 'A', th: 'อันนี้เท่าไร{Pq}', rom: 'an níi thâo-rài {Pq}', en: 'How much is this one?' },
      { who: 'B', th: 'ห้าร้อยบาท{Pb}', rom: 'hâa rɔ́ɔi bàat {Pb}', en: 'Five hundred baht.' },
      { who: 'A', th: 'แพงมาก ลดหน่อยได้ไหม{Pq}', rom: 'phɛɛng mâak, lót nɔ̀i dâi mǎi {Pq}', en: 'Very expensive. Can you lower the price a bit?' },
      { who: 'B', th: 'สี่ร้อยบาท{Pb}', rom: 'sìi rɔ́ɔi bàat {Pb}', en: 'Four hundred baht.' },
      { who: 'A', th: 'มีถูกกว่านี้ไหม{Pq}', rom: 'mii thùuk kwàa níi mǎi {Pq}', en: 'Do you have a cheaper one?' },
      { who: 'B', th: 'อันนี้สองร้อยบาท{Pb}', rom: 'an níi sɔ̌ɔng rɔ́ɔi bàat {Pb}', en: 'This one is two hundred baht.' },
      { who: 'A', th: 'ตกลง เอา{P}', rom: 'tòk-long, ao {P}', en: "OK, deal. I'll take it." },
      { who: 'B', th: 'ขอบคุณ{Pb}', rom: 'khɔ̀ɔp-khun {Pb}', en: 'Thank you.' },
    ],
  },
  'want-have-can': {
    scene: 'A Thai friend checks in on you at lunchtime.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'กินข้าวหรือยัง{Pbq}', rom: 'kin khâao rǔue yang {Pbq}', en: 'Have you eaten yet?' },
      { who: 'A', th: 'ยัง{P}', rom: 'yang {P}', en: 'Not yet.' },
      { who: 'B', th: 'อยากกินอะไร{Pbq}', rom: 'yàak kin a-rai {Pbq}', en: 'What do you want to eat?' },
      { who: 'A', th: '{I}ชอบอาหารไทย{P}', rom: '{I} chɔ̂ɔp aa-hǎan thai {P}', en: 'I like Thai food.' },
      { who: 'B', th: 'ไปกินข้าวกัน{Pb}', rom: 'pai kin khâao kan {Pb}', en: "Let's go eat." },
      { who: 'A', th: 'ได้{P}', rom: 'dâi {P}', en: 'OK, sure.' },
    ],
  },
  'getting-around': {
    scene: 'Asking a passer-by the way back to your hotel.', you: 'the visitor',
    lines: [
      { who: 'A', th: 'ขอโทษ{P}', rom: 'khɔ̌ɔ-thôot {P}', en: 'Excuse me.' },
      { who: 'A', th: 'อยากไปโรงแรม{P}', rom: 'yàak pai roong-rɛɛm {P}', en: 'I want to go to the hotel.' },
      { who: 'B', th: 'ไม่ไกล{Pb}', rom: 'mâi klai {Pb}', en: "It's not far." },
      { who: 'B', th: 'ตรงไป แล้วเลี้ยวขวา{Pb}', rom: 'trong pai, lɛ́ɛo líao khwǎa {Pb}', en: 'Go straight, then turn right.' },
      { who: 'A', th: 'ตรงไป เลี้ยวขวา', rom: 'trong pai, líao khwǎa', en: 'Straight, then right?' },
      { who: 'B', th: 'ใช่{Pb}', rom: 'châi {Pb}', en: 'Yes.' },
      { who: 'A', th: 'ขอบคุณ{P}', rom: 'khɔ̀ɔp-khun {P}', en: 'Thank you.' },
    ],
  },
  'transport': {
    scene: 'Taking a taxi to the airport.', you: 'the passenger',
    lines: [
      { who: 'A', th: 'ไปสนามบิน{P}', rom: 'pai sa-nǎam-bin {P}', en: 'To the airport, please.' },
      { who: 'A', th: 'เปิดมิเตอร์ด้วย{P}', rom: 'pòet mí-tôe dûai {P}', en: 'Please use the meter.' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'OK.' },
      { who: 'A', th: 'นานเท่าไร{Pq}', rom: 'naan thâo-rài {Pq}', en: 'How long does it take?' },
      { who: 'B', th: 'รถติด หนึ่งชั่วโมง{Pb}', rom: 'rót tìt, nùeng chûa-moong {Pb}', en: 'Traffic is bad. One hour.' },
      { who: 'B', th: 'ถึงแล้ว{Pb}', rom: 'thǔeng lɛ́ɛo {Pb}', en: "We've arrived." },
      { who: 'A', th: 'จอดตรงนี้{P}', rom: 'jɔ̀ɔt trong níi {P}', en: 'Stop here, please.' },
      { who: 'A', th: 'ไม่ต้องทอน{P}', rom: 'mâi tɔ̂ng thɔɔn {P}', en: 'Keep the change.' },
      { who: 'B', th: 'ขอบคุณ{Pb} ตุ๊กตุ๊กจอดตรงนั้น', rom: 'khɔ̀ɔp-khun {Pb}, túk-túk jɔ̀ɔt trong nán', en: 'Thank you. The tuk-tuks wait over there.' },
    ],
  },
  'hotel': {
    scene: 'Checking in at your hotel.', you: 'the guest',
    lines: [
      { who: 'B', th: 'สวัสดี{Pb}', rom: 'sa-wàt-dii {Pb}', en: 'Hello.' },
      { who: 'A', th: '{I}จองไว้แล้ว{P}', rom: '{I} jɔɔng wái lɛ́ɛo {P}', en: 'I have a reservation.' },
      { who: 'B', th: 'สองคืน ใช่ไหม{Pbq}', rom: 'sɔ̌ɔng khuen, châi mǎi {Pbq}', en: 'Two nights, right?' },
      { who: 'A', th: 'ใช่{P}', rom: 'châi {P}', en: 'Yes.' },
      { who: 'A', th: 'รหัสไวไฟคืออะไร{Pq}', rom: 'ra-hàt wai-fai khue a-rai {Pq}', en: "What's the Wi-Fi password?" },
      { who: 'B', th: 'หนึ่ง สอง สาม สี่{Pb}', rom: 'nùeng, sɔ̌ɔng, sǎam, sìi {Pb}', en: 'One, two, three, four.' },
      { who: 'A', th: 'อาหารเช้ากี่โมง{Pq}', rom: 'aa-hǎan cháao kìi moong {Pq}', en: 'What time is breakfast?' },
      { who: 'B', th: 'เจ็ดโมง{Pb}', rom: 'jèt moong {Pb}', en: "Seven o'clock." },
    ],
  },
  'ordering-food': {
    scene: 'Ordering lunch at a restaurant.', you: 'the customer',
    lines: [
      { who: 'A', th: 'ขอเมนูหน่อย{P}', rom: 'khɔ̌ɔ mee-nuu nɔ̀i {P}', en: 'The menu, please.' },
      { who: 'A', th: 'เอาข้าวผัดไก่{P}', rom: 'ao khâao phàt kài {P}', en: "I'd like chicken fried rice." },
      { who: 'B', th: 'เผ็ดไหม{Pbq}', rom: 'phèt mǎi {Pbq}', en: 'Spicy?' },
      { who: 'A', th: 'ไม่ใส่พริก{P}', rom: 'mâi sài phrík {P}', en: 'No chili, please.' },
      { who: 'B', th: 'ดื่มอะไร{Pbq}', rom: 'dùuem a-rai {Pbq}', en: 'Anything to drink?' },
      { who: 'A', th: 'กาแฟเย็น หวานน้อย{P}', rom: 'kaa-fɛɛ yen, wǎan nɔ́ɔi {P}', en: 'Iced coffee, not too sweet.' },
      { who: 'A', th: 'อิ่มแล้ว เช็คบิลด้วย{P}', rom: 'ìm lɛ́ɛo, chék bin dûai {P}', en: "I'm full. The bill, please." },
    ],
  },
  'about-you': {
    scene: 'Chatting with someone at a café.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'คุณมาจากไหน{Pbq}', rom: 'khun maa jàak nǎi {Pbq}', en: 'Where are you from?' },
      { who: 'A', th: '{I}มาจากอเมริกา{P}', rom: '{I} maa jàak a-mee-ri-kaa {P}', en: "I'm from America." },
      { who: 'B', th: 'พูดภาษาไทยได้ไหม{Pbq}', rom: 'phûut phaa-sǎa thai dâi mǎi {Pbq}', en: 'Can you speak Thai?' },
      { who: 'A', th: '{I}พูดภาษาไทยได้นิดหน่อย{P}', rom: '{I} phûut phaa-sǎa thai dâi nít-nɔ̀i {P}', en: 'I can speak a little Thai.' },
      { who: 'B', th: 'ชอบประเทศไทยไหม{Pbq}', rom: 'chɔ̂ɔp pra-thêet thai mǎi {Pbq}', en: 'Do you like Thailand?' },
      { who: 'A', th: '{I}ชอบประเทศไทย{P}', rom: '{I} chɔ̂ɔp pra-thêet thai {P}', en: 'I like Thailand.' },
    ],
  },
  'time-feelings': {
    scene: 'A hot afternoon with a new friend.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'วันนี้ร้อนมาก{Pb}', rom: 'wan-níi rɔ́ɔn mâak {Pb}', en: "It's very hot today." },
      { who: 'A', th: 'ใช่ ร้อนมาก{P}', rom: 'châi, rɔ́ɔn mâak {P}', en: 'Yes, very hot.' },
      { who: 'B', th: 'หิวข้าวไหม{Pbq}', rom: 'hǐu khâao mǎi {Pbq}', en: 'Are you hungry?' },
      { who: 'A', th: 'หิวข้าว แต่เหนื่อย{P}', rom: 'hǐu khâao, tɛ̀ɛ nùeai {P}', en: "I'm hungry, but tired." },
      { who: 'A', th: 'กี่โมงแล้ว{Pq}', rom: 'kìi moong lɛ́ɛo {Pq}', en: 'What time is it?' },
      { who: 'B', th: 'ห้าโมงเย็น{Pb}', rom: 'hâa moong yen {Pb}', en: "Five in the evening." },
      { who: 'A', th: 'เจอกันพรุ่งนี้{P}', rom: 'joe kan phrûng-níi {P}', en: 'See you tomorrow.' },
      { who: 'B', th: 'เจอกันพรุ่งนี้{Pb}', rom: 'joe kan phrûng-níi {Pb}', en: 'See you tomorrow.' },
    ],
  },
  'health': {
    scene: "You're not feeling well and ask the hotel staff for help.", you: 'the guest',
    lines: [
      { who: 'A', th: 'ไม่สบาย{P}', rom: 'mâi sa-baai {P}', en: "I'm sick." },
      { who: 'B', th: 'เป็นอะไร{Pbq}', rom: 'pen a-rai {Pbq}', en: "What's wrong?" },
      { who: 'A', th: 'ปวดหัว เป็นไข้{P}', rom: 'pùat hǔa, pen khâi {P}', en: 'I have a headache and a fever.' },
      { who: 'A', th: 'ท้องเสียด้วย{P}', rom: 'thɔ́ɔng sǐa dûai {P}', en: 'And I have diarrhea.' },
      { who: 'B', th: 'ไปโรงพยาบาลไหม{Pbq}', rom: 'pai roong-pha-yaa-baan mǎi {Pbq}', en: 'Do you want to go to the hospital?' },
      { who: 'A', th: 'ร้านขายยาอยู่ที่ไหน{Pq}', rom: 'ráan khǎai yaa yùu thîi-nǎi {Pq}', en: 'Where is a pharmacy?' },
      { who: 'B', th: 'อยู่ใกล้ๆ นี้{Pb}', rom: 'yùu klâi-klâi níi {Pb}', en: "It's near here." },
      { who: 'A', th: 'ขอบคุณ{P}', rom: 'khɔ̀ɔp-khun {P}', en: 'Thank you.' },
    ],
  },
  'small-talk': {
    scene: 'A friendly vendor starts chatting with you.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'มาเที่ยวเหรอ{Pbq}', rom: 'maa thîao rǒe {Pbq}', en: 'Here on holiday?' },
      { who: 'A', th: 'มาเที่ยว{P}', rom: 'maa thîao {P}', en: "I'm here on holiday." },
      { who: 'A', th: 'มาเมืองไทยครั้งแรก{P}', rom: 'maa mueang thai khráng rɛ̂ɛk {P}', en: 'This is my first time in Thailand.' },
      { who: 'B', th: 'พูดไทยเก่ง{Pb}', rom: 'phûut thai kèng {Pb}', en: 'You speak Thai well.' },
      { who: 'A', th: 'ยังไม่เก่ง{P}', rom: 'yang mâi kèng {P}', en: "Not really, I'm not good yet." },
      { who: 'B', th: 'ชอบไหม{Pbq}', rom: 'chɔ̂ɔp mǎi {Pbq}', en: 'Do you like it?' },
      { who: 'A', th: 'ชอบมาก สนุกมาก{P}', rom: 'chɔ̂ɔp mâak, sa-nùk mâak {P}', en: "I like it a lot. It's a lot of fun." },
    ],
  },
  'question-words': {
    scene: 'A friend tells you about their plans.', you: 'the friend',
    lines: [
      { who: 'B', th: 'พรุ่งนี้จะไปตลาด{Pb}', rom: 'phrûng-níi jà pai ta-làat {Pb}', en: "Tomorrow I'm going to the market." },
      { who: 'A', th: 'ไปกับใคร{Pq}', rom: 'pai kàp khrai {Pq}', en: 'Who are you going with?' },
      { who: 'B', th: 'ไปกับเพื่อน{Pb}', rom: 'pai kàp phûean {Pb}', en: 'With a friend.' },
      { who: 'A', th: 'ไปยังไง{Pq}', rom: 'pai yang-ngai {Pq}', en: 'How are you getting there?' },
      { who: 'B', th: 'นั่งรถไฟฟ้า{Pb}', rom: 'nâng rót-fai-fáa {Pb}', en: 'By skytrain.' },
      { who: 'A', th: 'จะไปเมื่อไร{Pq}', rom: 'jà pai mûea-rài {Pq}', en: 'When are you going?' },
      { who: 'B', th: 'ตอนเช้า{Pb}', rom: 'tɔɔn cháao {Pb}', en: 'In the morning.' },
    ],
  },
  'verbs': {
    scene: 'Shopping with a Thai friend.', you: 'the shopper',
    lines: [
      { who: 'A', th: 'รอ{I}ด้วย{P}', rom: 'rɔɔ {I} dûai {P}', en: 'Wait for me, please.' },
      { who: 'B', th: 'ได้ จะซื้ออะไร{Pbq}', rom: 'dâi, jà súue a-rai {Pbq}', en: 'Sure. What are you going to buy?' },
      { who: 'A', th: 'อยากซื้ออันนี้{P}', rom: 'yàak súue an-níi {P}', en: 'I want to buy this one.' },
      { who: 'B', th: 'ดูก่อน{Pb}', rom: 'duu kɔ̀ɔn {Pb}', en: 'Take a look first.' },
      { who: 'A', th: 'ไม่รู้ คิดก่อน{P}', rom: 'mâi rúu, khít kɔ̀ɔn {P}', en: "I don't know. Let me think first." },
      { who: 'B', th: 'ได้ ไม่เป็นไร{Pb}', rom: 'dâi, mâi pen rai {Pb}', en: 'Sure, no problem.' },
    ],
  },
  'days-times': {
    scene: 'Making weekend plans.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'วันนี้วันอะไร{Pbq}', rom: 'wan-níi wan a-rai {Pbq}', en: 'What day is it today?' },
      { who: 'A', th: 'วันศุกร์{P}', rom: 'wan sùk {P}', en: 'Friday.' },
      { who: 'B', th: 'พรุ่งนี้ว่างไหม{Pbq}', rom: 'phrûng-níi wâang mǎi {Pbq}', en: 'Are you free tomorrow?' },
      { who: 'A', th: 'ตอนเย็นว่าง{P}', rom: 'tɔɔn yen wâang {P}', en: "I'm free in the evening." },
      { who: 'B', th: 'ไปตลาดกลางคืนไหม{Pbq}', rom: 'pai ta-làat klaang-khuen mǎi {Pbq}', en: 'Shall we go to the night market?' },
      { who: 'A', th: 'ได้ เจอกันพรุ่งนี้{P}', rom: 'dâi, joe kan phrûng-níi {P}', en: 'Sure. See you tomorrow.' },
    ],
  },
  'places': {
    scene: 'Looking for a convenience store.', you: 'the visitor',
    lines: [
      { who: 'A', th: 'แถวนี้มีเซเว่นไหม{Pq}', rom: 'thɛ̌o níi mii see-wên mǎi {Pq}', en: 'Is there a 7-Eleven around here?' },
      { who: 'B', th: 'มี{Pb} ตรงไปแล้วเลี้ยวซ้าย', rom: 'mii {Pb}, trong pai lɛ́ɛo líao sáai', en: 'Yes. Go straight, then turn left.' },
      { who: 'A', th: 'เดินไปได้ไหม{Pq}', rom: 'doen pai dâi mǎi {Pq}', en: 'Can I walk there?' },
      { who: 'B', th: 'ได้{Pb} ไม่ไกล', rom: 'dâi {Pb}, mâi klai', en: "Yes, it's not far." },
      { who: 'A', th: 'อยู่ทางซ้าย{Pq}', rom: 'yùu thaang sáai {Pq}', en: "It's on the left?" },
      { who: 'B', th: 'ใช่{Pb}', rom: 'châi {Pb}', en: 'Yes.' },
      { who: 'A', th: 'ขอบคุณ{P}', rom: 'khɔ̀ɔp-khun {P}', en: 'Thank you.' },
    ],
  },
  'street-food': {
    scene: 'Ordering at a street food stall.', you: 'the customer',
    lines: [
      { who: 'A', th: 'ที่นี่อะไรอร่อย{Pq}', rom: 'thîi-nîi a-rai a-rɔ̀i {Pq}', en: "What's good here?" },
      { who: 'B', th: 'ผัดกะเพราหมู{Pb}', rom: 'phàt ka-phrao mǔu {Pb}', en: 'Stir-fried basil pork.' },
      { who: 'A', th: 'เอาหนึ่งที่ ใส่ไข่ดาว{P}', rom: 'ao nùeng thîi, sài khài-daao {P}', en: 'One serving, with a fried egg.' },
      { who: 'B', th: 'เผ็ดไหม{Pbq}', rom: 'phèt mǎi {Pbq}', en: 'Spicy?' },
      { who: 'A', th: 'เผ็ดนิดหน่อย{P}', rom: 'phèt nít-nɔ̀i {P}', en: 'A little spicy.' },
      { who: 'A', th: 'แล้วก็ข้าวเหนียวมะม่วง{P}', rom: 'lɛ́ɛo kɔ̂ɔ khâao-nǐao ma-mûang {P}', en: 'And mango sticky rice too.' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'Sure.' },
    ],
  },
  'clothes': {
    scene: 'Trying on a shirt at a shop.', you: 'the shopper',
    lines: [
      { who: 'A', th: 'ลองได้ไหม{Pq}', rom: 'lɔɔng dâi mǎi {Pq}', en: 'Can I try it on?' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'Sure.' },
      { who: 'A', th: 'เล็กไป มีใหญ่กว่านี้ไหม{Pq}', rom: 'lék pai, mii yài kwàa níi mǎi {Pq}', en: "It's too small. Do you have a bigger one?" },
      { who: 'B', th: 'มี{Pb} เอาสีอะไร{Pbq}', rom: 'mii {Pb}, ao sǐi a-rai {Pbq}', en: 'Yes. Which color would you like?' },
      { who: 'A', th: 'สีดำ{P}', rom: 'sǐi dam {P}', en: 'Black.' },
      { who: 'B', th: 'สีดำไม่มี มีสีขาว{Pb}', rom: 'sǐi dam mâi mii, mii sǐi khǎao {Pb}', en: "There's no black. There's white." },
      { who: 'A', th: 'โอเค เอาสีขาว{P}', rom: 'oo-khee, ao sǐi khǎao {P}', en: "OK, I'll take white." },
    ],
  },
  'massage': {
    scene: 'Booking a Thai massage.', you: 'the customer',
    lines: [
      { who: 'A', th: 'นวดไทย ชั่วโมงละเท่าไร{Pq}', rom: 'nûat thai, chûa-moong lá thâo-rài {Pq}', en: 'How much is a Thai massage per hour?' },
      { who: 'B', th: 'สามร้อยบาท{Pb}', rom: 'sǎam rɔ́ɔi bàat {Pb}', en: 'Three hundred baht.' },
      { who: 'A', th: 'เอาหนึ่งชั่วโมง{P}', rom: 'ao nùeng chûa-moong {P}', en: "I'll have one hour." },
      { who: 'B', th: 'แรงไหม{Pbq}', rom: 'rɛɛng mǎi {Pbq}', en: 'Is it too strong?' },
      { who: 'A', th: 'เบาๆ หน่อย{P}', rom: 'bao-bao nɔ̀i {P}', en: 'Softer, please.' },
      { who: 'A', th: 'ปวดหลัง{P}', rom: 'pùat lǎng {P}', en: 'My back hurts.' },
      { who: 'B', th: 'โอเค{Pb}', rom: 'oo-khee {Pb}', en: 'OK.' },
      { who: 'A', th: 'สบายมาก{P}', rom: 'sa-baai mâak {P}', en: 'That feels really good.' },
    ],
  },
  'beaches': {
    scene: 'Buying a boat ticket to an island.', you: 'the traveler',
    lines: [
      { who: 'A', th: 'ตั๋วเรือไปเกาะเท่าไร{Pq}', rom: 'tǔa ruea pai kɔ̀ thâo-rài {Pq}', en: 'How much is a boat ticket to the island?' },
      { who: 'B', th: 'สองร้อยบาท{Pb}', rom: 'sɔ̌ɔng rɔ́ɔi bàat {Pb}', en: 'Two hundred baht.' },
      { who: 'A', th: 'เรือออกกี่โมง{Pq}', rom: 'ruea ɔ̀ɔk kìi moong {Pq}', en: 'What time does the boat leave?' },
      { who: 'B', th: 'เก้าโมง{Pb}', rom: 'kâao moong {Pb}', en: "Nine o'clock." },
      { who: 'A', th: 'มีเสื้อชูชีพไหม{Pq}', rom: 'mii sûea chuu-chîip mǎi {Pq}', en: 'Are there life jackets?' },
      { who: 'B', th: 'มี{Pb} วันนี้คลื่นใหญ่', rom: 'mii {Pb}, wan-níi khlûen yài', en: 'Yes. The waves are big today.' },
      { who: 'A', th: 'ว่ายน้ำได้ไหม{Pq}', rom: 'wâai-náam dâi mǎi {Pq}', en: 'Can I swim?' },
      { who: 'B', th: 'ไม่ได้ อันตราย{Pb}', rom: 'mâi dâi, an-ta-raai {Pb}', en: "No, it's dangerous." },
    ],
  },
  'temples': {
    scene: 'Visiting a temple.', you: 'the visitor',
    lines: [
      { who: 'A', th: 'เข้าไปได้ไหม{Pq}', rom: 'khâo pai dâi mǎi {Pq}', en: 'May I go in?' },
      { who: 'B', th: 'ได้ ต้องถอดรองเท้า{Pb}', rom: 'dâi, tɔ̂ng thɔ̀ɔt rɔɔng-tháao {Pb}', en: 'Yes, but you need to take off your shoes.' },
      { who: 'A', th: 'แต่งตัวแบบนี้ได้ไหม{Pq}', rom: 'tɛ̀ng-tua bɛ̀ɛp níi dâi mǎi {Pq}', en: 'Is this outfit OK?' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: "It's fine." },
      { who: 'A', th: 'วัดนี้สวยมาก{P}', rom: 'wát níi sǔai mâak {P}', en: 'This temple is very beautiful.' },
      { who: 'B', th: 'มาไหว้พระเหรอ{Pbq}', rom: 'maa wâi phrá rǒe {Pbq}', en: 'Did you come to pay respects?' },
      { who: 'A', th: 'ใช่ มาทำบุญ{P}', rom: 'châi, maa tham-bun {P}', en: 'Yes, I came to make merit.' },
    ],
  },
  'phone': {
    scene: 'At a phone shop at the airport.', you: 'the traveler',
    lines: [
      { who: 'A', th: 'อยากซื้อซิมการ์ด{P}', rom: 'yàak súue sim-káat {P}', en: 'I want to buy a SIM card.' },
      { who: 'B', th: 'กี่วัน{Pbq}', rom: 'kìi wan {Pbq}', en: 'For how many days?' },
      { who: 'A', th: 'สองอาทิตย์{P}', rom: 'sɔ̌ɔng aa-thít {P}', en: 'Two weeks.' },
      { who: 'B', th: 'ห้าร้อยบาท{Pb}', rom: 'hâa rɔ́ɔi bàat {Pb}', en: 'Five hundred baht.' },
      { who: 'A', th: 'แบตหมด ชาร์จโทรศัพท์ได้ไหม{Pq}', rom: 'bɛ̀t mòt, cháat thoo-ra-sàp dâi mǎi {Pq}', en: 'My battery is dead. Can I charge my phone?' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'Sure.' },
      { who: 'A', th: 'มีไวไฟไหม{Pq}', rom: 'mii wai-fai mǎi {Pq}', en: 'Is there Wi-Fi?' },
      { who: 'B', th: 'มี{Pb}', rom: 'mii {Pb}', en: 'Yes, there is.' },
    ],
  },
  'friends': {
    scene: 'Getting to know someone at a party.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'อยู่ที่ไหน{Pbq}', rom: 'yùu thîi-nǎi {Pbq}', en: 'Where do you live?' },
      { who: 'A', th: '{I}อยู่อเมริกา{P}', rom: '{I} yùu a-mee-ri-kaa {P}', en: 'I live in America.' },
      { who: 'B', th: 'แต่งงานหรือยัง{Pbq}', rom: 'tɛ̀ng-ngaan rǔue yang {Pbq}', en: 'Are you married?' },
      { who: 'A', th: 'แต่งงานแล้ว{P}', rom: 'tɛ̀ng-ngaan lɛ́ɛo {P}', en: "I'm married." },
      { who: 'B', th: 'ขอไลน์หน่อยได้ไหม{Pbq}', rom: 'khɔ̌ɔ lai nɔ̀i dâi mǎi {Pbq}', en: 'Can I have your LINE?' },
      { who: 'A', th: 'ได้{P}', rom: 'dâi {P}', en: 'Sure.' },
      { who: 'B', th: 'ไปกินข้าวด้วยกันไหม{Pbq}', rom: 'pai kin khâao dûai kan mǎi {Pbq}', en: 'Shall we go eat together?' },
      { who: 'A', th: 'ได้ ใจดีมาก{P}', rom: 'dâi, jai-dii mâak {P}', en: "Sure. You're very kind." },
    ],
  },
  'reactions': {
    scene: 'A friend shares some news.', you: 'the friend',
    lines: [
      { who: 'B', th: '{Ib}ได้งานใหม่{Pb}', rom: '{Ib} dâi ngaan mài {Pb}', en: 'I got a new job.' },
      { who: 'A', th: 'จริงเหรอ ยินดีด้วย{P}', rom: 'jing rǒe, yin-dii dûai {P}', en: 'Really? Congratulations.' },
      { who: 'B', th: 'แต่ต้องย้ายไปเชียงใหม่{Pb}', rom: 'tɛ̀ɛ tɔ̂ng yáai pai chiang-mài {Pb}', en: 'But I have to move to Chiang Mai.' },
      { who: 'A', th: 'น่าเสียดาย คิดถึง{P}', rom: 'nâa sǐa-daai, khít-thǔeng {P}', en: "What a pity. I'll miss you." },
      { who: 'B', th: 'ใจเย็นๆ ติดต่อกันนะ{Pb}', rom: 'jai yen yen, tìt-tɔ̀ɔ kan ná {Pb}', en: "Take it easy. Let's keep in touch." },
      { who: 'A', th: 'ได้เลย{P}', rom: 'dâi loei {P}', en: 'Sure, of course.' },
    ],
  },
  'family': {
    scene: "A friend introduces you to their family.", you: 'the visitor',
    lines: [
      { who: 'B', th: 'นี่ครอบครัว{Ib}{Pb}', rom: 'nîi khrɔ̂ɔp-khrua {Ib} {Pb}', en: 'This is my family.' },
      { who: 'A', th: 'ยินดีที่ได้รู้จัก{P}', rom: 'yin-dii thîi dâi rúu-jàk {P}', en: 'Nice to meet you.' },
      { who: 'B', th: 'มีพี่น้องกี่คน{Pbq}', rom: 'mii phîi-nɔ́ɔng kìi khon {Pbq}', en: 'How many brothers and sisters do you have?' },
      { who: 'A', th: 'มีน้องหนึ่งคน{P}', rom: 'mii nɔ́ɔng nùeng khon {P}', en: 'I have one younger sibling.' },
      { who: 'B', th: 'มีลูกไหม{Pbq}', rom: 'mii lûuk mǎi {Pbq}', en: 'Do you have children?' },
      { who: 'A', th: 'มีลูกสองคน{P}', rom: 'mii lûuk sɔ̌ɔng khon {P}', en: 'I have two children.' },
      { who: 'B', th: 'ลูกชายหรือลูกสาว{Pbq}', rom: 'lûuk-chaai rǔue lûuk-sǎao {Pbq}', en: 'Sons or daughters?' },
      { who: 'A', th: 'ลูกชายหนึ่ง ลูกสาวหนึ่ง{P}', rom: 'lûuk-chaai nùeng, lûuk-sǎao nùeng {P}', en: 'One son and one daughter.' },
    ],
  },
  'telling-time': {
    scene: 'Arranging to meet a friend for dinner.', you: 'the friend',
    lines: [
      { who: 'A', th: 'เจอกันกี่โมง{Pq}', rom: 'joe kan kìi moong {Pq}', en: 'What time shall we meet?' },
      { who: 'B', th: 'หนึ่งทุ่ม ได้ไหม{Pbq}', rom: 'nùeng thûm, dâi mǎi {Pbq}', en: 'Seven in the evening, is that OK?' },
      { who: 'A', th: 'หนึ่งทุ่มครึ่งได้ไหม{Pq}', rom: 'nùeng thûm khrûeng dâi mǎi {Pq}', en: 'Could we make it half past seven?' },
      { who: 'B', th: 'ได้{Pb} ร้านปิดสามทุ่ม', rom: 'dâi {Pb}, ráan pìt sǎam thûm', en: 'Sure. The restaurant closes at nine.' },
      { who: 'A', th: 'ตอนนี้กี่โมงแล้ว{Pq}', rom: 'tɔɔn-níi kìi moong lɛ́ɛo {Pq}', en: 'What time is it now?' },
      { who: 'B', th: 'บ่ายสามโมงครึ่ง{Pb}', rom: 'bàai sǎam moong khrûeng {Pb}', en: 'Half past three.' },
      { who: 'A', th: 'โอเค เจอกันหนึ่งทุ่มครึ่ง{P}', rom: 'oo-khee, joe kan nùeng thûm khrûeng {P}', en: 'OK, see you at half past seven.' },
    ],
  },
  'airport': {
    scene: 'Arriving at the airport: immigration, then a missing bag.', you: 'the traveler',
    lines: [
      { who: 'B', th: 'ขอพาสปอร์ต{Pb}', rom: 'khɔ̌ɔ pháat-sa-pɔ̀ɔt {Pb}', en: 'Passport, please.' },
      { who: 'A', th: 'นี่{P}', rom: 'nîi {P}', en: 'Here you are.' },
      { who: 'B', th: 'อยู่กี่วัน{Pbq}', rom: 'yùu kìi wan {Pbq}', en: 'How many days are you staying?' },
      { who: 'A', th: 'อยู่สิบวัน มาเที่ยว{P}', rom: 'yùu sìp wan, maa thîao {P}', en: "Ten days. I'm here on holiday." },
      { who: 'B', th: 'ขอบคุณ{Pb} ทางออกอยู่ทางนั้น', rom: 'khɔ̀ɔp-khun {Pb}, thaang ɔ̀ɔk yùu thaang nán', en: 'Thank you. The exit is that way.' },
      { who: 'A', th: 'ขอโทษ{P} กระเป๋าหาย{P}', rom: 'khɔ̌ɔ-thôot {P}, kra-pǎo hǎai {P}', en: 'Excuse me. My luggage is lost.' },
      { who: 'B', th: 'เที่ยวบินอะไร{Pbq}', rom: 'thîao-bin a-rai {Pbq}', en: 'Which flight?' },
      { who: 'A', th: 'เที่ยวบินจากเชียงใหม่{P}', rom: 'thîao-bin jàak chiang-mài {P}', en: 'The flight from Chiang Mai.' },
    ],
  },
  'comparing': {
    scene: 'Choosing between two bags at a shop.', you: 'the shopper',
    lines: [
      { who: 'A', th: 'อันไหนดีกว่า{Pq}', rom: 'an nǎi dii kwàa {Pq}', en: 'Which one is better?' },
      { who: 'B', th: 'อันนี้ดีกว่า แต่แพงกว่า{Pb}', rom: 'an níi dii kwàa, tɛ̀ɛ phɛɛng kwàa {Pb}', en: 'This one is better, but more expensive.' },
      { who: 'A', th: 'อันนั้นถูกกว่าไหม{Pq}', rom: 'an nán thùuk kwàa mǎi {Pq}', en: 'Is that one cheaper?' },
      { who: 'B', th: 'ถูกกว่า แต่เก่า{Pb}', rom: 'thùuk kwàa, tɛ̀ɛ kào {Pb}', en: "It's cheaper, but old." },
      { who: 'A', th: 'เอาอันใหม่ อันนี้ดีที่สุด{P}', rom: 'ao an mài, an níi dii thîi-sùt {P}', en: "I'll take the new one. This is the best." },
      { who: 'B', th: 'ใช่{Pb} ดีที่สุด', rom: 'châi {Pb}, dii thîi-sùt', en: 'Yes, the best.' },
    ],
  },
  'weather': {
    scene: 'Planning a day out during the rainy season.', you: 'the visitor',
    lines: [
      { who: 'A', th: 'วันนี้อากาศเป็นยังไง{Pq}', rom: 'wan-níi aa-kàat pen yang-ngai {Pq}', en: "How's the weather today?" },
      { who: 'B', th: 'ตอนเช้าแดดออก แต่ตอนเย็นฝนจะตก{Pb}', rom: 'tɔɔn cháao dɛ̀ɛt ɔ̀ɔk, tɛ̀ɛ tɔɔn yen fǒn jà tòk {Pb}', en: "Sunny in the morning, but it's going to rain in the evening." },
      { who: 'A', th: 'หน้าฝนเหรอ{Pq}', rom: 'nâa fǒn rǒe {Pq}', en: "Is it the rainy season?" },
      { who: 'B', th: 'ใช่{Pb} ร้อนและชื้นมาก', rom: 'châi {Pb}, rɔ́ɔn lɛ́ chúuen mâak', en: "Yes. It's very hot and humid." },
      { who: 'A', th: 'มีร่มไหม{Pq}', rom: 'mii rôm mǎi {Pq}', en: 'Do you have an umbrella?' },
      { who: 'B', th: 'มี{Pb} เอาไปด้วย', rom: 'mii {Pb}, ao pai dûai', en: 'Yes. Take it with you.' },
      { who: 'A', th: 'ถ้าฝนตก จะอยู่โรงแรม{P}', rom: 'thâa fǒn tòk, jà yùu roong-rɛɛm {P}', en: "If it rains, I'll stay at the hotel." },
      { who: 'B', th: 'สบายๆ{Pb} หน้าหนาวอากาศดีกว่า', rom: 'sa-baai sa-baai {Pb}, nâa nǎao aa-kàat dii kwàa', en: 'No stress. The weather is better in the cool season.' },
    ],
  },
  'faith': {
    scene: 'Talking with a volunteer at a meditation temple.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'นับถือศาสนาอะไร{Pbq}', rom: 'náp-thǔue sàat-sa-nǎa a-rai {Pbq}', en: 'What religion are you?' },
      { who: 'A', th: '{I}เป็นคริสต์ แต่ชอบนั่งสมาธิ{P}', rom: '{I} pen khrít, tɛ̀ɛ chɔ̂ɔp nâng sa-maa-thí {P}', en: "I'm Christian, but I like to meditate." },
      { who: 'B', th: 'ดีมาก{Pb} ใจสงบ', rom: 'dii mâak {Pb}, jai sa-ngòp', en: 'Very good. A calm mind.' },
      { who: 'A', th: 'นั่งสมาธิที่นี่ได้ไหม{Pq}', rom: 'nâng sa-maa-thí thîi-nîi dâi mǎi {Pq}', en: 'Can I meditate here?' },
      { who: 'B', th: 'ได้{Pb} ตอนเย็นพระสวดมนต์', rom: 'dâi {Pb}, tɔɔn yen phrá sùat mon', en: 'Yes. The monks chant in the evening.' },
      { who: 'A', th: '{I}นั่งสมาธิทุกเช้า{P}', rom: '{I} nâng sa-maa-thí thúk cháao {P}', en: 'I meditate every morning.' },
      { who: 'B', th: 'คนไทยเคารพทุกศาสนา{Pb}', rom: 'khon thai khao-róp thúk sàat-sa-nǎa {Pb}', en: 'Thai people respect every religion.' },
      { who: 'A', th: 'ขอบคุณ{P}', rom: 'khɔ̀ɔp-khun {P}', en: 'Thank you.' },
    ],
  },
  'already': {
    scene: 'A friend calls while you are on your way to meet them.', you: 'the friend',
    lines: [
      { who: 'B', th: 'ถึงหรือยัง{Pbq}', rom: 'thǔeng rǔue yang {Pbq}', en: 'Have you arrived yet?' },
      { who: 'A', th: 'ยัง{P} เพิ่งออกจากบ้าน', rom: 'yang {P}, phôeng ɔ̀ɔk jàak bâan', en: "Not yet. I've just left home." },
      { who: 'B', th: 'กินข้าวหรือยัง{Pbq}', rom: 'kin khâao rǔue yang {Pbq}', en: 'Have you eaten yet?' },
      { who: 'A', th: 'ยังไม่ได้กินข้าว หิวมาก{P}', rom: 'yang mâi dâi kin khâao, hǐu mâak {P}', en: "I haven't eaten yet. I'm really hungry." },
      { who: 'B', th: '{Ib}ซื้อตั๋วหนังแล้ว{Pb}', rom: '{Ib} súue tǔa nǎng lɛ́ɛo {Pb}', en: "I've already bought the movie tickets." },
      { who: 'A', th: 'ขอบคุณ{P} หนังเริ่มกี่โมง{Pq}', rom: 'khɔ̀ɔp-khun {P}, nǎng rôem kìi moong {Pq}', en: 'Thanks. What time does the movie start?' },
      { who: 'B', th: 'หนึ่งทุ่มครึ่ง{Pb} ใกล้แล้ว', rom: 'nùeng thûm khrûeng {Pb}, klâi lɛ́ɛo', en: "Half past seven. It's nearly time." },
      { who: 'A', th: 'อีกสิบนาทีถึง{P}', rom: 'ìik sìp naa-thii thǔeng {P}', en: "I'll be there in ten minutes." },
      { who: 'B', th: 'โอเค{Pb} {Ib}รออยู่ข้างหน้า', rom: 'oo-khee {Pb}, {Ib} rɔɔ yùu khâang-nâa', en: "OK. I'm waiting out front." },
      { who: 'A', th: 'ถึงแล้ว{P} อยู่ไหน{Pq}', rom: 'thǔeng lɛ́ɛo {P}, yùu nǎi {Pq}', en: "I'm here. Where are you?" },
    ],
  },
  'future': {
    scene: 'Chatting with a colleague on a Friday afternoon.', you: 'the colleague',
    lines: [
      { who: 'B', th: 'พรุ่งนี้จะทำอะไร{Pbq}', rom: 'phrûng-níi jà tham a-rai {Pbq}', en: 'What are you doing tomorrow?' },
      { who: 'A', th: 'พรุ่งนี้จะไปตลาดจตุจักร{P}', rom: 'phrûng-níi jà pai ta-làat ja-tu-jàk {P}', en: "Tomorrow I'm going to Chatuchak market." },
      { who: 'B', th: 'ดีจัง จะไปกับใคร{Pbq}', rom: 'dii jang, jà pai kàp khrai {Pbq}', en: 'Nice! Who are you going with?' },
      { who: 'A', th: 'อาจจะไปกับเพื่อน แต่ยังไม่แน่ใจ{P}', rom: 'àat jà pai kàp phûean, tɛ̀ɛ yang mâi nɛ̂ɛ-jai {P}', en: "Maybe with a friend, but I'm not sure yet." },
      { who: 'B', th: 'พรุ่งนี้อาจจะฝนตกนะ{Pbq}', rom: 'phrûng-níi àat jà fǒn tòk ná {Pbq}', en: 'It might rain tomorrow, you know.' },
      { who: 'A', th: 'ถ้าฝนตก จะไปวันอาทิตย์แทน{P}', rom: 'thâa fǒn tòk, jà pai wan aa-thít thɛɛn {P}', en: "If it rains, I'll go on Sunday instead." },
      { who: 'B', th: 'แล้วจะกลับอเมริกาเมื่อไร{Pbq}', rom: 'lɛ́ɛo jà klàp a-mee-ri-kaa mûea-rài {Pbq}', en: 'And when are you going back to America?' },
      { who: 'A', th: 'จะกลับเดือนหน้า แต่ปีหน้าจะมาอีก{P}', rom: 'jà klàp duean nâa, tɛ̀ɛ pii nâa jà maa ìik {P}', en: "I'm going back next month, but I'll come again next year." },
      { who: 'B', th: 'ดีเลย เจอกันวันจันทร์{Pb}', rom: 'dii loei, joe kan wan jan {Pb}', en: 'Great. See you on Monday.' },
      { who: 'A', th: 'เจอกัน{P}', rom: 'joe kan {P}', en: 'See you.' },
    ],
  },
  'in-progress': {
    scene: 'A Thai friend calls you in the evening.', you: 'the friend',
    lines: [
      { who: 'B', th: 'ฮัลโหล กำลังทำอะไรอยู่{Pbq}', rom: 'han-lǒo, kam-lang tham a-rai yùu {Pbq}', en: 'Hello, what are you up to?' },
      { who: 'A', th: 'กำลังทำกับข้าว{P}', rom: 'kam-lang tham kàp-khâao {P}', en: "I'm cooking." },
      { who: 'B', th: 'ทำอะไร{Pbq}', rom: 'tham a-rai {Pbq}', en: 'What are you making?' },
      { who: 'A', th: 'ผัดกะเพรา แต่ยังไม่เสร็จ{P}', rom: 'phàt ka-phrao, tɛ̀ɛ yang mâi sèt {P}', en: "Basil stir-fry, but it's not done yet." },
      { who: 'B', th: 'แฟนอยู่ด้วยไหม{Pbq}', rom: 'fɛɛn yùu dûai mǎi {Pbq}', en: 'Is your partner there too?' },
      { who: 'A', th: 'เขากำลังนอน วันนี้เหนื่อยมาก{P}', rom: 'khǎo kam-lang nɔɔn, wan-níi nùeai mâak {P}', en: "They're sleeping. They were really tired today." },
      { who: 'B', th: 'ตอนนี้ที่นี่ฝนกำลังตกหนัก{Pb}', rom: 'tɔɔn-níi thîi-nîi fǒn kam-lang tòk nàk {Pb}', en: "It's raining hard here right now." },
      { who: 'A', th: 'จริงเหรอ ที่นี่ยังไม่ตก{P}', rom: 'jing rǒe, thîi-nîi yang mâi tòk {P}', en: "Really? It's not raining here yet." },
      { who: 'B', th: '{Ib}ยังทำงานอยู่ ยุ่งมาก{Pb}', rom: '{Ib} yang tham-ngaan yùu, yûng mâak {Pb}', en: "I'm still working. Very busy." },
      { who: 'A', th: 'สู้ๆ เดี๋ยวพรุ่งนี้โทรหา{P}', rom: 'sûu-sûu, dǐao phrûng-níi thoo hǎa {P}', en: "Hang in there. I'll call you tomorrow." },
    ],
  },
  'experience': {
    scene: 'Talking about travel with someone you just met.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'เคยไปเชียงใหม่ไหม{Pbq}', rom: 'khoei pai chiang-mài mǎi {Pbq}', en: 'Have you ever been to Chiang Mai?' },
      { who: 'A', th: 'เคยไปครั้งหนึ่ง สวยมาก{P}', rom: 'khoei pai khráng nùeng, sǔai mâak {P}', en: "I've been once. It's beautiful." },
      { who: 'B', th: 'เคยไปปายไหม{Pbq}', rom: 'khoei pai paai mǎi {Pbq}', en: 'Have you ever been to Pai?' },
      { who: 'A', th: 'ยังไม่เคย แต่อยากไป{P}', rom: 'yang mâi khoei, tɛ̀ɛ yàak pai {P}', en: 'Not yet, but I want to.' },
      { who: 'B', th: 'เคยกินทุเรียนไหม{Pbq}', rom: 'khoei kin thú-rian mǎi {Pbq}', en: 'Have you ever eaten durian?' },
      { who: 'A', th: 'เคยลองกินดูแล้ว ไม่ค่อยชอบ{P}', rom: 'khoei lɔɔng kin duu lɛ́ɛo, mâi khɔ̂i chɔ̂ɔp {P}', en: "I've tried it. I don't really like it." },
      { who: 'B', th: 'จริงเหรอ {Ib}ชอบมาก กินทุกอาทิตย์{Pb}', rom: 'jing rǒe, {Ib} chɔ̂ɔp mâak, kin thúk aa-thít {Pb}', en: 'Really? I love it. I eat it every week.' },
      { who: 'A', th: 'แต่ข้าวเหนียวมะม่วง {I}กินทุกวัน{P}', rom: 'tɛ̀ɛ khâao-nǐao ma-mûang, {I} kin thúk wan {P}', en: 'But mango sticky rice, I eat every day.' },
      { who: 'B', th: 'เหมือนกันเลย{Pb}', rom: 'mǔean kan loei {Pb}', en: 'Same here!' },
    ],
  },
  'ability': {
    scene: 'Eating at a noodle shop with a chatty owner.', you: 'the customer',
    lines: [
      { who: 'B', th: 'กินเผ็ดได้ไหม{Pbq}', rom: 'kin phèt dâi mǎi {Pbq}', en: 'Can you eat spicy food?' },
      { who: 'A', th: 'กินได้นิดหน่อย ไม่เอาเผ็ดมาก{P}', rom: 'kin dâi nít-nɔ̀i, mâi ao phèt mâak {P}', en: 'A little. Not too spicy, please.' },
      { who: 'B', th: 'พูดภาษาไทยเก่งนะ{Pbq}', rom: 'phûut phaa-sǎa thai kèng ná {Pbq}', en: 'You speak Thai well!' },
      { who: 'A', th: 'ยังไม่เก่ง พูดได้นิดหน่อย{P}', rom: 'yang mâi kèng, phûut dâi nít-nɔ̀i {P}', en: "Not really. I can speak a little." },
      { who: 'B', th: 'อ่านภาษาไทยได้ไหม{Pbq}', rom: 'àan phaa-sǎa thai dâi mǎi {Pbq}', en: 'Can you read Thai?' },
      { who: 'A', th: 'อ่านได้นิดหน่อย แต่เขียนไม่เป็น{P}', rom: 'àan dâi nít-nɔ̀i, tɛ̀ɛ khǐan mâi pen {P}', en: "I can read a little, but I can't write." },
      { who: 'B', th: 'ไม่เป็นไร ค่อยๆ เรียน{Pb}', rom: 'mâi pen rai, khɔ̂i-khɔ̂i rian {Pb}', en: 'Never mind. Learn it little by little.' },
      { who: 'A', th: 'ขอโทษ{P} สูบบุหรี่ที่นี่ได้ไหม{Pq}', rom: 'khɔ̌ɔ-thôot {P}, sùup bu-rìi thîi-nîi dâi mǎi {Pq}', en: 'Excuse me, is smoking allowed here?' },
      { who: 'B', th: 'ไม่ได้{Pb} ห้ามสูบบุหรี่ในร้าน', rom: 'mâi dâi {Pb}, hâam sùup bu-rìi nai ráan', en: "No. Smoking isn't allowed in the shop." },
      { who: 'A', th: 'โอเค ไม่เป็นไร{P}', rom: 'oo-khee, mâi pen rai {P}', en: 'OK, no problem.' },
    ],
  },
  'must-should': {
    scene: 'A Thai friend gives you tips before a temple visit.', you: 'the visitor',
    lines: [
      { who: 'B', th: 'พรุ่งนี้จะไปวัดพระแก้วใช่ไหม{Pbq}', rom: 'phrûng-níi jà pai wát phra-kɛ̂ɛo châi mǎi {Pbq}', en: "You're going to the Temple of the Emerald Buddha tomorrow, right?" },
      { who: 'A', th: 'ใช่{P} ต้องจองตั๋วไหม{Pq}', rom: 'châi {P}, tɔ̂ng jɔɔng tǔa mǎi {Pq}', en: 'Yes. Do I need to book a ticket?' },
      { who: 'B', th: 'ไม่ต้องจอง{Pb} แต่ควรไปเช้าๆ', rom: 'mâi tɔ̂ng jɔɔng {Pb}, tɛ̀ɛ khuan pai cháao-cháao', en: 'No need to book. But you should go early.' },
      { who: 'A', th: 'ต้องแต่งตัวยังไง{Pq}', rom: 'tɔ̂ng tɛ̀ng-tua yang-ngai {Pq}', en: 'How do I have to dress?' },
      { who: 'B', th: 'ต้องใส่กางเกงขายาว ห้ามใส่ขาสั้น{Pb}', rom: 'tɔ̂ng sài kaang-keeng khǎa yaao, hâam sài khǎa sân {Pb}', en: 'You must wear long trousers. No shorts.' },
      { who: 'A', th: 'ต้องถอดรองเท้าไหม{Pq}', rom: 'tɔ̂ng thɔ̀ɔt rɔɔng-tháao mǎi {Pq}', en: 'Do I have to take off my shoes?' },
      { who: 'B', th: 'ต้องถอดก่อนเข้าโบสถ์{Pb}', rom: 'tɔ̂ng thɔ̀ɔt kɔ̀ɔn khâo bòot {Pb}', en: 'You have to take them off before going into the chapel.' },
      { who: 'A', th: 'ไปแท็กซี่ดีไหม{Pq}', rom: 'pai thɛ́k-sîi dii mǎi {Pq}', en: 'Should I go by taxi?' },
      { who: 'B', th: 'นั่งเรือดีกว่า{Pb} รถไม่ติด', rom: 'nâng ruea dii kwàa {Pb}, rót mâi tìt', en: 'Better to take the boat. No traffic.' },
      { who: 'A', th: 'ขอบคุณมาก ไม่ต้องห่วง{P}', rom: 'khɔ̀ɔp-khun mâak, mâi tɔ̂ng hùang {P}', en: "Thanks a lot. Don't worry about me." },
    ],
  },
  'wants': {
    scene: 'Deciding where to eat with a friend.', you: 'the friend',
    lines: [
      { who: 'B', th: 'คืนนี้อยากกินอะไร{Pbq}', rom: 'khuen-níi yàak kin a-rai {Pbq}', en: 'What do you feel like eating tonight?' },
      { who: 'A', th: 'อะไรก็ได้ แล้วแต่คุณ{P}', rom: 'a-rai kɔ̂ɔ dâi, lɛ́ɛo-tɛ̀ɛ khun {P}', en: "Anything's fine. It's up to you." },
      { who: 'B', th: 'ชอบอาหารญี่ปุ่นไหม{Pbq}', rom: 'chɔ̂ɔp aa-hǎan yîi-pùn mǎi {Pbq}', en: 'Do you like Japanese food?' },
      { who: 'A', th: 'ไม่ค่อยชอบ ชอบอาหารไทยมากกว่า{P}', rom: 'mâi khɔ̂i chɔ̂ɔp, chɔ̂ɔp aa-hǎan thai mâak kwàa {P}', en: 'Not really. I prefer Thai food.' },
      { who: 'B', th: 'งั้นไปร้านส้มตำไหม{Pbq}', rom: 'ngán pai ráan sôm-tam mǎi {Pbq}', en: 'Then how about a som tam place?' },
      { who: 'A', th: 'ดีเลย อยากลองกินลาบด้วย{P}', rom: 'dii loei, yàak lɔɔng kin lâap dûai {P}', en: 'Great. I want to try larb too.' },
      { who: 'B', th: 'น้องสาว{Ib}มาด้วยได้ไหม{Pbq}', rom: 'nɔ́ɔng-sǎao {Ib} maa dûai dâi mǎi {Pbq}', en: 'Can my younger sister come too?' },
      { who: 'A', th: 'ได้สิ ยิ่งเยอะยิ่งสนุก{P}', rom: 'dâi sì, yîng yóe yîng sa-nùk {P}', en: 'Of course. The more the merrier.' },
      { who: 'B', th: 'อยากได้โต๊ะข้างนอกหรือข้างใน{Pbq}', rom: 'yàak dâi tó khâang-nɔ̂ɔk rǔue khâang-nai {Pbq}', en: 'Do you want a table outside or inside?' },
      { who: 'A', th: 'ข้างในดีกว่า ข้างนอกร้อน{P}', rom: 'khâang-nai dii kwàa, khâang-nɔ̂ɔk rɔ́ɔn {P}', en: "Inside is better. It's hot outside." },
    ],
  },
  'classifiers': {
    scene: 'Buying food and drinks for a picnic.', you: 'the shopper',
    lines: [
      { who: 'B', th: 'รับอะไรดี{Pbq}', rom: 'ráp a-rai dii {Pbq}', en: 'What can I get you?' },
      { who: 'A', th: 'ขอน้ำสองขวด กับเบียร์สามกระป๋อง{P}', rom: 'khɔ̌ɔ náam sɔ̌ɔng khùat, kàp bia sǎam kra-pɔ̌ng {P}', en: 'Two bottles of water and three cans of beer, please.' },
      { who: 'B', th: 'เอาเย็นไหม{Pbq}', rom: 'ao yen mǎi {Pbq}', en: 'Cold ones?' },
      { who: 'A', th: 'เอาเย็น แล้วก็ขนมปังสองถุง{P}', rom: 'ao yen, lɛ́ɛo kɔ̂ɔ kha-nǒm-pang sɔ̌ɔng thǔng {P}', en: 'Cold. And two bags of bread.' },
      { who: 'B', th: 'ไข่ต้มเอากี่ฟอง{Pbq}', rom: 'khài tôm ao kìi fɔɔng {Pbq}', en: 'How many boiled eggs?' },
      { who: 'A', th: 'หกฟอง{P}', rom: 'hòk fɔɔng {P}', en: 'Six.' },
      { who: 'B', th: 'ต้องการถุงไหม{Pbq}', rom: 'tɔ̂ng-kaan thǔng mǎi {Pbq}', en: 'Do you need a bag?' },
      { who: 'A', th: 'ไม่ต้อง มีกระเป๋าแล้ว{P}', rom: 'mâi tɔ̂ng, mii kra-pǎo lɛ́ɛo {P}', en: 'No need, I have a bag.' },
      { who: 'B', th: 'ทั้งหมดสามร้อยยี่สิบบาท{Pb}', rom: 'tháng-mòt sǎam rɔ́ɔi yîi-sìp bàat {Pb}', en: "That's three hundred and twenty baht altogether." },
      { who: 'A', th: 'ขอน้ำเพิ่มอีกหนึ่งขวด{P}', rom: 'khɔ̌ɔ náam phôem ìik nùeng khùat {P}', en: 'One more bottle of water, please.' },
    ],
  },
  'connectors': {
    scene: 'You arrive late to meet a friend at the cinema.', you: 'the friend',
    lines: [
      { who: 'B', th: 'ทำไมมาสาย{Pbq}', rom: 'tham-mai maa sǎai {Pbq}', en: 'Why are you late?' },
      { who: 'A', th: 'ขอโทษ{P} มาสายเพราะรถติดมาก', rom: 'khɔ̌ɔ-thôot {P}, maa sǎai phrɔ́ rót tìt mâak', en: "Sorry. I'm late because the traffic was terrible." },
      { who: 'B', th: 'ไม่เป็นไร แต่หนังเริ่มแล้ว{Pb}', rom: 'mâi pen rai, tɛ̀ɛ nǎng rôem lɛ́ɛo {Pb}', en: 'Never mind, but the movie has started.' },
      { who: 'A', th: 'งั้นไปกินข้าวก่อน แล้วค่อยดูรอบหน้า{P}', rom: 'ngán pai kin khâao kɔ̀ɔn, lɛ́ɛo khɔ̂i duu rɔ̂ɔp nâa {P}', en: "Then let's eat first, and watch the next showing." },
      { who: 'B', th: 'ดีเลย ถ้าหิวก็ไปร้านข้างๆ{Pb}', rom: 'dii loei, thâa hǐu kɔ̂ɔ pai ráan khâang-khâang {Pb}', en: "Good idea. If you're hungry, let's go to the place next door." },
      { who: 'A', th: 'ถึงจะแพง แต่อร่อย{P}', rom: 'thǔeng jà phɛɛng, tɛ̀ɛ a-rɔ̀i {P}', en: "Even though it's expensive, it's delicious." },
      { who: 'B', th: 'เมื่อวานโทรหา ทำไมไม่รับ{Pbq}', rom: 'mûea-waan thoo hǎa, tham-mai mâi ráp {Pbq}', en: "I called you yesterday. Why didn't you answer?" },
      { who: 'A', th: 'แบตหมด ก็เลยไม่ได้รับ{P}', rom: 'bɛ̀t mòt, kɔ̂ɔ loei mâi dâi ráp {P}', en: "My battery was dead, so I didn't pick up." },
      { who: 'B', th: 'หลังจากกินข้าว ไปเดินเล่นกันไหม{Pbq}', rom: 'lǎng jàak kin khâao, pai doen lên kan mǎi {Pbq}', en: 'After we eat, shall we go for a walk?' },
      { who: 'A', th: 'ได้ แต่ต้องกลับก่อนสี่ทุ่ม{P}', rom: 'dâi, tɛ̀ɛ tɔ̂ng klàp kɔ̀ɔn sìi thûm {P}', en: 'Sure, but I have to be home before ten.' },
    ],
  },
  'opinions': {
    scene: 'Leaving a restaurant with a friend.', you: 'the friend',
    lines: [
      { who: 'B', th: 'อาหารร้านนี้เป็นยังไงบ้าง{Pbq}', rom: 'aa-hǎan ráan níi pen yang-ngai bâang {Pbq}', en: 'How was the food here?' },
      { who: 'A', th: 'ค่อนข้างดี แต่สำหรับ{I} เผ็ดไป{P}', rom: 'khɔ̂n-khâang dii, tɛ̀ɛ sǎm-ràp {I}, phèt pai {P}', en: "Quite good, but for me it's too spicy." },
      { who: 'B', th: 'จริงเหรอ {Ib}คิดว่าไม่เผ็ดเลย{Pb}', rom: 'jing rǒe, {Ib} khít wâa mâi phèt loei {Pb}', en: "Really? I didn't think it was spicy at all." },
      { who: 'A', th: 'ต้มยำอร่อยมาก แต่ส้มตำก็งั้นๆ{P}', rom: 'tôm-yam a-rɔ̀i mâak, tɛ̀ɛ sôm-tam kɔ̂ɔ ngán-ngán {P}', en: 'The tom yum was delicious, but the som tam was so-so.' },
      { who: 'B', th: 'เห็นด้วย ร้านข้างๆ อร่อยกว่า{Pb}', rom: 'hěn dûai, ráan khâang-khâang a-rɔ̀i kwàa {Pb}', en: 'I agree. The place next door is better.' },
      { who: 'A', th: 'แล้วหนังเมื่อวาน คิดว่ายังไง{Pq}', rom: 'lɛ́ɛo nǎng mûea-waan, khít wâa yang-ngai {Pq}', en: "And yesterday's movie, what did you think?" },
      { who: 'B', th: 'น่าเบื่อ ยาวไป{Pb}', rom: 'nâa bùea, yaao pai {Pb}', en: 'Boring. Too long.' },
      { who: 'A', th: 'ไม่ค่อยเห็นด้วย {I}คิดว่าน่าสนใจ{P}', rom: 'mâi khɔ̂i hěn dûai, {I} khít wâa nâa sǒn-jai {P}', en: "I don't really agree. I thought it was interesting." },
      { who: 'B', th: 'แล้วแต่คน{Pb}', rom: 'lɛ́ɛo-tɛ̀ɛ khon {Pb}', en: 'It depends on the person.' },
      { who: 'A', th: 'คุณพูดถูก{P}', rom: 'khun phûut thùuk {P}', en: "You're right." },
    ],
  },
  'people': {
    scene: 'A friend asks about your new colleague.', you: 'yourself',
    lines: [
      { who: 'B', th: 'เพื่อนร่วมงานใหม่เป็นคนยังไง{Pbq}', rom: 'phûean rûam ngaan mài pen khon yang-ngai {Pbq}', en: "What's your new colleague like?" },
      { who: 'A', th: 'เป็นคนใจดี ขยันมาก{P}', rom: 'pen khon jai-dii, kha-yǎn mâak {P}', en: "They're kind, and very hardworking." },
      { who: 'B', th: 'หน้าตาเป็นยังไง{Pbq}', rom: 'nâa-taa pen yang-ngai {Pbq}', en: 'What do they look like?' },
      { who: 'A', th: 'สูง ผอม ผมยาว ใส่แว่น{P}', rom: 'sǔung, phɔ̌ɔm, phǒm yaao, sài wɛ̂n {P}', en: 'Tall, thin, long hair, wears glasses.' },
      { who: 'B', th: 'อายุเท่าไร{Pbq}', rom: 'aa-yú thâo-rài {Pbq}', en: 'How old?' },
      { who: 'A', th: 'น่าจะอายุเท่ากับ{I}{P}', rom: 'nâa jà aa-yú thâo kàp {I} {P}', en: 'Probably the same age as me.' },
      { who: 'B', th: 'เป็นคนเงียบๆ ไหม{Pbq}', rom: 'pen khon ngîap-ngîap mǎi {Pbq}', en: 'Are they the quiet type?' },
      { who: 'A', th: 'ตอนแรกขี้อายนิดหน่อย แต่ตอนนี้เป็นกันเองมาก{P}', rom: 'tɔɔn rɛ̂ɛk khîi-aai nít-nɔ̀i, tɛ̀ɛ tɔɔn-níi pen kan-eeng mâak {P}', en: 'A bit shy at first, but now very friendly.' },
      { who: 'B', th: 'ดีจัง{Pb}', rom: 'dii jang {Pb}', en: "That's nice." },
    ],
  },
  'describing-places': {
    scene: 'A Thai friend asks about your hometown.', you: 'yourself',
    lines: [
      { who: 'B', th: 'บ้านเกิดอยู่ที่ไหน{Pbq}', rom: 'bâan kòet yùu thîi-nǎi {Pbq}', en: 'Where is your hometown?' },
      { who: 'A', th: 'อยู่เมืองเล็กๆ ใกล้ทะเล{P}', rom: 'yùu mueang lék-lék klâi tha-lee {P}', en: "It's a small town near the sea." },
      { who: 'B', th: 'ที่นั่นเป็นยังไง{Pbq}', rom: 'thîi-nân pen yang-ngai {Pbq}', en: "What's it like there?" },
      { who: 'A', th: 'เงียบ สะอาด วิวสวยมาก{P}', rom: 'ngîap, sa-àat, wiu sǔai mâak {P}', en: 'Quiet, clean, and the view is beautiful.' },
      { who: 'B', th: 'ร้อนเหมือนกรุงเทพไหม{Pbq}', rom: 'rɔ́ɔn mǔean krung-thêep mǎi {Pbq}', en: 'Is it hot like Bangkok?' },
      { who: 'A', th: 'ไม่ร้อนเท่ากรุงเทพ หน้าหนาวมีหิมะด้วย{P}', rom: 'mâi rɔ́ɔn thâo krung-thêep, nâa nǎao mii hì-má dûai {P}', en: "Not as hot as Bangkok. In winter there's even snow." },
      { who: 'B', th: 'ว้าว อยากไปจัง{Pb}', rom: 'wáao, yàak pai jang {Pb}', en: "Wow, I'd love to go." },
      { who: 'A', th: 'แต่ไม่ค่อยสะดวก ต้องมีรถ{P}', rom: 'tɛ̀ɛ mâi khɔ̂i sa-dùak, tɔ̂ng mii rót {P}', en: "But it's not very convenient. You need a car." },
      { who: 'B', th: 'กรุงเทพคึกคักกว่า แต่เสียงดัง{Pb}', rom: 'krung-thêep khúek-khák kwàa, tɛ̀ɛ sǐang dang {Pb}', en: 'Bangkok is livelier, but noisy.' },
      { who: 'A', th: 'ใช่ {I}ชอบที่เงียบๆ มากกว่า{P}', rom: 'châi, {I} chɔ̂ɔp thîi ngîap-ngîap mâak kwàa {P}', en: 'Yes. I prefer quiet places.' },
    ],
  },
  'routine': {
    scene: 'A friend asks about your typical day.', you: 'yourself',
    lines: [
      { who: 'B', th: 'ปกติตื่นกี่โมง{Pbq}', rom: 'pòk-ka-tì tùuen kìi moong {Pbq}', en: 'What time do you usually get up?' },
      { who: 'A', th: 'ตื่นหกโมงเช้า แล้วก็ไปวิ่ง{P}', rom: 'tùuen hòk moong cháao, lɛ́ɛo kɔ̂ɔ pai wîng {P}', en: 'I get up at six, and then go for a run.' },
      { who: 'B', th: 'เช้ามาก ออกกำลังกายทุกวันเหรอ{Pbq}', rom: 'cháao mâak, ɔ̀ɔk-kam-lang-kaai thúk wan rǒe {Pbq}', en: 'So early! You exercise every day?' },
      { who: 'A', th: 'เกือบทุกวัน หลังจากนั้นอาบน้ำ กินข้าวเช้า{P}', rom: 'kùeap thúk wan, lǎng jàak nán àap-náam, kin khâao cháao {P}', en: 'Almost every day. After that I shower and have breakfast.' },
      { who: 'B', th: 'ไปทำงานยังไง{Pbq}', rom: 'pai tham-ngaan yang-ngai {Pbq}', en: 'How do you get to work?' },
      { who: 'A', th: 'นั่งรถไฟฟ้า เพราะไม่ชอบรถติด{P}', rom: 'nâng rót-fai-fáa, phrɔ́ mâi chɔ̂ɔp rót tìt {P}', en: "The Skytrain, because I don't like traffic jams." },
      { who: 'B', th: 'กลับบ้านกี่โมง{Pbq}', rom: 'klàp bâan kìi moong {Pbq}', en: 'What time do you get home?' },
      { who: 'A', th: 'ปกติกลับถึงบ้านหกโมงเย็น{P}', rom: 'pòk-ka-tì klàp thǔeng bâan hòk moong yen {P}', en: 'Usually at six in the evening.' },
      { who: 'B', th: 'ตอนเย็นทำอะไร{Pbq}', rom: 'tɔɔn yen tham a-rai {Pbq}', en: 'What do you do in the evening?' },
      { who: 'A', th: 'บางทีก็ทำกับข้าวเอง ไม่ค่อยดูทีวี{P}', rom: 'baang-thii kɔ̂ɔ tham kàp-khâao eeng, mâi khɔ̂i duu thii-wii {P}', en: "Sometimes I cook. I don't watch much TV." },
    ],
  },
  'work-life': {
    scene: "Meeting someone at a friend's birthday party.", you: 'the guest',
    lines: [
      { who: 'B', th: 'ทำงานอะไร{Pbq}', rom: 'tham-ngaan a-rai {Pbq}', en: 'What do you do for work?' },
      { who: 'A', th: '{I}เป็นครูสอนภาษาอังกฤษ{P}', rom: '{I} pen khruu sɔ̌ɔn phaa-sǎa ang-krìt {P}', en: "I'm an English teacher." },
      { who: 'B', th: 'สอนที่ไหน{Pbq}', rom: 'sɔ̌ɔn thîi-nǎi {Pbq}', en: 'Where do you teach?' },
      { who: 'A', th: 'สอนที่โรงเรียนแถวสุขุมวิท{P}', rom: 'sɔ̌ɔn thîi roong-rian thɛ̌ɛo sù-khǔm-wít {P}', en: 'At a school near Sukhumvit.' },
      { who: 'B', th: 'ทำงานกี่โมงถึงกี่โมง{Pbq}', rom: 'tham-ngaan kìi moong thǔeng kìi moong {Pbq}', en: 'What hours do you work?' },
      { who: 'A', th: 'แปดโมงถึงสี่โมงเย็น{P}', rom: 'pɛ̀ɛt moong thǔeng sìi moong yen {P}', en: 'Eight until four.' },
      { who: 'B', th: 'ชอบงานไหม{Pbq}', rom: 'chɔ̂ɔp ngaan mǎi {Pbq}', en: 'Do you like your job?' },
      { who: 'A', th: 'ชอบ เด็กๆ น่ารัก แต่งานยุ่งมาก{P}', rom: 'chɔ̂ɔp, dèk-dèk nâa-rák, tɛ̀ɛ ngaan yûng mâak {P}', en: 'Yes. The kids are lovely, but it is very busy.' },
      { who: 'A', th: 'แล้วคุณทำงานอะไร{Pq}', rom: 'lɛ́ɛo khun tham-ngaan a-rai {Pq}', en: 'And what do you do?' },
      { who: 'B', th: '{Ib}ทำงานบริษัท แต่วันศุกร์ทำงานที่บ้าน{Pb}', rom: '{Ib} tham-ngaan bɔɔ-ri-sàt, tɛ̀ɛ wan sùk tham-ngaan thîi bâan {Pb}', en: 'I work for a company, but on Fridays I work from home.' },
    ],
  },
  'study': {
    scene: 'A Thai person is surprised to hear you are learning Thai.', you: 'the learner',
    lines: [
      { who: 'B', th: 'เรียนภาษาไทยมานานเท่าไรแล้ว{Pbq}', rom: 'rian phaa-sǎa thai maa naan thâo-rài lɛ́ɛo {Pbq}', en: 'How long have you been learning Thai?' },
      { who: 'A', th: 'เรียนมาสามเดือนแล้ว{P}', rom: 'rian maa sǎam duean lɛ́ɛo {P}', en: "I've been learning for three months." },
      { who: 'B', th: 'เรียนที่โรงเรียน หรือเรียนเอง{Pbq}', rom: 'rian thîi roong-rian, rǔue rian eeng {Pbq}', en: 'At a school, or on your own?' },
      { who: 'A', th: 'เรียนเอง ฟังทุกวัน{P}', rom: 'rian eeng, fang thúk wan {P}', en: 'On my own. I listen every day.' },
      { who: 'B', th: 'ภาษาไทยยากไหม{Pbq}', rom: 'phaa-sǎa thai yâak mǎi {Pbq}', en: 'Is Thai difficult?' },
      { who: 'A', th: 'พูดไม่ค่อยยาก แต่เสียงวรรณยุกต์ยากมาก{P}', rom: 'phûut mâi khɔ̂i yâak, tɛ̀ɛ sǐang wan-na-yúk yâak mâak {P}', en: "Speaking isn't too hard, but the tones are very hard." },
      { who: 'B', th: 'แต่พูดชัดนะ{Pbq}', rom: 'tɛ̀ɛ phûut chát ná {Pbq}', en: 'But you speak very clearly!' },
      { who: 'A', th: 'ขอบคุณ{P} ถ้าพูดผิด ช่วยแก้ให้หน่อย{P}', rom: 'khɔ̀ɔp-khun {P}, thâa phûut phìt, chûai kɛ̂ɛ hâi nɔ̀i {P}', en: 'Thanks. If I say something wrong, please correct me.' },
      { who: 'B', th: 'ได้เลย{Pb}', rom: 'dâi loei {Pb}', en: 'Sure thing.' },
      { who: 'A', th: 'อันนี้พูดว่ายังไง{Pq}', rom: 'an-níi phûut wâa yang-ngai {Pq}', en: '(pointing) How do you say this?' },
    ],
  },
  'weekend': {
    scene: 'Friday evening, talking about the weekend with a friend.', you: 'the friend',
    lines: [
      { who: 'B', th: 'เสาร์อาทิตย์นี้จะทำอะไร{Pbq}', rom: 'sǎo aa-thít níi jà tham a-rai {Pbq}', en: 'What are you doing this weekend?' },
      { who: 'A', th: 'ยังไม่มีแผน อาจจะอยู่บ้านพักผ่อน{P}', rom: 'yang mâi mii phɛ̌ɛn, àat jà yùu bâan phák-phɔ̀n {P}', en: "No plans yet. Maybe I'll stay home and rest." },
      { who: 'B', th: 'ไปเที่ยวทะเลด้วยกันไหม{Pbq}', rom: 'pai thîao tha-lee dûai kan mǎi {Pbq}', en: 'Want to come to the beach with us?' },
      { who: 'A', th: 'ดีเลย ไปที่ไหน{Pq}', rom: 'dii loei, pai thîi-nǎi {Pq}', en: 'Sounds great! Where?' },
      { who: 'B', th: 'ตั้งใจจะไปหัวหิน{Pb}', rom: 'tâng-jai jà pai hǔa-hǐn {Pb}', en: "We're planning to go to Hua Hin." },
      { who: 'A', th: 'ไปกี่วัน{Pq}', rom: 'pai kìi wan {Pq}', en: 'For how many days?' },
      { who: 'B', th: 'ไปสองคืน กลับวันอาทิตย์{Pb}', rom: 'pai sɔ̌ɔng khuen, klàp wan aa-thít {Pb}', en: 'Two nights, back on Sunday.' },
      { who: 'A', th: 'ไปกับใคร{Pq}', rom: 'pai kàp khrai {Pq}', en: 'Who are you going with?' },
      { who: 'B', th: 'กับพี่สาว{Ib} แล้วก็เพื่อนอีกสองคน{Pb}', rom: 'kàp phîi-sǎao {Ib}, lɛ́ɛo kɔ̂ɔ phûean ìik sɔ̌ɔng khon {Pb}', en: 'With my older sister, and two other friends.' },
      { who: 'A', th: 'โอเค ไปด้วย{P}', rom: 'oo-khee, pai dûai {P}', en: "OK, I'm in." },
    ],
  },
  'body': {
    scene: 'At a clinic, telling the doctor what is wrong.', you: 'the patient',
    lines: [
      { who: 'B', th: 'เป็นอะไรมา{Pbq}', rom: 'pen a-rai maa {Pbq}', en: "What's the problem?" },
      { who: 'A', th: 'เจ็บคอ ไอ แล้วก็น้ำมูกไหล{P}', rom: 'jèp khɔɔ, ai, lɛ́ɛo kɔ̂ɔ náam-mûuk lǎi {P}', en: 'I have a sore throat, a cough, and a runny nose.' },
      { who: 'B', th: 'เป็นตั้งแต่เมื่อไร{Pbq}', rom: 'pen tâng-tɛ̀ɛ mûea-rài {Pbq}', en: 'Since when?' },
      { who: 'A', th: 'เป็นตั้งแต่เมื่อวาน{P}', rom: 'pen tâng-tɛ̀ɛ mûea-waan {P}', en: 'Since yesterday.' },
      { who: 'B', th: 'มีไข้ไหม{Pbq}', rom: 'mii khâi mǎi {Pbq}', en: 'Do you have a fever?' },
      { who: 'A', th: 'ไม่มีไข้ แต่เวียนหัวนิดหน่อย{P}', rom: 'mâi mii khâi, tɛ̀ɛ wian hǔa nít-nɔ̀i {P}', en: "No fever, but I'm a little dizzy." },
      { who: 'B', th: 'เจ็บตรงไหนอีกไหม{Pbq}', rom: 'jèp trong nǎi ìik mǎi {Pbq}', en: 'Does it hurt anywhere else?' },
      { who: 'A', th: 'ปวดหลังนิดหน่อย{P}', rom: 'pùat lǎng nít-nɔ̀i {P}', en: 'My back aches a little.' },
      { who: 'B', th: 'เป็นหวัด{Pb} กินยาหลังอาหาร แล้วก็พักผ่อนเยอะๆ', rom: 'pen wàt {Pb}, kin yaa lǎng aa-hǎan, lɛ́ɛo kɔ̂ɔ phák-phɔ̀n yóe-yóe', en: "It's a cold. Take the medicine after meals, and get lots of rest." },
      { who: 'A', th: 'ต้องกลับมาหาหมออีกไหม{Pq}', rom: 'tɔ̂ng klàp maa hǎa mɔ̌ɔ ìik mǎi {Pq}', en: 'Do I need to come back?' },
    ],
  },
  'housing': {
    scene: 'Viewing a condo to rent.', you: 'the renter',
    lines: [
      { who: 'A', th: 'มีห้องให้เช่าไหม{Pq}', rom: 'mii hɔ̂ng hâi châo mǎi {Pq}', en: 'Do you have a room for rent?' },
      { who: 'B', th: 'มี{Pb} ห้องชั้นสิบ วิวสวย', rom: 'mii {Pb}, hɔ̂ng chán sìp, wiu sǔai', en: 'Yes, a room on the tenth floor with a nice view.' },
      { who: 'A', th: 'ค่าเช่าเดือนละเท่าไร{Pq}', rom: 'khâa châo duean lá thâo-rài {Pq}', en: 'How much is the rent per month?' },
      { who: 'B', th: 'เดือนละหนึ่งหมื่นสองพันบาท{Pb}', rom: 'duean lá nùeng mùean sɔ̌ɔng phan bàat {Pb}', en: 'Twelve thousand baht a month.' },
      { who: 'A', th: 'รวมค่าน้ำค่าไฟไหม{Pq}', rom: 'ruam khâa náam khâa fai mǎi {Pq}', en: 'Does that include water and electricity?' },
      { who: 'B', th: 'ไม่รวม{Pb} มัดจำสองเดือน สัญญาหนึ่งปี', rom: 'mâi ruam {Pb}, mát-jam sɔ̌ɔng duean, sǎn-yaa nùeng pii', en: "Not included. Two months' deposit, and a one-year contract." },
      { who: 'A', th: 'ขอดูห้องได้ไหม{Pq}', rom: 'khɔ̌ɔ duu hɔ̂ng dâi mǎi {Pq}', en: 'Can I see the room?' },
      { who: 'B', th: 'ได้{Pb} มีเฟอร์นิเจอร์ครบ', rom: 'dâi {Pb}, mii foe-ni-joe khróp', en: "Sure. It's fully furnished." },
      { who: 'A', th: 'แอร์เสีย ช่วยซ่อมก่อนได้ไหม{Pq}', rom: 'ɛɛ sǐa, chûai sɔ̂m kɔ̀ɔn dâi mǎi {Pq}', en: 'The air-con is broken. Could you fix it first?' },
      { who: 'B', th: 'ได้{Pb} พรุ่งนี้ช่างจะมาซ่อม', rom: 'dâi {Pb}, phrûng-níi châang jà maa sɔ̂m', en: 'Yes. The repairman will come tomorrow.' },
    ],
  },
  'weather-talk': {
    scene: 'Small talk with a neighbour on a stormy afternoon.', you: 'the neighbour',
    lines: [
      { who: 'B', th: 'เมื่อคืนฝนตกหนักมาก{Pb}', rom: 'mûea-khuen fǒn tòk nàk mâak {Pb}', en: 'It rained really hard last night.' },
      { who: 'A', th: 'ใช่ {I}เปียกหมดเลย{P}', rom: 'châi, {I} pìak mòt loei {P}', en: 'Yes, I got completely soaked.' },
      { who: 'B', th: 'พยากรณ์อากาศบอกว่าพายุกำลังมา{Pb}', rom: 'pha-yaa-kɔɔn aa-kàat bɔ̀ɔk wâa phaa-yú kam-lang maa {Pb}', en: 'The forecast says a storm is coming.' },
      { who: 'A', th: 'จริงเหรอ วันนี้ร้อนกว่าเมื่อวานอีก{P}', rom: 'jing rǒe, wan-níi rɔ́ɔn kwàa mûea-waan ìik {P}', en: "Really? Today is even hotter than yesterday." },
      { who: 'B', th: 'สามสิบหกองศา ร้อนขึ้นเรื่อยๆ{Pb}', rom: 'sǎam-sìp-hòk ong-sǎa, rɔ́ɔn khûen rûeai-rûeai {Pb}', en: 'Thirty-six degrees. It keeps getting hotter.' },
      { who: 'A', th: 'หน้าฝนเริ่มเมื่อไร{Pq}', rom: 'nâa fǒn rôem mûea-rài {Pq}', en: 'When does the rainy season start?' },
      { who: 'B', th: 'ปกติเดือนพฤษภาคม{Pb}', rom: 'pòk-ka-tì duean phrúet-sa-phaa-khom {Pb}', en: 'Usually in May.' },
      { who: 'A', th: '{I}ชอบหน้าหนาวที่สุด อากาศเย็นสบาย{P}', rom: '{I} chɔ̂ɔp nâa nǎao thîi-sùt, aa-kàat yen sa-baai {P}', en: 'I like the cool season best. The weather is cool and pleasant.' },
      { who: 'B', th: 'แต่หน้าหนาวฝุ่นเยอะ ควรใส่หน้ากาก{Pb}', rom: 'tɛ̀ɛ nâa nǎao fùn yóe, khuan sài nâa-kàak {Pb}', en: "But there's a lot of smog then. You should wear a mask." },
      { who: 'A', th: 'ที่บ้าน{I} หน้าหนาวมีหิมะ{P}', rom: 'thîi bâan {I}, nâa nǎao mii hì-má {P}', en: "Where I'm from, there's snow in winter." },
    ],
  },
  'messaging': {
    scene: 'Calling an office to reach a friend.', you: 'the caller',
    lines: [
      { who: 'B', th: 'ฮัลโหล{Pb}', rom: 'han-lǒo {Pb}', en: 'Hello?' },
      { who: 'A', th: 'ฮัลโหล ขอสายคุณนิด{P}', rom: 'han-lǒo, khɔ̌ɔ sǎai khun nít {P}', en: 'Hello, may I speak to Khun Nid?' },
      { who: 'B', th: 'ใครพูด{Pbq}', rom: 'khrai phûut {Pbq}', en: "Who's speaking?" },
      { who: 'A', th: '{I}ชื่อแซม เป็นเพื่อนคุณนิด{P}', rom: '{I} chûue sɛɛm, pen phûean khun nít {P}', en: "My name is Sam. I'm a friend of Khun Nid." },
      { who: 'B', th: 'ตอนนี้คุณนิดติดประชุม{Pb}', rom: 'tɔɔn-níi khun nít tìt pra-chum {Pb}', en: 'Khun Nid is in a meeting right now.' },
      { who: 'A', th: 'ขอโทษ{P} ไม่ค่อยได้ยิน สัญญาณไม่ดี', rom: 'khɔ̌ɔ-thôot {P}, mâi khɔ̂i dâi-yin, sǎn-yaan mâi dii', en: "Sorry, I can't hear you well. The signal is bad." },
      { who: 'B', th: 'คุณนิด ติดประชุม{Pb}', rom: 'khun nít, tìt pra-chum {Pb}', en: 'Khun Nid. Is in a meeting.' },
      { who: 'A', th: 'ฝากข้อความได้ไหม{Pq}', rom: 'fàak khɔ̂ɔ-khwaam dâi mǎi {Pq}', en: 'Can I leave a message?' },
      { who: 'B', th: 'ได้{Pb}', rom: 'dâi {Pb}', en: 'Of course.' },
      { who: 'A', th: 'ช่วยบอกให้โทรกลับหน่อย หรือส่งไลน์มาก็ได้{P}', rom: 'chûai bɔ̀ɔk hâi thoo klàp nɔ̀i, rǔue sòng lai maa kɔ̂ɔ dâi {P}', en: 'Please ask them to call me back, or a LINE message is fine.' },
    ],
  },
  'invitations': {
    scene: 'Inviting a Thai friend out, then being invited back.', you: 'the friend',
    lines: [
      { who: 'A', th: 'วันเสาร์ว่างไหม{Pq}', rom: 'wan sǎo wâang mǎi {Pq}', en: 'Are you free on Saturday?' },
      { who: 'B', th: 'ว่าง{Pb} มีอะไรเหรอ', rom: 'wâang {Pb}, mii a-rai rǒe', en: "I'm free. What's up?" },
      { who: 'A', th: 'ไปดูหนังกันไหม{Pq} {I}เลี้ยงเอง', rom: 'pai duu nǎng kan mǎi {Pq}, {I} líang eeng', en: "Shall we go and see a movie? It's my treat." },
      { who: 'B', th: 'ดีเลย ขอบคุณที่ชวน{Pb}', rom: 'dii loei, khɔ̀ɔp-khun thîi chuan {Pb}', en: 'Sounds great. Thanks for inviting me.' },
      { who: 'A', th: 'เจอกันกี่โมงดี{Pq}', rom: 'joe kan kìi moong dii {Pq}', en: 'What time shall we meet?' },
      { who: 'B', th: 'บ่ายสองโมงที่สยาม{Pb}', rom: 'bàai sɔ̌ɔng moong thîi sa-yǎam {Pb}', en: 'Two in the afternoon, at Siam.' },
      { who: 'A', th: 'ได้เลย{P}', rom: 'dâi loei {P}', en: 'Perfect.' },
      { who: 'B', th: 'แล้ววันอาทิตย์ ไปกินข้าวบ้าน{Ib}ไหม{Pbq}', rom: 'lɛ́ɛo wan aa-thít, pai kin khâao bâan {Ib} mǎi {Pbq}', en: 'And on Sunday, would you like to come for dinner at my place?' },
      { who: 'A', th: 'ขอโทษ วันอาทิตย์มีนัดแล้ว{P}', rom: 'khɔ̌ɔ-thôot, wan aa-thít mii nát lɛ́ɛo {P}', en: 'Sorry, I already have plans on Sunday.' },
      { who: 'B', th: 'ไม่เป็นไร ไว้คราวหน้านะ{Pbq}', rom: 'mâi pen rai, wái khraao nâa ná {Pbq}', en: 'Never mind. Next time, then.' },
    ],
  },
  'past-time': {
    scene: "Catching up with a friend you haven't seen in a while.", you: 'the friend',
    lines: [
      { who: 'B', th: 'ไม่ได้เจอกันนานเลย{Pb}', rom: 'mâi dâi joe kan naan loei {Pb}', en: 'Long time no see!' },
      { who: 'A', th: 'ใช่ {I}เพิ่งกลับมาอาทิตย์ที่แล้ว{P}', rom: 'châi, {I} phôeng klàp maa aa-thít thîi lɛ́ɛo {P}', en: 'Yes. I just got back last week.' },
      { who: 'B', th: 'ไปไหนมา{Pbq}', rom: 'pai nǎi maa {Pbq}', en: 'Where have you been?' },
      { who: 'A', th: 'กลับอเมริกา ไปเยี่ยมครอบครัว{P}', rom: 'klàp a-mee-ri-kaa, pai yîam khrɔ̂ɔp-khrua {P}', en: 'Back to America, to visit family.' },
      { who: 'B', th: 'ไปตั้งแต่เมื่อไร{Pbq}', rom: 'pai tâng-tɛ̀ɛ mûea-rài {Pbq}', en: 'Since when?' },
      { who: 'A', th: 'ไปตั้งแต่เดือนที่แล้ว{P}', rom: 'pai tâng-tɛ̀ɛ duean thîi lɛ́ɛo {P}', en: 'Since last month.' },
      { who: 'B', th: 'เมื่อวานทำอะไร{Pbq}', rom: 'mûea-waan tham a-rai {Pbq}', en: 'What did you do yesterday?' },
      { who: 'A', th: 'เมื่อวานนอนทั้งวัน ยังเหนื่อยอยู่{P}', rom: 'mûea-waan nɔɔn tháng wan, yang nùeai yùu {P}', en: "Yesterday I slept all day. I'm still tired." },
      { who: 'B', th: 'เมื่อกี้{Ib}เห็นแฟนคุณที่ตลาด{Pb}', rom: 'mûea-kíi {Ib} hěn fɛɛn khun thîi ta-làat {Pb}', en: 'I saw your partner at the market just now.' },
      { who: 'A', th: 'ใช่ เมื่อเช้าเขาบอกว่าจะไปตลาด{P}', rom: 'châi, mûea-cháao khǎo bɔ̀ɔk wâa jà pai ta-làat {P}', en: 'Yes, this morning they said they were going to the market.' },
    ],
  },
  'story': {
    scene: 'Telling a friend about a bad morning.', you: 'the storyteller',
    lines: [
      { who: 'B', th: 'ดูเหนื่อยๆ เกิดอะไรขึ้น{Pbq}', rom: 'duu nùeai-nùeai, kòet a-rai khûen {Pbq}', en: 'You look tired. What happened?' },
      { who: 'A', th: 'เมื่อวานตื่นสาย เพราะนาฬิกาปลุกไม่ดัง{P}', rom: 'mûea-waan tùuen sǎai, phrɔ́ naa-li-kaa plùk mâi dang {P}', en: "Yesterday I woke up late, because my alarm didn't go off." },
      { who: 'B', th: 'แล้วไงต่อ{Pbq}', rom: 'lɛ́ɛo ngai tɔ̀ɔ {Pbq}', en: 'And then what?' },
      { who: 'A', th: 'ก็เลยพลาดรถเมล์ เลยต้องนั่งแท็กซี่{P}', rom: 'kɔ̂ɔ loei phlâat rót-mee, loei tɔ̂ng nâng thɛ́k-sîi {P}', en: 'So I missed the bus, and had to take a taxi.' },
      { who: 'B', th: 'โชคดีที่มีแท็กซี่{Pb}', rom: 'chôok dii thîi mii thɛ́k-sîi {Pb}', en: 'Lucky there was a taxi.' },
      { who: 'A', th: 'แต่รถติดมาก ไปถึงช้าไปครึ่งชั่วโมง{P}', rom: 'tɛ̀ɛ rót tìt mâak, pai thǔeng cháa pai khrûeng chûa-moong {P}', en: 'But the traffic was terrible. I got there half an hour late.' },
      { who: 'B', th: 'หัวหน้าว่าอะไรไหม{Pbq}', rom: 'hǔa-nâa wâa a-rai mǎi {Pbq}', en: 'Did your boss say anything?' },
      { who: 'A', th: 'ตอนแรกหัวหน้าโกรธ แต่หลังจากนั้นหัวเราะ{P}', rom: 'tɔɔn rɛ̂ɛk hǔa-nâa kròot, tɛ̀ɛ lǎng jàak nán hǔa-rɔ́ {P}', en: 'At first my boss was angry, but after that they laughed.' },
      { who: 'B', th: 'ทำไมหัวเราะ{Pbq}', rom: 'tham-mai hǔa-rɔ́ {Pbq}', en: 'Why did they laugh?' },
      { who: 'A', th: 'เพราะหัวหน้าก็มาสายเหมือนกัน สุดท้ายก็โอเค{P}', rom: 'phrɔ́ hǔa-nâa kɔ̂ɔ maa sǎai mǔean kan, sùt-tháai kɔ̂ɔ oo-khee {P}', en: 'Because the boss was late too! In the end it was OK.' },
    ],
  },
};
