// 30-day plan for a trip to Thailand, about 1 hour a day.
// Each day's "focus" assumes about 10 new phrases per session.
window.PLAN = {
  daily: [
    ['30 min', 'Audio session. Answer out loud every time, with the voice set to Both.'],
    ['10 min', 'Free listening: Thai YouTube, podcasts or music. Just catch words you know.'],
    ['15 min', "Speaking: say today's phrases while doing chores, or act out a scene from your trip."],
    ['5 min', 'A second, short session later in the day (reviews only), or replay phrases from the vocabulary list.'],
  ],
  days: [
    { focus: 'Unit 1 · Greetings', tip: 'Get the polite ending into every sentence.' },
    { focus: 'Unit 2 · Getting by', tip: '"I don\'t understand" and "please speak slowly" will save you.' },
    { focus: 'Unit 3 · Food and shopping', tip: 'Practise asking "how much?" at every meal today, in your head.' },
    { focus: 'Finish Unit 3, start Unit 4 · Numbers', tip: 'Count objects around you out loud in Thai.' },
    { focus: 'Unit 4 · Numbers', tip: 'Read prices on receipts out loud in Thai.' },
    { focus: 'Unit 5 · Money and bargaining', tip: 'Numbers and prices are what you will use most. Drill them.' },
    { focus: 'Review day', tip: 'No new phrases. Turn on hands-free mode and review on a walk.', review: true },
    { focus: 'Finish Unit 5', tip: 'Role-play a market: ask the price, bargain, agree.' },
    { focus: 'Unit 6 · Want, have, can', tip: 'Make your own sentences: "I want to go…", "do you have…?"' },
    { focus: 'Finish Unit 6, start Unit 7 · Getting around', tip: 'Listen for tone: near and far sound almost the same.' },
    { focus: 'Unit 7 · Getting around', tip: 'Give yourself directions out loud on your next walk.' },
    { focus: 'Unit 8 · Taxis and transport', tip: '"Please use the meter" is worth knowing by heart.' },
    { focus: 'Finish Unit 8', tip: 'Act out a whole taxi ride: destination, meter, stop here, pay.' },
    { focus: 'Review day', tip: 'No new phrases. Clear all your reviews and play the vocabulary list for Units 1–8.', review: true },
    { focus: 'Unit 9 · At the hotel', tip: 'Imagine your check-in, start to finish.' },
    { focus: 'Finish Unit 9, start Unit 10 · Ordering food', tip: 'Switch to one voice only for a session and see if it is harder.' },
    { focus: 'Unit 10 · Ordering food', tip: 'Order your own dinner out loud in Thai, even at home.' },
    { focus: 'Finish Unit 10, start Unit 11 · About you', tip: 'Prepare a 3-sentence introduction of yourself.' },
    { focus: 'Unit 12 · Time and feelings', tip: 'Describe your day in single Thai words: hot, tired, hungry.' },
    { focus: 'Unit 13 · Health and help', tip: 'Learn these well, and hope you never need them.' },
    { focus: 'Review day', tip: 'No new phrases. Hands-free review on a walk.', review: true },
    { focus: 'Finish Unit 13', tip: 'Learn how to say your own allergies or medicines, if you have any.' },
    { focus: 'Unit 14 · Small talk', tip: 'Thais love it when visitors try. Practise a modest reply to compliments.' },
    { focus: 'Finish Unit 14', tip: 'You have now met every phrase in the course.' },
    { focus: 'Catch-up day', tip: 'Finish any unit you are behind on, or mark ones you know with "I know this unit".' },
    { focus: 'Role-play: restaurant and market', tip: 'Order a full meal and bargain for something, all out loud.', review: true },
    { focus: 'Role-play: taxi and hotel', tip: 'Airport to hotel: taxi, check-in, Wi-Fi, breakfast time.', review: true },
    { focus: 'Numbers and prices drill', tip: 'Play Units 4 and 5 in the vocabulary list. Say random prices out loud.', review: true },
    { focus: 'Reviews and small talk', tip: 'Introduce yourself out loud three times, in different ways.', review: true },
    { focus: 'Final review. You are ready!', tip: 'Clear your reviews and relax. Use what you know from the first day.', review: true },
  ],
};
