"""Generate Thai audio for every phrase in app/course.js, in a male and a female neural voice.

Run after changing the course:   pip install edge-tts   then   python tools/generate_audio.py
Existing files are kept, so only new phrases are generated. Writes:
  audio/male/<id>.mp3, audio/female/<id>.mp3   (id = first 10 hex chars of sha1 of the text)
  app/audio-manifest.js                        (text -> id, used by the app)
"""
import asyncio
import hashlib
import json
import pathlib
import subprocess
import sys

import edge_tts

ROOT = pathlib.Path(__file__).resolve().parent.parent
VOICES = {'male': 'th-TH-NiwatNeural', 'female': 'th-TH-PremwadeeNeural'}
RATE = '-15%'  # the app compensates with playbackRate, see THAI_BASE_RATE in app.js


def key(text):
    return hashlib.sha1(text.encode('utf-8')).hexdigest()[:10]


async def generate(sem, voice, folder, text, failures):
    out = ROOT / 'audio' / folder / f'{key(text)}.mp3'
    if out.exists() and out.stat().st_size > 0:
        return
    out.parent.mkdir(parents=True, exist_ok=True)
    async with sem:
        for attempt in range(4):
            try:
                await edge_tts.Communicate(text, voice, rate=RATE).save(str(out))
                print(f'{folder:6} {text}')
                return
            except Exception as e:  # network hiccups: retry with backoff
                if attempt == 3:
                    failures.append((folder, text, repr(e)))
                await asyncio.sleep(2 * (attempt + 1))


async def main():
    texts = json.loads(subprocess.check_output(['node', str(ROOT / 'tools' / 'list-texts.js')], encoding='utf-8'))
    sem = asyncio.Semaphore(6)
    failures = []
    await asyncio.gather(*(generate(sem, v, f, t, failures) for f, v in VOICES.items() for t in texts))

    manifest = {t: key(t) for t in sorted(texts)}
    (ROOT / 'app' / 'audio-manifest.js').write_text(
        '// Generated by tools/generate_audio.py: Thai text -> audio file id.\n'
        'window.AUDIO = ' + json.dumps(manifest, ensure_ascii=False, indent=1) + ';\n',
        encoding='utf-8')
    print(f'{len(texts)} phrases x {len(VOICES)} voices; {len(failures)} failed')
    for f in failures:
        print('FAILED', *f)
    sys.exit(1 if failures else 0)


asyncio.run(main())
